# The pre-processor options used by the cpp (man cpp for more).
CPPFLAGS  	+= -I../../include -I../../dep/avalon/include -I../../dep/zlib/include -I../../dep/fmt/include -g -O1 -Wall -MMD

# The options used in linking as well as in any direct use of ld.
LDFLAGS   	+= -L../../dep/fmt/lib/linux/ \
				-lpthread -lfmt


# Preheader file.
PREHEADER 	= 

PREHEADERGCH = 


# The target file. Choose the right one.
TARGETPROG 	=

TARGETLIB  	= libCommonLib.a

TARGETSO   	=


# Source directory
SRCDIRS 	= ./

# Target directory
TARGETDIR  	= ../../lib/linux/


## Implicit Section: change the following only when necessary.
##==========================================================================
-include ../../Common.mak

