# The pre-processor options used by the cpp (man cpp for more).
CPPFLAGS  	+= -I../../include/ -g -Wall -MMD

# The options used in linking as well as in any direct use of ld.
LDFLAGS   	+= -L../../lib/linux/ -lAvalonNetwork -lAvalonFramework -lAvalonLogger -lAvalonThread -lAvalonCore -lpthread


# preheader file.
PREHEADER 	= 

PREHEADERGCH = 


# The target file. Choose the right one.
TARGETPROG 	= testclient

TARGETLIB  	=

TARGETSO   	=


#source directory
SRCDIRS 	= ./

#target directory
TARGETDIR  	= ../../bin/linux/


## Implicit Section: change the following only when necessary.
##==========================================================================
-include ../../Common.mak

