#排行榜
CREATE TABLE IF NOT EXISTS `t_sortlist`(
	`guid`		BIGINT	UNSIGNED NOT NULL,				#主键
	`id`		BIGINT	UNSIGNED NOT NULL,				#id
	`sorttype`	TINYINT UNSIGNED NOT NULL,				#排行榜类型
	`name`		VARCHAR(32)	NOT NULL,					#名字
	`quality`	TINYINT UNSIGNED NOT NULL DEFAULT 0,	#品质
	`level`		SMALLINT UNSIGNED NOT NULL DEFAULT 0,	#等级
	`occu`		TINYINT UNSIGNED NOT NULL DEFAULT 0,	#职业
	`sex`		TINYINT UNSIGNED NOT NULL DEFAULT 0,	#性别
	`vip`		TINYINT	UNSIGNED NOT NULL DEFAULT 0,	#vip
	`ownerid`	BIGINT	UNSIGNED NOT NULL DEFAULT 0,	#拥有者id
	`owneraccid`	INT UNSIGNED NOT NULL DEFAULT 0,	#拥有者账号id
	`ownername`	VARCHAR(32)	NOT NULL DEFAULT '',		#拥有者名字
	`value1`	INT UNSIGNED NOT NULL DEFAULT 0,		#数据1
	`value2`	INT UNSIGNED NOT NULL DEFAULT 0,		#数据2
	`value3`	INT UNSIGNED NOT NULL DEFAULT 0,		#数据3
	PRIMARY KEY(`guid`)
);
