# The pre-processor options used by the cpp (man cpp for more).
CPPFLAGS  	+= -I../../include/ -g -O2 -Wall -MMD

# The options used in linking as well as in any direct use of ld.
LDFLAGS   	+= -lpthread 


# preheader file.
PREHEADER 	= 

PREHEADERGCH = 


# The target file. Choose the right one.
TARGETPROG 	=

TARGETLIB  	= libAvalonDatabase.a

TARGETSO   	=


#source directory
SRCDIRS 	= ./

#target directory
TARGETDIR  	= ../../lib/linux/


## Implicit Section: change the following only when necessary.
##==========================================================================
-include ../../Common.mak
