#ifndef _CL_CHEAT_DEFINE_H_
#define _CL_CHEAT_DEFINE_H_


// 玩家作弊原因
enum PlayerCheatReason
{
	// 没有作弊
	PLAYER_CHEAT_REASON_NONE = 0,

	// 修改内存
	PLAYER_CHEAT_REASON_MODIFY_MEMORY,
	// 不同步
	PLAYER_CHEAT_REASON_UNSYNC,
	// 错误的随机数
	PLAYER_CHEAT_REASON_INVALID_CHECKSUM,
	// 结算异常
	PLAYER_CHEAT_REASON_CHECK_RACE_END,
	// 地下城时间异常
	PLAYER_CHEAT_REASON_DUNGEON_USED_TIME_ABNOR,
	// 清图请求MD5错误
	PLAYER_CHEAT_REASON_CLEAT_AREA_REQUEST_MD5_ERR,
	// 结算请求MD5错误
	PLAYER_CHEAT_REASON_RACE_END_REQUEST_MD5_ERR,
	// 拾取掉落请求MD5错误
	PLAYER_CHEAT_REASON_PICK_UP_DROP_REQUEST_MD5_ERR,
	// 最终帧错误
	PLAYER_CHEAT_REASON_LAST_FRAME_ERR,
	// 上报帧错误
	PLAYER_CHEAT_REASON_REPORT_FRAME_ERR,
	// 静态数值非法
	PLAYER_CHEAT_REASON_STATIC_VALUE_INVALID,
	// 加速
	PLAYER_CHAET_REASON_SPEED_UP,
};

#endif