#ifndef _CL_ERRORCODE_H_
#define _CL_ERRORCODE_H_

/**
 *@brief 错误码相关宏定义
 *		错误码由两部分组成，服务器类型加具体错误id
 */
#define CL_FUNCTION_OFFSET_IN_ERRORCODE 100000

#define CL_SUB_FUNCTION_OFFSET 1000

#define CL_ERRORCODE_BEGIN() \
	enum {
#define CL_ERRORCODE_END() \
	};

#define CL_SYS_ERRORCODE_BEGIN() \
	SYS_ERRORCODE_BEGIN = 1,
#define CL_SYS_ERRORCODE_END() \
	SYS_ERRORCODE_END = CL_FUNCTION_OFFSET_IN_ERRORCODE - 1,

#define CL_FUNCTION_ERRORCODE_BEGIN(Type) \
	Type##_ERRORCODE_BEGIN = FUNCTION_##Type * CL_FUNCTION_OFFSET_IN_ERRORCODE,
#define CL_FUNCTION_ERRORCODE_END(Type) \
	Type##_ERRORCODE_END = ( FUNCTION_##Type + 1 ) * CL_FUNCTION_OFFSET_IN_ERRORCODE - 1,

#define CL_SUB_FUNCTION_ERRORCODE_BEGIN(Type, Sub, offset) \
	Sub##_ERRORCODE_BEGIN = FUNCTION_##Type * CL_FUNCTION_OFFSET_IN_ERRORCODE + offset * CL_SUB_FUNCTION_OFFSET,

#define CL_DEFINE_ERRORCODE(Identify) \
	Identify,


#define CL_FUNCTION_BEGIN() \
	enum { \
		FUNCTION_SYS,
#define CL_FUNCTION_END() \
	};

#define CL_DEFINE_FUNCTION(Identify) \
	FUNCTION_##Identify,

namespace ErrorCode
{
	/**
	 *@brief 功能定义
	 */
	CL_FUNCTION_BEGIN()
		CL_DEFINE_FUNCTION(LOGIN)		//登录验证
		CL_DEFINE_FUNCTION(ENTERGAME)	//进入游戏
		CL_DEFINE_FUNCTION(SCENE)		//场景相关
		CL_DEFINE_FUNCTION(RECORD)		//档案错误码

		//
		CL_DEFINE_FUNCTION(RELAY)		//relay server错误码
        CL_DEFINE_FUNCTION(MATCH)       //匹配相关

		CL_DEFINE_FUNCTION(SKILL)		//技能相关
		CL_DEFINE_FUNCTION(SETTING)		//设置相关
        CL_DEFINE_FUNCTION(DUNGEON)     //地下城相关
		CL_DEFINE_FUNCTION(ITEM)		//道具相关
		CL_DEFINE_FUNCTION(SHOP)		//商店相关
		CL_DEFINE_FUNCTION(MAIL)		//邮件相关
        CL_DEFINE_FUNCTION(TEAM)		//组队相关
		CL_DEFINE_FUNCTION(WARPSTONE)	//次元石相关
		CL_DEFINE_FUNCTION(RETINUE)		//随从相关

		CL_DEFINE_FUNCTION(RECONNECT)	//重连
		CL_DEFINE_FUNCTION(MALL)		//商城

		CL_DEFINE_FUNCTION(PLAYER)		//玩家相关
		CL_DEFINE_FUNCTION(QUICKBUY)	//快速购买
		CL_DEFINE_FUNCTION(TASK)	//任务相关

		CL_DEFINE_FUNCTION(TOWER)		//死亡之塔

		CL_DEFINE_FUNCTION(PK)			//PK相关
		CL_DEFINE_FUNCTION(GUILD)		//公会
		CL_DEFINE_FUNCTION(ITEM_TRANS)	//道具事务
		CL_DEFINE_FUNCTION(RED_PACKET)	//红包
		CL_DEFINE_FUNCTION(BILLING)		//充值
		CL_DEFINE_FUNCTION(AUCTION)		//拍卖行
		CL_DEFINE_FUNCTION(HORN)		//喇叭

		CL_DEFINE_FUNCTION(CHAT)		//聊天

		CL_DEFINE_FUNCTION(PET)			//宠物
		CL_DEFINE_FUNCTION(CUSTOM_SERVICE)	// 客服系统
		CL_DEFINE_FUNCTION(RELATION)		//社交
		CL_DEFINE_FUNCTION(PREMIUM_LEAGUE)	// 赏金联赛
		CL_DEFINE_FUNCTION(ROOM)			// 房间
		CL_DEFINE_FUNCTION(VERIFY)			// 验证服务器
		CL_DEFINE_FUNCTION(SCORE_WAR)		// 积分赛	
		CL_DEFINE_FUNCTION(DIG)				// 挖宝
		CL_DEFINE_FUNCTION(BET_HORSE)		// 赌马
		CL_DEFINE_FUNCTION(SECURITY_LOCK)	// 安全锁
		CL_DEFINE_FUNCTION(ADVENTURE_TEAM)	// 冒险队
		CL_DEFINE_FUNCTION(BLACK_MARKET)	// 黑市商人
		CL_DEFINE_FUNCTION(BATTLE)			// 吃鸡
		CL_DEFINE_FUNCTION(OPERATE)			// 运营活动
		CL_DEFINE_FUNCTION(NEW_TITLE)		// 头衔
		CL_DEFINE_FUNCTION(NEW_SIGN)         //自然月签到
		CL_DEFINE_FUNCTION(TEAM_COPY)		// 团本
		CL_DEFINE_FUNCTION(HIRE)			// 招募
		CL_DEFINE_FUNCTION(CHAMPION)		// 冠军赛
		CL_DEFINE_FUNCTION(LOSTDUNGEON)		// 迷失地牢
		CL_DEFINE_FUNCTION(GOLD_CONSIGNMENT)// 金币寄售
		CL_DEFINE_FUNCTION(ITEM_THING)		// 道具事务
	CL_FUNCTION_END()

	/**
	 *@brief 错误码定义
	 */
	CL_ERRORCODE_BEGIN()
		CL_DEFINE_ERRORCODE(SUCCESS)
		
		//系统错误码
		CL_SYS_ERRORCODE_BEGIN()
		CL_DEFINE_ERRORCODE(SYS_REPEAT_LOGIN)
		CL_DEFINE_ERRORCODE(SYS_FORBIT_LOGIN)
		CL_DEFINE_ERRORCODE(SYS_GM_KICK)
		CL_DEFINE_ERRORCODE(SYS_NOT_OPEN)
		CL_DEFINE_ERRORCODE(SYS_CHEAT_FIRST_FORBIT_LOGIN)
		CL_DEFINE_ERRORCODE(SYS_CHEAT_FOREVER_FORBIT_LOGIN)
		CL_SYS_ERRORCODE_END()

		//登录服错误码
		CL_FUNCTION_ERRORCODE_BEGIN(LOGIN)
		CL_DEFINE_ERRORCODE(LOGIN_SERVER_UNREADY)	//服务器未就绪
		CL_DEFINE_ERRORCODE(LOGIN_UNKNOW_ACCOUNT)	//未知账号，账号名错误
		CL_DEFINE_ERRORCODE(LOGIN_REPEAT)			//重复登录
		CL_DEFINE_ERRORCODE(LOGIN_WRONG_PASSWD)		//密码错
		CL_DEFINE_ERRORCODE(LOGIN_VERIFY_TIMEOUT)	//验证超时
		CL_DEFINE_ERRORCODE(LOGIN_SERVER_BUSY)		//服务器繁忙
        CL_DEFINE_ERRORCODE(LOGIN_ERROR_VERSION)    //版本号错误
		CL_DEFINE_ERRORCODE(LOGIN_FORBID_LOGIN)     //封号
		CL_DEFINE_ERRORCODE(LOGIN_DB_ERROR)			//数据库错误
		CL_DEFINE_ERRORCODE(LOGIN_WAIT)				//排队中
		CL_DEFINE_ERRORCODE(LOGIN_BUSY)				//服务器禁止登录
		CL_DEFINE_ERRORCODE(LOGIN_ANTIADDICT_NIGHT) //防沉迷夜晚提示
		CL_DEFINE_ERRORCODE(LOGIN_ANTIADDICT_TIPS_COMMON) //防沉迷提示一
		CL_DEFINE_ERRORCODE(LOGIN_ANTIADDICT_TIPS_HOLIDAY)//防沉迷提示二
		CL_DEFINE_ERRORCODE(LOGIN_GM_DATA_NOT_LOADED) //gm数据未加载完毕
		CL_DEFINE_ERRORCODE(LOGIN_ACT_VALUE_NOT_ENOUGH)// 活跃度不足
		CL_DEFINE_ERRORCODE(LOGIN_ANTIADDICT_TOURIST_LOGIN)//游客登录防沉迷
		CL_DEFINE_ERRORCODE(LOGIN_ANTIADDICT_TOURIST_ONLINE)//游客在线防沉迷
		CL_DEFINE_ERRORCODE(LOGIN_ANTIADDICT_TOURIST_TIME_TIP)//游客沉迷时间提示
		CL_DEFINE_ERRORCODE(LOGIN_ANTIADDICT_NOADULT_TIME_TIP)//未成年沉迷时间提示

		CL_FUNCTION_ERRORCODE_END(LOGIN)

		//进入游戏流程错误码
		CL_FUNCTION_ERRORCODE_BEGIN(ENTERGAME)
		CL_DEFINE_ERRORCODE(ENTERGAME_UNVALID_ROLEINFO)		//角色信息不合法
		CL_DEFINE_ERRORCODE(ENTERGAME_SERVER_BUSY)			//服务器繁忙
		CL_DEFINE_ERRORCODE(ENTERGAME_TOOMANY_ROLES)		//太多角色
		CL_DEFINE_ERRORCODE(ENTERGAME_DUPLICATE_NAME)		//重复名
		CL_DEFINE_ERRORCODE(ENTERGAME_NOROLE)				//删除角色或进入游戏时提示
		CL_DEFINE_ERRORCODE(ENTERGAME_SCENE_UNREADY)		//场景未就绪
		CL_DEFINE_ERRORCODE(ENTERGAME_INIT_FAILED)			//角色初始化失败
		CL_DEFINE_ERRORCODE(ENTERGAME_REPEAT)				//重复
		CL_DEFINE_ERRORCODE(ENTERGAME_UNVALID_NAME)			//角色名不合法
		CL_DEFINE_ERRORCODE(ENTERGAME_NO_CREATEROLE)		//不允许建号
		CL_DEFINE_ERRORCODE(ENTERGAME_NEED_LEVEL_20)		//需要有角色达到20级
		CL_DEFINE_ERRORCODE(ENTERGAME_NEED_LEVEL_40)		//需要有角色达到40级
		CL_DEFINE_ERRORCODE(ENTERGAME_TODAY_TOOMANY_ROLE)	//超过今日创建角色最大数
		CL_DEFINE_ERRORCODE(ENTERGAME_RECOVER_ROLE_UNEXIST)	//请求恢复的角色不存在
		CL_DEFINE_ERRORCODE(ENTERGAME_RECOVER_ROLE_DELETED)	//请求恢复的角色已经删除了（超过保存时间）
		CL_DEFINE_ERRORCODE(ENTERGAME_RECOVER_ROLE_NOT_DELETE)	//请求恢复的角色并没有被删除
		CL_DEFINE_ERRORCODE(ENTERGAME_DELETE_ROLE_DELETED)	//请求删除的角色已经被删除了
		CL_DEFINE_ERRORCODE(ENTERGAME_DELETE_ROLE_UNEXIST)	//请求删除的角色不存在
		CL_DEFINE_ERRORCODE(ENTERGAME_DELETE_ROLE_MAX_NUM)	//当前正在删除的角色达到上限
		CL_DEFINE_ERRORCODE(ENTERGAME_DELETE_ROLE_LIMIT)	//请求删除的角色受限（时间限制）
		CL_DEFINE_ERRORCODE(ENTERGAME_RECOVER_ROLE_LIMIT)	//请求恢复的角色受限（时间限制）
		CL_DEFINE_ERRORCODE(ENTERGAME_ROLE_FIELD_REACN_UPPER_LIMIT) //角色栏位达到上限
		CL_DEFINE_ERRORCODE(ENTERGAME_ROLE_FIELD_NOT_ALL_USED) //角色栏位未全部使用
		CL_DEFINE_ERRORCODE(ENTERGAME_EXTENSIBLE_ROLE_FIELD_UNLOCK_FAILED) //可扩展角色栏位解锁失败
		CL_DEFINE_ERRORCODE(ENTERGAME_PREFERENCES_ROLE_REACN_UPPER_LIMIT) //偏好角色数量达到上限
		CL_FUNCTION_ERRORCODE_END(ENTERGAME)

		//重连错误码
		CL_FUNCTION_ERRORCODE_BEGIN(RECONNECT)
		CL_DEFINE_ERRORCODE(RECONNECT_PLAYER_DELETED)		//角色数据已经删除
		CL_DEFINE_ERRORCODE(RECONNECT_INVALID_SEQUENCE)		//无效的sequence
		CL_DEFINE_ERRORCODE(RECONNECT_PLAYER_ONLINE)		//账号还在线
		CL_DEFINE_ERRORCODE(RECONNECT_NO_CONNECTION)		//错误的连接
		CL_FUNCTION_ERRORCODE_END(RECONNECT)

		//场景相关错误码
		CL_FUNCTION_ERRORCODE_BEGIN(SCENE)
		CL_DEFINE_ERRORCODE(SCENE_DUPLICATE)				//重复的场景
		CL_DEFINE_ERRORCODE(SCENE_NOOWNER)					//建动态场景时下线
		
		CL_DEFINE_ERRORCODE(SCENE_CHANGE_ERROR)				//切换场景出错（异常情况）
		CL_DEFINE_ERRORCODE(SCENE_UNEXIST)				//场景不存在
		CL_DEFINE_ERRORCODE(SCENE_ALREADY_IN_THIS_SCENE)	//已经在该场景
		CL_DEFINE_ERRORCODE(SCENE_LEVEL_LIMIT)				//等级限制

		CL_FUNCTION_ERRORCODE_END(SCENE)

		//档案服错误码
		CL_FUNCTION_ERRORCODE_BEGIN(RECORD)
		CL_DEFINE_ERRORCODE(RECORD_ERROR)					//数据库错误
		CL_DEFINE_ERRORCODE(RECORD_DUPLICATE_NAME)			//重复名
		CL_DEFINE_ERRORCODE(RECORD_NO_NAMECOLUMN)			//没有名字列
		CL_DEFINE_ERRORCODE(RECORD_TIMEOUT)
		CL_FUNCTION_ERRORCODE_END(RECORD)

		//relay server
		CL_FUNCTION_ERRORCODE_BEGIN(RELAY)
		CL_DEFINE_ERRORCODE(RELAY_LOGIN_SYSTEMERROR)		//系统错误
		CL_DEFINE_ERRORCODE(RELAY_LOGIN_INVALIDSESSION)		//无效的game session
		CL_DEFINE_ERRORCODE(RELAY_LOGIN_INVALIDFIGHTER)		//无效的参战者

		CL_DEFINE_ERRORCODE(RELAY_RECONNECT_SYSTEMERROR)	//系统错误
		CL_DEFINE_ERRORCODE(RELAY_RECONNECT_PLAYER_ONLINE)	//玩家还在线上
		CL_DEFINE_ERRORCODE(RELAY_RECONNECT_INVALIDSESSION)	//无效的game session
		CL_DEFINE_ERRORCODE(RELAY_RECONNECT_INVALIDFIGHTER)	//无效的参战者

		// 观战
		CL_DEFINE_ERRORCODE(RELAY_OBSERVE_RACE_NOT_EXIST)	// 比赛不存在
		CL_DEFINE_ERRORCODE(RELAY_OBSERVE_REPEAT_PLAYER)	// 重复的玩家，已经在观战了
		CL_DEFINE_ERRORCODE(RELAY_OBSERVE_RACE_CANNOT_OBSERVE)	// 不能观战

		CL_FUNCTION_ERRORCODE_END(RELAY)

        CL_FUNCTION_ERRORCODE_BEGIN(MATCH)
        CL_DEFINE_ERRORCODE(MATCH_START_SYSTEMERROR)        //系统错误
        CL_DEFINE_ERRORCODE(MATCH_START_REPEAT)             //已经在匹配中了
        CL_DEFINE_ERRORCODE(MATCH_TIMEOUT)                  //匹配失败，超时
		CL_DEFINE_ERRORCODE(MATCH_START_NOT_IN_PK_PARPARE)	//不在PK准备区中
		CL_DEFINE_ERRORCODE(MATCH_START_IN_TEAM)			//组队状态不能匹配
		CL_DEFINE_ERRORCODE(MATCH_START_WUDAO_NOT_JOIN)		//未加入武道大会
		CL_DEFINE_ERRORCODE(MATCH_START_WUDAO_COMPLETE)		//武道大会已经完成

        CL_DEFINE_ERRORCODE(MATCH_CANCLE_NOT_MATCHING)      //不在匹配列表中
        CL_DEFINE_ERRORCODE(MATCH_CANCLE_RACING)            //玩家已经在游戏中了
		CL_DEFINE_ERRORCODE(MATCH_NOT_SET_EQUAL_SKILL)      //尚未设置公平竞技场技能
		CL_DEFINE_ERRORCODE(MATCH_NOT_BEGIN)                //尚未开始
        CL_FUNCTION_ERRORCODE_END(MATCH)

		//Skill noted by hch
		CL_FUNCTION_ERRORCODE_BEGIN(SKILL)
		CL_DEFINE_ERRORCODE(SKILL_ERROR)						//ERROR
		CL_DEFINE_ERRORCODE(SKILL_SAVE_DB_ERROR)				//保存到数据库失败
		CL_DEFINE_ERRORCODE(SKILL_NOT_FOUNT)					//没有这个技能
		CL_DEFINE_ERRORCODE(SKILL_TYPE_ERROR)					//错误的技能类型
		CL_DEFINE_ERRORCODE(SKILL_SP_NOT_ENOUGH)				//SP不够
		CL_DEFINE_ERRORCODE(SKILL_SP_REMOVE_ERROR)				//移除SP失败
		CL_DEFINE_ERRORCODE(SKILL_MAX_SKILL_LEVEL)				//超过最大等级
		CL_DEFINE_ERRORCODE(SKILL_OCCU_ERROR)					//职业不合法
		CL_DEFINE_ERRORCODE(SKILL_PLAYER_LEVEL)					//检查玩家等级
		CL_DEFINE_ERRORCODE(SKILL_NEED_SKILL_ERROR)				//前置技能错误

		CL_DEFINE_ERRORCODE(SKILL_NEED_ITEM_ERROR)				//没有需要的物品或BUFF
		CL_DEFINE_ERRORCODE(SKILL_NEXT_SKILL_ERROR)				//后置技能错误
		CL_DEFINE_ERRORCODE(SKILL_MIN_SKILL_LEVEL)				//超过最小等级
		CL_DEFINE_ERRORCODE(SKILL_AWAKEN_ERROR)					//没有觉醒
		CL_FUNCTION_ERRORCODE_END(SKILL)

		//Setting noted by hch
		CL_FUNCTION_ERRORCODE_BEGIN(SETTING)
		CL_DEFINE_ERRORCODE(SETTING_ERROR)						//ERROR
		CL_DEFINE_ERRORCODE(SETTING_INDEX_ERROR)				//索引错误
		CL_DEFINE_ERRORCODE(SETTING_SLOT_ERROR)					//槽位索引错误
		CL_DEFINE_ERRORCODE(SETTING_SKILL_REPEAT)				//技能重复
		CL_DEFINE_ERRORCODE(SETTING_SKILL_ERROR)				//技能不存在
		CL_DEFINE_ERRORCODE(SETTING_SKILL_PRE_OCCU_ERROR)		//预转职技能无法移动
		CL_DEFINE_ERRORCODE(SETTING_CHANGENAME_LEN_ERROR)		//角色改名长度错误
		CL_DEFINE_ERRORCODE(SETTING_CHANGENAME_FORBID_ERROR)	//角色改名有屏蔽字
		CL_DEFINE_ERRORCODE(SETTING_CHANGENAME_REPEAT_ERROR)	//角色改名有屏蔽字
		CL_DEFINE_ERRORCODE(SETTING_CHANGENAME_UNCHANGE_ERROR)	//角色改名没变化
		CL_DEFINE_ERRORCODE(SETTING_CHANGENAME_CARD_NOT_ENOUGH_ERROR)	//角色改名卡不够
		CL_DEFINE_ERRORCODE(SETTING_CHANGENAME_BUYCARD_NOT_ENOUGH_MONEY)	//角色改名买改名卡钱不够
		CL_DEFINE_ERRORCODE(SETTING_CHANGENAME_FAIL)			//角色改名失败
		CL_DEFINE_ERRORCODE(SETTING_TARGET_SHILED_INVATE)		// 目标屏蔽了邀请
		CL_DEFINE_ERRORCODE(SETTING_NAME_LEN_ERROR)				//命名长度错误
		CL_DEFINE_ERRORCODE(SETTING_NAME_FORBID_ERROR)			//命名有屏蔽字
		CL_DEFINE_ERRORCODE(SETTING_NAME_REPEAT_ERROR)			//命名重复

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(SETTING, WEAPON_SETTING, 2)
		CL_DEFINE_ERRORCODE(WEAPON_SETTING_NOT_FOUNT)			//没有找到武器
		CL_DEFINE_ERRORCODE(WEAPON_SETTING_INDEX_ERROR)			//索引错误


		CL_FUNCTION_ERRORCODE_END(SETTING)

        //地下城相关
        CL_FUNCTION_ERRORCODE_BEGIN(DUNGEON)

        // 开始地下城战斗
        CL_DEFINE_ERRORCODE(DUNGEON_START_CREATE_RACE_FAILED)	    // 创建比赛失败
        CL_DEFINE_ERRORCODE(DUNGEON_START_DUNGEON_NOT_EXIST)        // 地下城不存在
        CL_DEFINE_ERRORCODE(DUNGEON_START_LEVEL_LIMIT)              // 未达到等级要求
        CL_DEFINE_ERRORCODE(DUNGEON_START_NO_FATIGUE)               // 没有疲劳了
        CL_DEFINE_ERRORCODE(DUNGEON_START_CONDITION)                // 不满足进入条件（前置任务，前置关卡等）
        CL_DEFINE_ERRORCODE(DUNGEON_START_HARD_NOT_OPEN)            // 难度未开放
        CL_DEFINE_ERRORCODE(DUNGEON_START_NOT_IN_ENTRY_SCENE)       // 不在选择关卡的场景
        CL_DEFINE_ERRORCODE(DUNGEON_START_RACE_FAILED)	            // 开始比赛失败
        CL_DEFINE_ERRORCODE(DUNGEON_START_NO_TICKET)	            // 门票不足
        CL_DEFINE_ERRORCODE(DUNGEON_START_NO_HELL_MODE)             // 没有深渊模式
        CL_DEFINE_ERRORCODE(DUNGEON_START_NO_HELL_TICKET)           // 没有足够的深渊票
		CL_DEFINE_ERRORCODE(DUNGEON_START_TEAM_MEMBER_OFFLINE)		// 队伍成员不在线
		CL_DEFINE_ERRORCODE(DUNGEON_START_BAG_FULL)					// 背包空余位置不足
		CL_DEFINE_ERRORCODE(DUNGEON_START_NOT_OPEN_TIME)			// 不在开放时间
		CL_DEFINE_ERRORCODE(DUNGEON_START_NO_TIMES)					// 次数用完

        // 进入新区域
        CL_DEFINE_ERRORCODE(DUNGEON_ENTER_AREA_SYSTEM_ERROR)        // 系统错误
        CL_DEFINE_ERRORCODE(DUNGEON_ENTER_AREA_NOT_IN_DUNGEON)      // 已经离开地下城了
        CL_DEFINE_ERRORCODE(DUNGEON_ENTER_AREA_REPEAT)              // 重复进入
        CL_DEFINE_ERRORCODE(DUNGEON_ENTER_AREA_NOT_EXIST)           // 进入不存在的区域

		// 复活相关
		CL_DEFINE_ERRORCODE(DUNGEON_REVIVE_PLAYER_NOT_EXIST)        // 复活的目标不存在
		CL_DEFINE_ERRORCODE(DUNGEON_REVIVE_REPEAT)					// 重复复活
		CL_DEFINE_ERRORCODE(DUNGEON_REVIVE_NOT_ENOUGH_REVIVE_COIN)	// 没有足够的复活币

		// 关卡匹配
		CL_DEFINE_ERRORCODE(DUNGEON_MATCH_START_FAILED)				// 开始关卡匹配失败

		// 组队地下城
		CL_DEFINE_ERRORCODE(DUNGEON_TEAM_START_VOTE_REPEAT)			// 重复开始地下城
		CL_DEFINE_ERRORCODE(DUNGEON_TEAM_TARGET_MUST_SINGLE)		// 地下城不能组队开始
		CL_DEFINE_ERRORCODE(DUNGEON_TEAM_TOO_MANY_MEMBER)			// 超过地下城最大人数
		CL_DEFINE_ERRORCODE(DUNGEON_TEAM_NOT_ENOUGH_MEMBER)			// 人数不足，无法开始地下城
		CL_DEFINE_ERRORCODE(DUNGEON_TEAM_WAIT_OTHER_VOTE)			// 等待其他人投票

		// 地下城购买次数
		CL_DEFINE_ERRORCODE(DUNGEON_TIMES_CANT_BUY)					// 无法购买次数
		CL_DEFINE_ERRORCODE(DUNGEON_TIMES_NO_REMAIN_TIMES)			// 无法购买次数，剩余次数不足
		CL_DEFINE_ERRORCODE(DUNGEON_TIMES_NO_ENOUGH_MONEY)			// 无法购买次数，钱不够

		CL_DEFINE_ERRORCODE(DUNGEON_START_CONDITION_WEEK)           // 不满足进入周常深渊前置关卡条件（前置关卡任务）
		CL_DEFINE_ERRORCODE(DUNGEON_START_IN_TEAM_COPY)	            // 在团本中不允许打地下城

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(DUNGEON, DUNGEON_TEAM, 1)
		CL_DEFINE_ERRORCODE(DUNGEON_TEAM_START_RACE_FAILED)			// 开始比赛失败，这种情况下不需要提示
		CL_DEFINE_ERRORCODE(DUNGEON_START_MONSTER_NOT_EXIST)		// 怪物不存在
		CL_DEFINE_ERRORCODE(DUNGEON_START_MUST_TEAM)				// 必须组队
		CL_DEFINE_ERRORCODE(DUNGEON_START_MONSTER_BUSY)				// 怪物正忙，当前挑战的队伍达到上限
		CL_DEFINE_ERRORCODE(DUNGEON_START_MUST_SINGLE)				// 只有单人情况下能进

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(DUNGEON, DUNGEON_REVIVE, 2)
		CL_DEFINE_ERRORCODE(DUNGEON_REVIVE_NO_REMAIN_TIMES)			// 复活次数已用完
		CL_DEFINE_ERRORCODE(DUNGEON_REVIVE_NO_TEAM_REMAIN_TIMES)	// 队伍复活次数已用完

        CL_FUNCTION_ERRORCODE_END(DUNGEON)

		//item errcode
		CL_FUNCTION_ERRORCODE_BEGIN(ITEM)
		CL_DEFINE_ERRORCODE(ITEM_DATA_INVALID)					// 数据非法,包括各种相关空指正判断
		CL_DEFINE_ERRORCODE(ITEM_NO_REASON)						// 没有操作理由
		CL_DEFINE_ERRORCODE(ITEM_NUM_INVALID)					// item数量非法
		CL_DEFINE_ERRORCODE(ITEM_ADD_PACK_FULL)					// 添加item背包满
		CL_DEFINE_ERRORCODE(ITEM_MONEY_ADD_FULL)				// 金钱添加达到上限
		CL_DEFINE_ERRORCODE(ITEM_USE_FAIL)						// 使用道具失败
		CL_DEFINE_ERRORCODE(ITEM_CAN_NOT_EQUIP)					// 不能装备
		CL_DEFINE_ERRORCODE(ITEM_LOCKED)						// 装备加锁
		CL_DEFINE_ERRORCODE(ITEM_PACK_INVALID)					// 装备所处的包裹错误
		CL_DEFINE_ERRORCODE(ITEM_PACKSIZE_MAX)					// 背包格子达到上限
		CL_DEFINE_ERRORCODE(ITEM_TYPE_INVALID)					// 道具类别错误
		CL_DEFINE_ERRORCODE(ITEM_DECOMPOSE_FAIL)				// 道具分解失败
		CL_DEFINE_ERRORCODE(ITEM_STRENTH_LV_INVALID)			// 装备强化等级错误
		CL_DEFINE_ERRORCODE(ITEM_NOT_ENOUGH_GOLD)				// 金币不够
		CL_DEFINE_ERRORCODE(ITEM_NOT_ENOUGH_MAT)				// 材料不够
		CL_DEFINE_ERRORCODE(ITEM_STRENTH_FAIL)					// 装备强化失败无惩罚
		CL_DEFINE_ERRORCODE(ITEM_STRENTH_FAIL_MINUS)			// 装备强化失败扣等级
		CL_DEFINE_ERRORCODE(ITEM_STRENTH_FAIL_ZERO)				// 装备强化失败等级归零
		CL_DEFINE_ERRORCODE(ITEM_STRENTH_FAIL_BROKE)			// 装备强化失败破碎
		CL_DEFINE_ERRORCODE(ITEM_PUSH_STORAGE_FULL)				// 存仓库空间满了
		CL_DEFINE_ERRORCODE(ITEM_STORAGE_NUM_ERR)				// 存取仓库数量错误
		CL_DEFINE_ERRORCODE(ITEM_EQUIP_OCCU)					// 装备职业不符
		CL_DEFINE_ERRORCODE(ITEM_EQUIP_LV)						// 装备等级不符
		CL_DEFINE_ERRORCODE(ITEM_STRENTH_FAIL_TWO)				// 装备强化失败扣2级
		CL_DEFINE_ERRORCODE(ITEM_STRENTH_FAIL_THREE)			// 装备强化失败扣2级
		CL_DEFINE_ERRORCODE(ITEM_STRENTH_FAIL_FOUR)				// 装备强化失败扣4级
		CL_DEFINE_ERRORCODE(ITEM_NOT_ENOUGH_POINT)				// 点券不够
		CL_DEFINE_ERRORCODE(ITEM_STRENTH_FAIL_TITLE)			// 强化类型错误(称号)	added by huchenhui 2016.06.30
		CL_DEFINE_ERRORCODE(ITEM_CNA_NOT_DECOMPOSE)				// 装备不能分解
		CL_DEFINE_ERRORCODE(ITEM_USE_CD)						// 道具使用CD中
		CL_DEFINE_ERRORCODE(ITEM_SEAL_COUNT_MAX)				// 封装次数达到上限
		CL_DEFINE_ERRORCODE(ITEM_ALREADY_SEAL)					// 装备已经是封装了
		CL_DEFINE_ERRORCODE(ITEM_SEAL_QUALITY_ERR)				// 装备封装品质不符
		CL_DEFINE_ERRORCODE(ITEM_NOT_ENOUGH_WARRIOR_SOUL)		// 勇者之魂不够
		CL_DEFINE_ERRORCODE(ITEM_NOT_ENOUGH_PKCOIN)				// 决斗币不够
		CL_DEFINE_ERRORCODE(ITEM_ADDMAGIC_PART_ERR)				// 附魔部位错误
		CL_DEFINE_ERRORCODE(ITEM_MAGCARD_COMP_DIF_COLOR)		// 附魔卡合成品质不同
		CL_DEFINE_ERRORCODE(ITEM_ONEKEY_DECOMPOSE_LV_NOT_ENOUGH)		// 一键分解所需等级不够
		CL_DEFINE_ERRORCODE(ITEM_OPEN_JAR_DAYCOUNT)				// 开罐子日金钱次数已满
		CL_DEFINE_ERRORCODE(ITEM_NOT_SELL)						// 不能出售
		CL_DEFINE_ERRORCODE(ITEM_SELL_ITEM_NOT_EXIST)			// 出售物品不存在
		CL_DEFINE_ERRORCODE(ITEM_NOT_ENOUGH_GUILD_CONTRI)		// 公会贡献不够
		CL_DEFINE_ERRORCODE(ITEM_USE_BUFFALREADYEXIST)			// 使用道具buff已经存在
		CL_DEFINE_ERRORCODE(ITEM_NOT_ENOUGH_MONEY)				// 货币不足
		CL_DEFINE_ERRORCODE(ITEM_STRTICKET_LV_ERR)				// 强化券等级错误
		CL_DEFINE_ERRORCODE(ITEM_STRTICKET_REDUCE_ERR)			// 强化券扣除失败
		CL_DEFINE_ERRORCODE(ITEM_DAYUSENUM)						// 道具日使用次数完了
		CL_DEFINE_ERRORCODE(ITEM_SPECIAL_STRENTH_FAIL)			// 强化券强化失败
		CL_DEFINE_ERRORCODE(ITEM_NOT_CHANGE_OCCU)					// 未转职
		CL_DEFINE_ERRORCODE(ITEM_AUTO_SETPOTION_LV_INVALID)					// 自动配置药品等级不够
		CL_DEFINE_ERRORCODE(ITEM_ERRCODE_51)					// errcode51
		CL_DEFINE_ERRORCODE(ITEM_ERRCODE_52)					// errcode52
		CL_DEFINE_ERRORCODE(ITEM_ERRCODE_53)					// errcode53
		CL_DEFINE_ERRORCODE(ITEM_CAN_NOT_USE_IN_DUNGEON)		// 地下城不能使用该道具
		CL_DEFINE_ERRORCODE(ITEM_CAN_NOT_USE_IN_TOWN)			// 城镇内不能使用该道具
		CL_DEFINE_ERRORCODE(ITEM_ABANDON)						// 道具废弃
		CL_DEFINE_ERRORCODE(ITEM_EQUIPQL_FULL)					// 装备品级满了
		CL_DEFINE_ERRORCODE(ITEM_SET_POTION_ERROR)				// 设置药品位置错误
		CL_DEFINE_ERRORCODE(ITEM_LIMIT_BUY)						// 道具限购
		CL_DEFINE_ERRORCODE(ITEM_USE_LEVEL_LIMIT)						// 道具使用等级不足
		CL_DEFINE_ERRORCODE(FASHION_CMPS_PART_ERR)						// 时装合成部位错误
		CL_DEFINE_ERRORCODE(FASHION_CMPS_TIME_FS)				// 时装合成里有时限时装
		CL_DEFINE_ERRORCODE(FASHION_CMPS_NOT_OPEN)				// 时装合成没有开放
		CL_DEFINE_ERRORCODE(ITEM_MUST_HAS_ONE_POS)				// 每个背包都得有一个格子
		CL_DEFINE_ERRORCODE(ITEM_WEAPON_BAR_NOT_OPERATION)		// 武器已经配置在武器栏内,无法操作
		CL_DEFINE_ERRORCODE(ITEM_SOLD_OUT)						// 已售完
		CL_DEFINE_ERRORCODE(ITEM_COPIES_NOT_ENOUGH)				// 份额不足
		CL_DEFINE_ERRORCODE(ITEM_EQUIPTSF_COLOR)				// 装备转移 装备品质不够
		CL_DEFINE_ERRORCODE(ITEM_EQUIPRECO_BEYOND)				// 超出装备回收次数
		CL_DEFINE_ERRORCODE(ITEM_EQUIPRECO_REDEEM)				// 装备回收赎回积分不够
		CL_DEFINE_ERRORCODE(ITEM_EQUIPPACK_FULL)				// 装备背包空间满了
		CL_DEFINE_ERRORCODE(ITEM_EQUIPRECO_UPSCFAIL)			// 装备回收积分提升失败
		CL_DEFINE_ERRORCODE(ITEM_OFF_SALE)						// 商品下架
		CL_DEFINE_ERRORCODE(ITEM_EQUIPRECO_UPSCMONY)			// 装备回收积分提升货币不够
		CL_DEFINE_ERRORCODE(ITEM_EQUIPRECO_UPSCMAX)			// 装备回收积分提升积分已经最大
		CL_DEFINE_ERRORCODE(ITEM_EQUIPRECO_EMPTY)           //提交装备数量不能为0
		CL_DEFINE_ERRORCODE(ITEM_EQUIPRECO_JARCANNOTOPEN)    //装备回收积分罐子不能打开
		CL_DEFINE_ERRORCODE(ITEM_EQUIPRECO_JAROPENED)           //装备回收积分罐子已打开过
		CL_DEFINE_ERRORCODE(ITEM_GAMBLE_ALL_SOLD_OUT)			// 夺宝商品全部售完
		CL_DEFINE_ERRORCODE(ITEM_CONS_JARGIFT_ITEM_INSUFFIC)	// 消耗道具类魔罐礼包道具不足
		CL_DEFINE_ERRORCODE(ITEM_NOT_ENOUGH_TEACHVALUE)		    // 良师值不足
		CL_DEFINE_ERRORCODE(ITEM_ROLEBIND_EQ_CANT_PUTSTORE)		// 角色绑定装备未镶嵌转移石不能放入仓库
		CL_DEFINE_ERRORCODE(ITEM_TITLE_NOTSEAL_CANT_PUTSTORE)   // 未封装称号不能放入仓库
		CL_DEFINE_ERRORCODE(ITEM_FASHCOM_CHANGEACTIV_NOTOPEN)   // 百变换装节时装合成失败，活动未开启
		CL_DEFINE_ERRORCODE(ITEM_FASHCOM_CHANGEACTIV_TICKETNO)   // 百变换装节时装合成失败，换装卷不足
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_HOLE_NOTFINND)         // 装备未找到镶嵌孔
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_EQ_PBTYPE_HAVEED)      // 宝珠镶嵌,装备已经镶嵌改类型宝珠
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_HOLE_NOHAVEED)           // 宝珠摘除失败,孔里没有宝珠
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_MATERIAL_NOENOUGH)           // 宝珠摘除失败,材料不足
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_EXTRIPE_FAIL)           // 宝珠摘除失败
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_MOUNTFAIL_TYPEERR)      // 宝珠镶嵌失败，类型不对
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_UPLEVFAIL_MATER_INSUFF)   // 宝珠升级失败，消耗材料不足
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_OPEAR_FAIL_MOUNTEDBEAD)   // 无法对镶嵌了宝珠的装备进行该操作
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_PUSHFAIL_MOUNTEDBEAD)   // 无法放入镶嵌了宝珠的装备
		CL_DEFINE_ERRORCODE(ITEM_IN_LEASING)						//租赁物品,操作非法
		CL_DEFINE_ERRORCODE(ITEM_USE_ADVENTURE_TEAM_RENAME_FAILED)	// 使用冒险队改名卡失败
		CL_DEFINE_ERRORCODE(ITEM_USE_EXTENSIBLE_ROLE_FIELD_UNLOCK_FAILED) // 使用角色栏位扩展卡失败
		CL_DEFINE_ERRORCODE(ITEM_IN_AUCTIONCOOL_OPFAIL)			//拍卖行交易冷却中,操作非法
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_EXTRIPE_CNT_NOT_ENOUGH)	//宝珠摘取次数不足
		CL_DEFINE_ERRORCODE(ITEM_CHECKITEM_FAIL)			//道具检查失败
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_REPLACE_CNT_NOT_ENOUGH)	//宝珠置换次数不足
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_REPLACE_ITEM_NOT_ENOUGH)  // 宝珠置换失败,金币不足
		CL_DEFINE_ERRORCODE(ITEM_PREABEAD_REPLACE_FAILED)  // 宝珠置换失败
		CL_DEFINE_ERRORCODE(ITEM_ARTIFACT_JAR_ACTIVITY_CLOSE) // 神器罐子活动关闭
		CL_DEFINE_ERRORCODE(ITEM_ARTIFACT_JAR_DISCOUNT_EXTRACT_FAILE) // 神器罐子折扣抽取失败
		CL_DEFINE_ERRORCODE(ITEM_UPLEVEL_ALREADY_MAX)					// 已经到最大等级
		CL_DEFINE_ERRORCODE(ITEM_FASH_CMPS_FAIL_ITEMLOCK)			// 上锁的时装不能用来合成时装
		CL_DEFINE_ERRORCODE(ITEM_STR_TICKET_LEVEL_LIMIT)			// 强化券等级不符
		CL_DEFINE_ERRORCODE(ITEM_MOUNT_TITLE_BEAD_FAIL)			    // 只有角色绑定的称号才能镶嵌宝珠
		CL_DEFINE_ERRORCODE(ITEM_FASHION_LOCK_FORBID_OP)	   //时装锁禁止操作
		CL_DEFINE_ERRORCODE(ITEM_MAGIC_UP_FAIL)				  //附魔卡升级失败,概率上失败
		CL_DEFINE_ERRORCODE(ITEM_MAGIC_CANNOT_UP)			  //附魔卡不能升级
		CL_DEFINE_ERRORCODE(ITEM_MAGIC_UP_FAIL_MAXLEV)		  //附魔卡不能升级失败,已满级
		CL_DEFINE_ERRORCODE(ITEM_MAGIC_UP_FAIL_MATERCARD_TYPE) //附魔卡不能升级失败,副卡类型不对
		CL_DEFINE_ERRORCODE(ITEM_MAGIC_UP_FAIL_MATERCARD_NUM) //附魔卡不能升级失败,副卡数量不够
		CL_DEFINE_ERRORCODE(ITEM_MAGIC_UP_FAIL_MONEY)         //附魔卡不能升级失败,货币数量不够
		CL_DEFINE_ERRORCODE(ITEM_MAGIC_COMP_ONEKEY_FAIL_NOITEMS) //附魔卡一键合成失败,道具不足        
		CL_DEFINE_ERRORCODE(ITEM_ENHANCE_UPGRADE_INVALID_TYPE) //装备增幅失败,不是可增幅的装备类型
		CL_DEFINE_ERRORCODE(ITEM_BOX_NOT_EXIST)			//宝箱已消失，不存在
		CL_DEFINE_ERRORCODE(ITEM_PROTECT_NOT_EXIST)			//保护券不存在
		CL_DEFINE_ERRORCODE(ITEM_FROZEN_CURRENCY_NOT_ENOUGH)	 //冻结资产不够
		CL_DEFINE_ERRORCODE(ITEM_PROHIBIT_OPERATE)	 //道具不允许改操作
		CL_DEFINE_ERRORCODE(ITEM_USELIMIT)						// 道具使用次数完了
		CL_DEFINE_ERRORCODE(ITEM_INVALID_INDEX)		//错误的位置
		CL_DEFINE_ERRORCODE(ITEM_INSCIPTION_MOUNT_CANT_PUTSTORE)   // 镶嵌铭文的装备不能放入仓库
		CL_DEFINE_ERRORCODE(ITEM_NOT_EXIST)		//该道具不存在
		CL_DEFINE_ERRORCODE(ITEM_INSCIPTION_DESTROY_FAIL)		//铭文碎裂失败
		CL_DEFINE_ERRORCODE(ITEM_HUOMONV)		//火魔女欧克勒亚即将复活，请迅速击退冰魔女
		CL_DEFINE_ERRORCODE(ITEM_BINMONV)		//冰魔女明塔即将复活，请迅速击退火魔女
		CL_DEFINE_ERRORCODE(ITEM_PRESENT_FAIL)		//道具赠送失败
		CL_DEFINE_ERRORCODE(ITEM_PRESENT_FAIL_UPLIMIT)		//道具赠送失败,对方接受赠送达到上限
		CL_DEFINE_ERRORCODE(ITEM_PRESENT_FAIL_UPLIMIT_SINGLE)	//道具赠送失败,我赠送对方赠送数量达到上限
		CL_DEFINE_ERRORCODE(ITEM_IILEG_OPER_IN_SCHEME)	//非法操作,装备在方案中
		CL_DEFINE_ERRORCODE(ITEM_CHANGE_SCHEME_FAIL_PACK_INSUFF)	//换装备方案失败，背包格子不够
		CL_DEFINE_ERRORCODE(ITEM_CHANGE_SCHEME_FAIL_FREQ)	//换装备方案失败，操作频繁
		CL_DEFINE_ERRORCODE(ITEM_HONOR_LVL_HIGH)			// 荣誉等级过高
		CL_DEFINE_ERRORCODE(ITEM_TEAM_COPY_CNT_ENOUGH)		// 次数已满，无法使用
		CL_DEFINE_ERRORCODE(ITEM_WEEK_REPEAT_USE)			// 本周重复使用
		CL_DEFINE_ERRORCODE(ITEM_ALREADY_IN_STORAGE)		// 该道具已经在仓库里
		CL_DEFINE_ERRORCODE(ITEM_WEEK6USENUM)						// 道具周使用次数完了
		CL_FUNCTION_ERRORCODE_END(ITEM)

		//shop errcode
		CL_FUNCTION_ERRORCODE_BEGIN(SHOP)
		CL_DEFINE_ERRORCODE(SHOP_QUERY_ERR)						// 商店查询错误
		CL_DEFINE_ERRORCODE(SHOP_REFRESH_ERR)					// 商店刷新错误
		CL_DEFINE_ERRORCODE(SHOP_BUY_ERR)						// 商店购买错误
		CL_DEFINE_ERRORCODE(SHOP_BUY_NOT_ENOUGH_GOLD)			// 商店购买金币不足
		CL_DEFINE_ERRORCODE(SHOP_BUY_NOT_ENOUGH_POINT)			// 商店购买点券不足
		CL_DEFINE_ERRORCODE(SHOP_BUY_NOT_ENOUGH_ITEM)			// 商店购买道具不足
		CL_DEFINE_ERRORCODE(SHOP_BUY_NOT_ENOUGH_PACKSIZE)		// 商店购买背包空间不足
		CL_DEFINE_ERRORCODE(SHOP_BUY_SALE_OUT)					// 商店购买售罄
		CL_DEFINE_ERRORCODE(SHOP_REFRESH_NOT_ENOUGH_MONEY)		// 商店刷新点券不足
		CL_DEFINE_ERRORCODE(SHOP_NOT_ENOUGH_TOWER_LEVEL)		// 死亡塔层数不够
		CL_DEFINE_ERRORCODE(SHOP_NOT_ENOUGH_DUEL_POINT)			// 角斗场积分不足
		CL_DEFINE_ERRORCODE(SHOP_REFRESH_COUNT)					// 商店刷新次数不足
		CL_DEFINE_ERRORCODE(SHOP_GUIlD_SHOP_NOT_EXIST)			// 公会商店不存在
		CL_DEFINE_ERRORCODE(SHOP_GUIlD_NOT_ENOUGH_LV)			// 工会商店等级不足
		CL_DEFINE_ERRORCODE(SHOP_NOT_ENOUGH_SEASONLV)			// 商店需要的段位不足
		CL_DEFINE_ERRORCODE(SHOP_WAIT_WORLD_RESPONSE)			// 商店等待world返回
		CL_DEFINE_ERRORCODE(SHOP_ACTIVITY_CLOSE)				// 活动商店已经关闭
		CL_DEFINE_ERRORCODE(SHOP_IN_LEASEING)					// 商品租赁中
		CL_DEFINE_ERRORCODE(SHOP_BUY_BLESS_CRYSTAL_NOT_ENOUGH)	// 赐福水晶不足
		CL_DEFINE_ERRORCODE(SHOP_ITEM_IS_OFF_SALE)				// 商品已下架
		CL_DEFINE_ERRORCODE(SHOP_BUY_GNOME_COIN_NOT_ENOUGH)		// 地精纪念币不足
		CL_DEFINE_ERRORCODE(SHOP_BUY_BOUNTY_NOT_ENOUGH)			// 赏金不足
		CL_DEFINE_ERRORCODE(SHOP_BUY_HONOR_LVL_NOT_ENOUGH)		// 荣誉等级不足
		CL_FUNCTION_ERRORCODE_END(SHOP)

		//mail error code 
		CL_FUNCTION_ERRORCODE_BEGIN(MAIL)
		CL_DEFINE_ERRORCODE(MAIL_ERROR)							// 邮件系统错误
		CL_DEFINE_ERRORCODE(MAIL_TITLE_ERROR)					// 标题错误
		CL_DEFINE_ERRORCODE(MAIL_TITLE_LENGTH_ERROR)			// 标题长度错误
		CL_DEFINE_ERRORCODE(MAIL_CONTENT_ERROR)					// 内容错误
		CL_DEFINE_ERRORCODE(MAIL_CONTENT_LENGTH_ERROR)			// 内容长度错误
		CL_DEFINE_ERRORCODE(MAIL_SENDER_NAME_ERROR)				// 发件人字符串错误
		CL_DEFINE_ERRORCODE(MAIL_SENDER_NAME_LENGTH_ERROR)		// 发件人字符串长度错误
		CL_DEFINE_ERRORCODE(MAIL_REWARD_ERROR)					// 奖励错误
		CL_FUNCTION_ERRORCODE_END(MAIL)

        CL_FUNCTION_ERRORCODE_BEGIN(TEAM)
        CL_DEFINE_ERRORCODE(TEAM_ERROR)							// 组队系统错误
        CL_DEFINE_ERRORCODE(TEAM_CREATE_TEAM_HAS_TEAM)          // 创建队伍，已经有队伍了
        CL_DEFINE_ERRORCODE(TEAM_CREATE_TEAM_INVALID_TARGET)    // 创建队伍，无效的队伍目标

        CL_DEFINE_ERRORCODE(TEAM_JOIN_TIMEOUT)                  // 加入队伍，超时
        CL_DEFINE_ERRORCODE(TEAM_JOIN_TEAM_UNEXIST)             // 加入队伍，队伍不存在
        CL_DEFINE_ERRORCODE(TEAM_JOIN_TEAM_FULL)                // 加入队伍，队伍满
        CL_DEFINE_ERRORCODE(TEAM_JOIN_TEAM_MASTER_OFFLINE)      // 加入队伍，队长离线
        CL_DEFINE_ERRORCODE(TEAM_JOIN_TEAM_HAS_TEAM)            // 加入队伍，已经有队伍了
        CL_DEFINE_ERRORCODE(TEAM_JOIN_TEAM_PASSWD_ERROR)        // 加入队伍，密码错误
        CL_DEFINE_ERRORCODE(TEAM_JOIN_TEAM_HAS_PASSWD)          // 加入队伍，队伍有密码
		CL_DEFINE_ERRORCODE(TEAM_JOIN_LEVEL_LIMIT)				// 加入队伍，等级不足

        CL_DEFINE_ERRORCODE(TEAM_PASSWD_ERROR_LENGTH)           // 密码长度不对
        CL_DEFINE_ERRORCODE(TEAM_PASSWD_ONLY_NUM)               // 密码只能是数字
        CL_DEFINE_ERRORCODE(TEAM_NAME_TOO_LONG)                 // 名字太长
        CL_DEFINE_ERRORCODE(TEAM_NAME_INVALID)                  // 无效的名字
		CL_DEFINE_ERRORCODE(TEAM_TARGET_INVALID)                // 无效的目标
		CL_DEFINE_ERRORCODE(TEAM_TOO_MANY_PLAYER)               // 切换目标失败，人数太多

		CL_DEFINE_ERRORCODE(TEAM_REPLY_NOT_MASTER)				// 处理申请者，你不是队长
		CL_DEFINE_ERRORCODE(TEAM_REPLY_PLAYER_OFFLINE)          // 处理申请者，玩家不在线
		CL_DEFINE_ERRORCODE(TEAM_REPLY_PLAYER_INVALID)          // 处理申请者，该玩家未申请加入
		CL_DEFINE_ERRORCODE(TEAM_REPLY_TEAM_FULL)				// 处理申请者，队伍已满

		CL_DEFINE_ERRORCODE(TEAM_INVITE_NO_TEAM)				// 邀请玩家，自己没有队伍
		CL_DEFINE_ERRORCODE(TEAM_INVITE_NOT_TEAM_MASTER)		// 邀请玩家，自己不是队长
		CL_DEFINE_ERRORCODE(TEAM_INVITE_TEAM_FULL)				// 邀请玩家，队伍已满
		CL_DEFINE_ERRORCODE(TEAM_INVITE_TEAM_IN_RACE)			// 邀请玩家，队伍正在战斗中
		CL_DEFINE_ERRORCODE(TEAM_INVITE_TARGET_OFFLINE)			// 邀请玩家，对方不在线
		CL_DEFINE_ERRORCODE(TEAM_INVITE_TARGET_IN_TEAM)			// 邀请玩家，对方已经在队伍中
		CL_DEFINE_ERRORCODE(TEAM_INVITE_TARGET_BUSY)			// 邀请玩家，目标正忙
		CL_DEFINE_ERRORCODE(TEAM_INVITE_REPEAT)					// 邀请玩家，重复邀请

		CL_DEFINE_ERRORCODE(TEAM_JOIN_RACING)					// 加入队伍，队伍正在战斗中
		CL_DEFINE_ERRORCODE(TEAM_MIN_LEVEL)						// 等级不足
		CL_DEFINE_ERRORCODE(TEAM_INVITE_TARGET_MIN_LEVEL)		// 邀请玩家，对方等级不足
		CL_DEFINE_ERRORCODE(TEAM_INVITE_FREQUENTLY)				// 邀请玩家，太频繁

		CL_DEFINE_ERRORCODE(TEAM_JOIN_NOT_IN_TOWN)				// 加入队伍，不在城镇中
		CL_DEFINE_ERRORCODE(TEAM_JOIN_INVITE_TIMEOUT)			// 加入队伍，邀请已失效
		CL_DEFINE_ERRORCODE(TEAM_CREATE_NOT_IN_TOWN)			// 创建队伍失败，不在城镇中
		CL_DEFINE_ERRORCODE(TEAM_INVITE_MASTER_NOT_AGREE)		// 邀请玩家，队长未同意

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(TEAM, TEAM_MATCH, 1)
		CL_DEFINE_ERRORCODE(TEAM_MATCH_START_FAILED)			// 开始匹配失败，这种情况不需要提示
		CL_DEFINE_ERRORCODE(TEAM_MATCH_ONLY_MASTER)				// 只有队长能操作
		CL_DEFINE_ERRORCODE(TEAM_MATCH_START_IN_MATCHING)		// 开始匹配失败，已经在匹配中
		
		CL_DEFINE_ERRORCODE(TEAM_MATCH_CANCEL_NOT_IN_MATCHING)	// 取消匹配失败，不在匹配中

        CL_FUNCTION_ERRORCODE_END(TEAM)

		//WarpStone error code
		CL_FUNCTION_ERRORCODE_BEGIN(WARPSTONE)
			CL_DEFINE_ERRORCODE(WARP_STONE_SILVER_ERROR)			//银币不够
			CL_DEFINE_ERRORCODE(WARP_STONE_UNLOCK_ERROR)			//没有解锁
			CL_DEFINE_ERRORCODE(WARP_STONE_LEVEL_MAX)				//到达最大等级
			CL_DEFINE_ERRORCODE(WARP_STONE_NOT_FOUNT)				//次元石没找到
			CL_DEFINE_ERRORCODE(WARP_STONE_PLAYER_LEVEL_ERROR)		//次元石解锁等级不够
			CL_DEFINE_ERRORCODE(ENERGY_STONE_NOT_FOUNT)				//能量石没有找到
			CL_DEFINE_ERRORCODE(ENERGY_STONE_NOT_ENOUGH)			//能量石不够
			CL_DEFINE_ERRORCODE(ENERGY_STONE_TYPE_ERROR)			//能量石类型错误

		CL_FUNCTION_ERRORCODE_END(WARPSTONE)

		//retinue error code
		CL_FUNCTION_ERRORCODE_BEGIN(RETINUE)
			CL_DEFINE_ERRORCODE(RETINUE_NOT_PLAYER)					//没有对应的玩家
			CL_DEFINE_ERRORCODE(RETINUE_DATA_NOT_EXIST)				//随从数据表不存在
			CL_DEFINE_ERRORCODE(RETINUE_NOT_EXIST)					//随从不存在
			CL_DEFINE_ERRORCODE(RETINUE_IS_EXIST)					//随从已经存在
			CL_DEFINE_ERRORCODE(RETINUE_PLAYER_LEVEL)				//玩家等级不够
			CL_DEFINE_ERRORCODE(RETINUE_NOT_ITEM)					//洗练物品不够
			CL_DEFINE_ERRORCODE(RETINUE_UNLOCK_NOT_ITEM)			//解锁物品不够
			CL_DEFINE_ERRORCODE(RETINUE_LEVEL_DATA_NOT_EXIST)		//随从等级不存在.
			CL_DEFINE_ERRORCODE(RETINUE_LEVEL_NOT_ITEM)				//升级物品不够
			CL_DEFINE_ERRORCODE(RETINUE_RETINUE_INDEX_ERROR)		//设置随从位置错误
			CL_DEFINE_ERRORCODE(RETINUE_WARRIOR_SOUL_ERROR)			//勇士之魂不够
			CL_DEFINE_ERRORCODE(RETINUE_MAX_STAR_ERROR)				//不能超过最大星级
			CL_DEFINE_ERRORCODE(RETINUE_STAR_LEVEL_NOT_EXIST)		//没有这个星级
			CL_DEFINE_ERRORCODE(RETINUE_UP_STAR_NOT_ITEM)			//升星碎片不够
			CL_DEFINE_ERRORCODE(RETINUE_NOT_CHANGE_SKILL_ERROR)		//没有可洗练的技能
			CL_DEFINE_ERRORCODE(RETINUE_NOT_SKILL_GROUP_ERROR)		//没有对应的洗练库
			CL_DEFINE_ERRORCODE(RETINUE_SKILL_GROUP_RING_ERROR)		//洗练库是一个环
			CL_DEFINE_ERRORCODE(RETINUE_UP_TYPE_ERROR)				//升级类型不正确
			CL_DEFINE_ERRORCODE(RETINUE_NOT_MAIN_ERROR)				//没有主随从
			CL_DEFINE_ERRORCODE(RETINUE_NOT_DOWN_ERROR)				//无法下阵随从

		CL_FUNCTION_ERRORCODE_END(RETINUE)

		//商城
		CL_FUNCTION_ERRORCODE_BEGIN(MALL)
		CL_DEFINE_ERRORCODE(MALL_QUERY_FAIL)						//商城商品查询失败
		CL_DEFINE_ERRORCODE(MALL_BUYNUM_ERR)						//购买数量错误
		CL_DEFINE_ERRORCODE(MALL_CANNOT_FIND_MALL_GOODS)			//找不到商城中的商品
		CL_DEFINE_ERRORCODE(MALL_CANNOT_FIND_GIFT_PACK)				//找不到要触发的限时礼包
		CL_DEFINE_ERRORCODE(MALL_GIFT_PACK_ACTIVATED)				//商城限时礼包已触发
		CL_DEFINE_ERRORCODE(MALL_CANNOT_FIND_PERSONAL_TAILOR)		//找不到私人订制
		CL_DEFINE_ERRORCODE(FAILED_TO_CREATE_PERSONAL_TAILOR)		//创建私人订制失败
		CL_DEFINE_ERRORCODE(LIMIT_TO_CREATE_PERSONAL_TAILOR)		//限制创建私人订制
		CL_FUNCTION_ERRORCODE_END(MALL)

		//player error code
		CL_FUNCTION_ERRORCODE_BEGIN(PLAYER)
		CL_DEFINE_ERRORCODE(PLAYER_TRANSFORM_OCCU_LEVEL_ERROR)		//转职等级不够
		CL_DEFINE_ERRORCODE(PLAYER_AWAKEN_LEVEL_ERROR)				//觉醒等级不够
		CL_DEFINE_ERRORCODE(PLAYER_AWAKEN_EXIST)					//已经觉醒
		CL_DEFINE_ERRORCODE(PLAYER_AWAKEN_NOT_TRANSFORM_OCCU)		//还未转职
		CL_DEFINE_ERRORCODE(PLAYER_VIP_BUY_LEVEL_ERROR)				//vip购买时,vip等级错误
		CL_DEFINE_ERRORCODE(PLAYER_VIP_BUY_GIFT_ENOUGH_POINT)		//vip购买礼包,点卷不够
		CL_DEFINE_ERRORCODE(PLAYER_VIP_GIFT_EMPTY)					//vip礼包为空
		CL_DEFINE_ERRORCODE(PLAYER_VIP_BUY_NOT_ENOUGH_PACKSIZE)		//vip购买礼包背包空间不足
		CL_DEFINE_ERRORCODE(PLAYER_VIP_BUY_REMOVE_POINT_ERROR)		//vip购买礼包消耗点卷失败
		CL_DEFINE_ERRORCODE(PLAYER_VIP_BUY_ALREADY)					//vip已经购买这个礼包
		CL_DEFINE_ERRORCODE(PLAYER_VIPLV_NOT_ENOUGH)				//vip等级不足
		CL_DEFINE_ERRORCODE(PLAYER_MONEY_MANAGE_REWARD_NOT_FOUNT)	// 理财奖励不存在
		CL_DEFINE_ERRORCODE(PLAYER_MONEY_MANAGE_REWARD_EXIST)		// 理财奖励不能重复领取
		CL_DEFINE_ERRORCODE(PLAYER_MONEY_MANAGE_REWARD_ROLE_ERROR)	// 该角色无法领取理财奖励
		CL_DEFINE_ERRORCODE(PLAYER_MONEY_MANAGE_LEVEL_ERROR)		// 该角色领取理财奖励,等级不够
		CL_FUNCTION_ERRORCODE_END(PLAYER)

		//快速购买
		CL_FUNCTION_ERRORCODE_BEGIN(QUICKBUY)
		// 通用提示
		CL_DEFINE_ERRORCODE(QUICK_BUY_SYSTEM_ERROR)					//系统错误
		CL_DEFINE_ERRORCODE(QUICK_BUY_LAST_TRANS_NOT_FINISH)		//上一个事务还没结束
		CL_DEFINE_ERRORCODE(QUICK_BUY_TIMEOUT)						//超时
		CL_DEFINE_ERRORCODE(QUICK_BUY_INVALID_TYPE)					//无效的类型
		CL_DEFINE_ERRORCODE(QUICK_BUY_NOT_ENOUGH_MONEY)				//钱不够
		CL_DEFINE_ERRORCODE(QUICK_BUY_INVALID_ITEM)					//道具不存在
		CL_DEFINE_ERRORCODE(QUICK_BUY_INVALID_NUM)					//道具数量不正确
		CL_DEFINE_ERRORCODE(QUICK_BUY_BAG_FULL)						//背包空间不足

		// 复活
		CL_DEFINE_ERRORCODE(QUICK_BUY_REVIVE_NOT_IN_RACE)			//不在比赛中

		CL_FUNCTION_ERRORCODE_END(QUICKBUY)

		//任务相关
		CL_FUNCTION_ERRORCODE_BEGIN(TASK)
		CL_DEFINE_ERRORCODE(TASK_SET_ITEM_TASK_TYPE_ERROR)			//提交任务物品类型错误
		CL_DEFINE_ERRORCODE(TASK_SET_ITEM_ERROR)					//提交错误的任务物品
		CL_DEFINE_ERRORCODE(TASK_SET_ITEM_NUM_ERROR)				//提交的任务物品数量不够
		CL_DEFINE_ERRORCODE(TASK_NOT_EXIST)							//任务不存在
		CL_DEFINE_ERRORCODE(TASK_SCRIPT_NOT_EXIST)					//任务脚本不存在
		CL_DEFINE_ERRORCODE(TASK_NOT_UNFINISH)						//任务不再接取状态
		CL_DEFINE_ERRORCODE(TASK_TYPE_ERROR)						//任务类型错误
		CL_DEFINE_ERRORCODE(TASK_CYCLE_NOT_EXIST)					//循环任务不存在
		CL_DEFINE_ERRORCODE(TASK_CYCLE_REFRESH_NOT_CONSUME)			//消耗资源不足

		CL_DEFINE_ERRORCODE(TASK_DATILY_TASK_SCORE_BOX_NOT_FOUNT)	//每日任务积分奖励箱子不存在
		CL_DEFINE_ERRORCODE(TASK_DATILY_TASK_SCORE_BOX_SCORE)		//每日任务积分奖励积分不够
		CL_DEFINE_ERRORCODE(TASK_DATILY_TASK_SCORE_BOX_RECEIVE)		//每日任务积分奖励已经领取

		CL_DEFINE_ERRORCODE(TASK_ACHIEVEMENT_SCORE_BOX_NOT_FOUNT)	//成就积分奖励箱子不存在
		CL_DEFINE_ERRORCODE(TASK_ACHIEVEMENT_SCORE_BOX_SCORE)		//成就积分奖励积分不够
		CL_DEFINE_ERRORCODE(TASK_ACHIEVEMENT_SCORE_BOX_RECEIVE)		//成就积分奖励已经领取

		CL_FUNCTION_ERRORCODE_END(TASK)

		//死亡之塔相关
		CL_FUNCTION_ERRORCODE_BEGIN(TOWER)

		CL_DEFINE_ERRORCODE(TOWER_RESET_NO_REMAIN_COUNT)			// 没有重置次数

		CL_DEFINE_ERRORCODE(TOWER_DOING_WIPEOUT)					// 正在扫荡中
		CL_DEFINE_ERRORCODE(TOWER_NO_FLOOR_WIPEOUT)					// 没有层数去扫荡

		CL_DEFINE_ERRORCODE(TOWER_NOT_DOING_WIPEOUT)				// 没有在扫荡中
		CL_DEFINE_ERRORCODE(TOWER_WIPEOUT_NOT_FINISH)				// 扫荡未完成

		CL_DEFINE_ERRORCODE(TOWER_WIPEOUT_FINISHED)					// 扫荡已完成
		CL_DEFINE_ERRORCODE(TOWER_WIPEOUT_NOT_ENOUGH_POINT)			// 没有足够的点劵

		CL_DEFINE_ERRORCODE(TOWER_AWARD_NOT_PASS_FLOOR)				// 未通过该层
		CL_DEFINE_ERRORCODE(TOWER_AWARD_INVALID_FLOOR)				// 无效的层数，没有对应奖励
		CL_DEFINE_ERRORCODE(TOWER_AWARD_REPEAT_RECEIVE)				// 重复领奖

		CL_DEFINE_ERRORCODE(TOWER_NO_NEED_RESET)					// 不需要重置
		CL_DEFINE_ERRORCODE(TOWER_RESET_NO_VIP_PRIVILEGE)			// 没有VIP权限

		CL_FUNCTION_ERRORCODE_END(TOWER)

		//PK相关
		CL_FUNCTION_ERRORCODE_BEGIN(PK)

		CL_DEFINE_ERRORCODE(PK_CHALLENGE_IN_TEAM)					// 组队中
		CL_DEFINE_ERRORCODE(PK_CHALLENGE_NOT_IN_PK_PREPARE)			// 不在PK准备区中	
		CL_DEFINE_ERRORCODE(PK_CHALLENGE_TARGET_BUSY)				// 目标在忙
		CL_DEFINE_ERRORCODE(PK_CHALLENGE_TARGET_NOT_ONLINE)			// 目标不在线
		CL_DEFINE_ERRORCODE(PK_CHALLENGE_REPEAT)					// 重复挑战
		CL_DEFINE_ERRORCODE(PK_CHALLENGE_LEVEL_LIMIT)				// 等级太低


		// 武道大会
		CL_DEFINE_ERRORCODE(PK_WUDAO_SYSTEM_ERROR)					// 系统错误
		CL_DEFINE_ERRORCODE(PK_WUDAO_ACTIVITY_NOT_OPEN)				// 活动未开始
		CL_DEFINE_ERRORCODE(PK_WUDAO_ACTIVITY_COND)					// 不满足活动开启条件
		CL_DEFINE_ERRORCODE(PK_WUDAO_NO_TICKET)						// 没有门票
		CL_DEFINE_ERRORCODE(PK_WUDAO_JOINED)						// 已经参加了
		CL_DEFINE_ERRORCODE(PK_WUDAO_NOT_COMPLETE)					// 武道大会未完成


		CL_DEFINE_ERRORCODE(PK_CHALLENGE_IN_ROOM)					// 房间中
		CL_DEFINE_ERRORCODE(PK_CHALLENGE_SUCCESS)				    // 邀请成功

		CL_FUNCTION_ERRORCODE_END(PK)
		
		//公会相关
		CL_FUNCTION_ERRORCODE_BEGIN(GUILD)
		// 通用返回
		CL_DEFINE_ERRORCODE(GUILD_NO_POWER)							// 没有对应的权限
		CL_DEFINE_ERRORCODE(GUILD_FULL)								// 公会已满
		CL_DEFINE_ERRORCODE(GUILD_NOT_IN_GUILD)						// 不在公会中
		CL_DEFINE_ERRORCODE(GUILD_SYS_ERROR)						// 系统错误
		CL_DEFINE_ERRORCODE(GUILD_NOT_ENOUGH_MONEY)					// 没有足够的钱
		CL_DEFINE_ERRORCODE(GUILD_NOT_ENOUGH_TIMES)					// 次数用完
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_NOT_LEAVE)					// 公会战期间不能离开公会
		CL_DEFINE_ERRORCODE(GUILD_NO_ENOUGH_POINT)					// 没有足够的点劵
		CL_DEFINE_ERRORCODE(GUILD_NO_ENOUGH_ITEM)					// 没有足够的道具

		// 公会字符串
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_STR, 1)
		CL_DEFINE_ERRORCODE(GUILD_NAME_REPEAT)						// 名字重复
		CL_DEFINE_ERRORCODE(GUILD_NAME_INVALID)						// 名字中有屏蔽字
		CL_DEFINE_ERRORCODE(GUILD_DECLARATION_INVALID)				// 宣言中有屏蔽字
		CL_DEFINE_ERRORCODE(GUILD_ANNOUNCEMENT_INVALID)				// 公告中有屏蔽字
		CL_DEFINE_ERRORCODE(GUILD_MAIL_INVALID)						// 公告中有屏蔽字

		// 创建公会
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_CREATE, 2)
		CL_DEFINE_ERRORCODE(GUILD_CREATE_REPEAT)					// 重复创建
		CL_DEFINE_ERRORCODE(GUILD_CREATE_ALREADY_HAS_GUILD)			// 已经在公会中
		CL_DEFINE_ERRORCODE(GUILD_CREATE_INVALID_NAME)				// 无效的公会名
		CL_DEFINE_ERRORCODE(GUILD_CREATE_INVALID_DECLARATION)		// 无效的公会宣言
		CL_DEFINE_ERRORCODE(GUILD_CREATE_NOT_ENOUGH_MONEY)			// 没有足够的钱
		CL_DEFINE_ERRORCODE(GUILD_CREATE_MIN_LEVEL)					// 等级不足
		CL_DEFINE_ERRORCODE(GUILD_CREATE_COLDTIME)					// 刚离开公会，还在冷却时间中
		CL_DEFINE_ERRORCODE(GUILD_CREATE_NAME_EMPTY)				// 公会名为空
		CL_DEFINE_ERRORCODE(GUILD_CREATE_DECLARATION_EMPTY)			// 公会宣言为空

		// 加入公会
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_JOIN, 3)
		CL_DEFINE_ERRORCODE(GUILD_JOIN_REPEAT)						// 重复加入
		CL_DEFINE_ERRORCODE(GUILD_JOIN_ALREADY_HAS_GUILD)			// 已经在公会中
		CL_DEFINE_ERRORCODE(GUILD_JOIN_MIN_LEVEL)					// 等级不足
		CL_DEFINE_ERRORCODE(GUILD_JOIN_NOT_EXIST)					// 公会不存在
		CL_DEFINE_ERRORCODE(GUILD_JOIN_COLDTIME)					// 刚离开公会，还在冷却时间中
		CL_DEFINE_ERRORCODE(GUILD_JOIN_REQUEST_QUEUE_FULL)			// 公会申请列表已满
		CL_DEFINE_ERRORCODE(GUILD_JOIN_IN_DISMISS)					// 公会正在解散
		CL_DEFINE_ERRORCODE(GUILD_JOIN_LEVEL_LIMIT_APPROVAL)		// 玩家等级不足，无法加入
		CL_DEFINE_ERRORCODE(GUILD_NOT_CAN_JOIN)						// 没有符合要求的公会
		CL_DEFINE_ERRORCODE(GUILD_JOIN_LEVEL_LIMIT_APPLY)				// 玩家等级不足，无法申请入会


		// 离开公会
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_LEAVE, 4)
		CL_DEFINE_ERRORCODE(GUILD_LEAVE_TRANSFER_LEADER)			// 先转让会长

		// 处理公会新成员请求
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_REPLY, 5)
		CL_DEFINE_ERRORCODE(GUILD_REPLY_REQUESTER_UNEXIST)			// 没有这个请求者
		CL_DEFINE_ERRORCODE(GUILD_REPLY_IN_OTHER_GUILD)				// 已经在其他公会中了
		CL_DEFINE_ERRORCODE(GUILD_REPLY_COLDTIME)					// 刚离开公会，还在冷却时间中

		// 任命职务
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_POST, 6)
		CL_DEFINE_ERRORCODE(GUILD_POST_FULL)						// 目标职务人数已满
		CL_DEFINE_ERRORCODE(GUILD_POST_LEADER_LEAVE_TIME)			// 需要会长连续7天不在线

		// 建筑
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_BUILDING, 7)
		CL_DEFINE_ERRORCODE(GUILD_BUILDING_UPGRADE_MAIN_FIRST)		// 超过主城等级，先升级主城等级
		CL_DEFINE_ERRORCODE(GUILD_BUILDING_TOP_LEVEL)				// 已经到满级
		CL_DEFINE_ERRORCODE(GUILD_BUILDING_NOT_ENOUGH_FUND)			// 帮会资金不足
		CL_DEFINE_ERRORCODE(GUILD_BUILDING_POINT_FUND_TRANSACTION)	// 玩家正在事务中

		// 捐献
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_DONATE, 8)
		CL_DEFINE_ERRORCODE(GUILD_DONATE_NO_REMAIN_TIMES)			// 剩余次数不足

		// 公会兑换
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_EXCHANGE, 9)
		CL_DEFINE_ERRORCODE(GUILD_EXCHANGE_CD)						// 还在CD中
		CL_DEFINE_ERRORCODE(GUILD_EXCHANGE_NO_REMAIN_TIMES)			// 剩余次数不足
		CL_DEFINE_ERRORCODE(GUILD_EXCHANGE_NOT_ENOUGH_CONTRI)		// 贡献不足

		// 公会技能
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_SKILL, 10)
		CL_DEFINE_ERRORCODE(GUILD_SKILL_TOP_LEVEL)					// 已经到达最高等级

		// 工会解散
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_DISMISS, 11)
		CL_DEFINE_ERRORCODE(GUILD_DISMISS_IN_DISMISS)				// 正在解散中
		CL_DEFINE_ERRORCODE(GUILD_NOT_IN_DISMISS)					// 不在解散中

		// 公会圆桌会议
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_TABLE, 12)
		CL_DEFINE_ERRORCODE(GUILD_TABLE_FULL)						// 圆桌已满
		CL_DEFINE_ERRORCODE(GUILD_TABLE_SEAT_HAS_PLAYER)			// 位子已经被占
		CL_DEFINE_ERRORCODE(GUILD_TABLE_REPEAT)						// 已经在位子上了
		CL_DEFINE_ERRORCODE(GUILD_TABLE_SEAT_INVALID)				// 无效的位子

		// 膜拜
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_ORZ, 13)
		CL_DEFINE_ERRORCODE(GUILD_ORZ_INVALID_TYPE)					// 膜拜类型错误
		CL_DEFINE_ERRORCODE(GUILD_ORZ_VIP_PRIVILEGE)				// 没有这个VIP权限

		// 公会战
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_BATTLE, 14)
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_NOT_PLAYER)					// 没有找到玩家
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_NOT_EXIST)						// 玩家没有公会
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_NOT_IS_MEMBER)					// 玩家不是公会成员
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_GUILD_NOT_FIND)			// 公会战报名公会找不到
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_NOT_POWER)				// 玩家报名没有权限
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_NOT_ENROLL)				// 公会战没有开始报名
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_FULL)					// 公会战报名人数已满
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_GUILD_LEVEL)			// 公会战报名公会等级不够
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_TERRITORY_LEVEL_LOW)	// 公会战报名占领领地等级太低
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_TERRITORY_LEVEL_HIGH)	// 公会战报名占领领地等级太高
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_EXIST)					// 公会战不能重复报名
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_TRANSACTION)			// 公会战报名正在处理事务
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_TERRITORY_NOT_EXIST)			// 领地不存在或者公会没有报名

		CL_DEFINE_ERRORCODE(GUILD_BATTLE_NOT_ENROLL)					// 公会没有报名

		CL_DEFINE_ERRORCODE(GUILD_BATTLE_INSPIRE_MAX_COUNT)				// 公会战鼓舞已经最高次数
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_INSPIRE_ITEM)					// 公会战鼓舞道具不足
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_INSPIRE_TRANSACTION)			// 公会战鼓舞正在处理事务

		CL_DEFINE_ERRORCODE(GUILD_BATTLE_MEMBER_MATCH_COUNT)			// 公会战成员匹配次数不足
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_RACE_END_NOT_MEMBER)			// 战斗结束找不到玩家
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_IS_END)						// 公会战已经结束

		CL_DEFINE_ERRORCODE(GUILD_BATTLE_GIVE_REWARD_NOT_MEMBER)		// 领取奖励找不到玩家
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_GIVE_REWARD_DATA_ERROR)		// 领取奖励没有找到数据项
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_GIVE_REWARD_SCORE_ERROR)		// 领取奖励积分不足
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_GIVE_REWARD_ALREADY)			// 奖励已经领取

		CL_DEFINE_ERRORCODE(GUILD_BATTLE_RACE_NOT_END)					// 公会战上一场战斗没有结束
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_MATCH_TRANSACTION)				// 公会战匹配正在处理事务
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_NOT_DISMISS)			// 公会战报名不能解散
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_DISMISS_NOT_ENROLL)			// 公会战解散中不能报名

		CL_DEFINE_ERRORCODE(GUILD_BATTLE_INSPIRE_ENTER_TIME_ERROR)		// 公会战新成员一定时间不能鼓舞

		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_BUSY)					// 公会战报名服务器正忙,报名事务正在处理中
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_NOT_TERRITORY)			// 公会战宣战,这个领地不能报名
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_ITEM_ERROR)				// 公会战宣战,货币错误
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_ENROLL_ITEM_NUM)				// 公会战宣战,货币数量错误
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_SET_PROBABILITY_ERROR)			// 公会战抽奖几率设置错误
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_TYPE_ERROR)					// 公会战类型错误
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_SET_SETTING_ERROR)				// 公会仓库设置错误
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_LETTORY_STATUS_ERROR)			// 公会不是抽奖状态
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_PLAYER_NOT_LETTORY)			// 玩家不能抽奖
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_INSPIRE_CHALLENGE_NUM)			// 公会宣战,准备状态才能鼓舞
		CL_DEFINE_ERRORCODE(GUILD_BATTLE_NOT_OCCUPY_TERRITORY)			// 公会未占领领地

		// 公会仓库
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_STORAGE, 15)
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_DATA_INVALID)					// 公会仓库数据错误
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_PLAYER_NOT_ONLINE)			// 玩家不在线
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_CANNOT_ADD)					// 道具不满足放入公会仓库
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_NOT_FULL_IN)					// 公会仓库没法全部放入
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_DELITEM_FAIL)					// 公会仓库删除道具失败
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_LETTORY_ERROR)				// 抽奖状态不能操作公会仓库
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_DISMISS_ERROR)				// 公会解散中不能操作仓库
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_FULL)							// 公会仓库满了
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_MAGIC_LEV)					// 等级大于0的附魔卡不能放入公会仓库
		CL_DEFINE_ERRORCODE(GUILD_STORAGE_STRENGTHEN_LEV)				// 等级大于10的装备不能放入公会仓库

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, CROSS_GUILD_BATTLE, 16)
		CL_DEFINE_ERRORCODE(CROSS_GUILD_BATTLE_NEED_TERRITORY)			// 需要占领指定领地
		CL_DEFINE_ERRORCODE(CROSS_GUILD_BATTLE_NOT_RESULT)				// 没有回包
		CL_DEFINE_ERRORCODE(CROSS_GUILD_BATTLE_SORT_NOT_GUILD)			// 这个排行榜没有数据
		CL_DEFINE_ERRORCODE(CROSS_GUILD_BATTLE_NOT_OPEN)				// 跨服工会战没有开启

		// 公会地下城
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_DUNGEON, 17)
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_ERROR)					// 公会地下城错误
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_CFG_ERROR)				// 公会地下城配置错误
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_NOT_FINISH)				// 公会地下城没有通关
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_REWARD_ERROR)				// 公会地下城奖励错误
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_REWARD_GET_REPEATED)		// 公会地下城已经领取了奖励
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_NOT_LEAVE)				// 公会地下城开启不能离开公会
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_GUILD_LEVEL_LIMIT)		// 公会等级不足
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_PLAYER_LEVEL_LIMIT)		// 公会副本，玩家等级不足
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_NOT_SAME_GUILD)			// 公会副本，玩家不是同一公会
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_NOT_KICK)					// 公会地下城开启不能踢人
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_NOT_OPEN)					// 公会地下城未开启
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_GATE_FINISH)				// 公会地下城已通关
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_NOT_JOIN)					// 公会地下城开启不能加入公会
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_CD)						// 公会地下城CD
		CL_DEFINE_ERRORCODE(GUILD_DUNGEON_NOT_SET_TYPE)				// 公会地下城开启不可设置副本难度


		// 公会拍卖
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_AUCTION, 18)
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_TYPE_ERROR)			// 公会拍卖类型错误
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_ITEM_NOT_EXIST)		// 公会拍卖品不存在
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_BID_BE_OVER)			// 公会拍卖竞价被超过
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_BID_PRICE_ERROR)		// 公会拍卖竞价出价错误
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_BEING_BID)			// 公会拍卖您的竞价正在处理
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_NOT_SEAL_STATE)		// 不在拍卖状态
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_OVER_FIX)				// 超过一口价
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_PREPARE)				// 拍卖准备中
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_DEAL)					// 拍卖已成交
		CL_DEFINE_ERRORCODE(GUILD_AUCTION_ABORATION)			// 拍卖已流拍

		// 公会徽记
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_EMBLEM, 19)
		CL_DEFINE_ERRORCODE(GUILD_EMBLEM_ACTIVATE_ERROR)		// 公会徽记激活错误
		CL_DEFINE_ERRORCODE(GUILD_EMBLEM_HONOUR_LEVEL_NOT_ENOUGH)// 公会徽记升级荣耀殿堂等级不足

		// 公会兼并
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(GUILD, GUILD_MERGER, 20)
		CL_DEFINE_ERRORCODE(GUILD_MERGER_REQUEST_EXISTS)		  //请求已存在 
		CL_DEFINE_ERRORCODE(GUILD_MERGER_REQUEST_NOT_EXISTS)      //请求不存在
		CL_DEFINE_ERRORCODE(GUILD_MERGER_INVAILD)                 //非法操作
		CL_DEFINE_ERRORCODE(GUILD_MERGER_REQUEST_ONE)             //只能同时同意一个兼并申请
		CL_DEFINE_ERRORCODE(GUILD_MERGER_TIME_SHORT)              //距离上一次兼并时间过短
		CL_FUNCTION_ERRORCODE_END(GUILD)

		//事务
		CL_FUNCTION_ERRORCODE_BEGIN(ITEM_TRANS)
		CL_DEFINE_ERRORCODE(ITEM_TRANS_FAILED)						// 失败
		CL_DEFINE_ERRORCODE(ITEM_TRANS_NOT_ENOUGH_MONEY)			// 钱不够
		CL_DEFINE_ERRORCODE(ITEM_TRANS_NOT_ENOUGH_REVIVE_COIN)		// 复活币不足
		CL_DEFINE_ERRORCODE(ITEM_TRANS_NOT_ENOUGH_ITEM)				// 道具不足
		CL_DEFINE_ERRORCODE(ITEM_TRANS_NOT_ENOUGH_TIMES)			// 次数不足
		CL_DEFINE_ERRORCODE(ITEM_TRANS_NOT_ENOUGH_FATIGUE)			// 疲劳不足
		CL_FUNCTION_ERRORCODE_END(ITEM_TRANS)

		// 红包
		CL_FUNCTION_ERRORCODE_BEGIN(RED_PACKET)
		CL_DEFINE_ERRORCODE(RED_PACKET_SYS_ERROR)					// 系统错误
		CL_DEFINE_ERRORCODE(RED_PACKET_INVALID)						// 无效的红包
		CL_DEFINE_ERRORCODE(RED_PACKET_NOT_EXIST)					// 红包不存在
		CL_DEFINE_ERRORCODE(RED_PACKET_NOT_OWNER)					// 红包不是你的
		CL_DEFINE_ERRORCODE(RED_PACKET_ALREADY_SEND)				// 红包已经发出去了
		CL_DEFINE_ERRORCODE(RED_PACKET_NOT_IN_GUILD)				// 公会红包，不在公会中
		CL_DEFINE_ERRORCODE(RED_PACKET_CANT_OPEN)					// 红包无法打开
		CL_DEFINE_ERRORCODE(RED_PACKET_EMPTY)						// 红包已被抢完
		CL_DEFINE_ERRORCODE(RED_PACKET_INVALID_NUM)					// 红包个数错误
		CL_DEFINE_ERRORCODE(RED_PACKET_INVALID_NAME)				// 红包名字错误
		CL_DEFINE_ERRORCODE(RED_PACKET_NOT_OPEN)					// 系统未开放
		CL_DEFINE_ERRORCODE(RED_PACKET_NO_VIP_PRIVILEGE)			// 没有VIP权限
		CL_DEFINE_ERRORCODE(RED_PACKET_IN_GUILD_BATTLE)			    // 公会战期间无法发红包
		CL_DEFINE_ERRORCODE(RED_PACKET_IN_GUILD_CROSS_BATTLE)	    // 跨服公会战期间无法发红包
		CL_DEFINE_ERRORCODE(RED_PACKET_IN_GUILD_DUNGEON)			// 公会地下城期间无法发红包
		CL_DEFINE_ERRORCODE(RED_PACKET_ACCOUNT_OPENED)			    // 账号下角色已经打开过公会红包
		CL_DEFINE_ERRORCODE(RED_PACKET_ACCOUNT_GUILD_OPENED_MAX)	// 账号日领取公会红包达到上限
		CL_FUNCTION_ERRORCODE_END(RED_PACKET)

		//充值
		CL_FUNCTION_ERRORCODE_BEGIN(BILLING)
		CL_DEFINE_ERRORCODE(BILLING_PLAYER_OFFLINE)					// 玩家不在线
		CL_DEFINE_ERRORCODE(BILLING_GOODS_UNEXIST)					// 货物不存在
		CL_DEFINE_ERRORCODE(BILLING_GOODS_NUM_LIMIT)				// 没有次数了
		CL_DEFINE_ERRORCODE(BILLING_GOODS_MONTH_CARD_CANT_BUY)		// 月卡时间未到无法购买
		CL_DEFINE_ERRORCODE(BILLING_GOODS_MONEY_MANAGE_CARD_BUY)	// 理财卡不能重复购买
		CL_DEFINE_ERRORCODE(BILLING_GOODS_ADVENTURE_KING_ALREADY)	// 不是普通版通行证
		CL_DEFINE_ERRORCODE(BILLING_GOODS_ADVENTURE_KING_CANT_USE_RMB)	// 本赛季不支持rmb购买
		CL_DEFINE_ERRORCODE(BILLING_GOODS_ALREADY_HAVE_GIFT_RIGHT_CAARD)	// 已经有礼遇特权卡了
		CL_FUNCTION_ERRORCODE_END(BILLING)

		//拍卖行
		CL_FUNCTION_ERRORCODE_BEGIN(AUCTION)
		CL_DEFINE_ERRORCODE(AUCTION_REFRESH_ERROR)					// 拍卖行刷新，系统错误
		CL_DEFINE_ERRORCODE(AUCTION_REFRESH_NO_ENOUGH_MONEY)		// 拍卖行刷新，没有足够的货币
		CL_DEFINE_ERRORCODE(AUCTION_BOOTH_FULL)						// 栏位已满，没的买了
		CL_DEFINE_ERRORCODE(AUCTION_BUY_BOOTH_NO_ENOUGH_MONEY)		// 购买栏位，没有足够的货币
		CL_DEFINE_ERRORCODE(AUCTION_ATTENT_FULL)					// 拍卖行关注数量满额
		CL_DEFINE_ERRORCODE(AUCTION_OFFSALE)						// 拍卖行物品已经下架或售出

		CL_FUNCTION_ERRORCODE_END(AUCTION)

		//聊天
		CL_FUNCTION_ERRORCODE_BEGIN(CHAT)
		CL_DEFINE_ERRORCODE(CHAT_MAX_SHOW_WIDTH_ERR)				// 最大聊天内容显示宽度错误
		CL_DEFINE_ERRORCODE(CHAT_PARSER_ERR)						// 聊天文字解析错误
		CL_DEFINE_ERRORCODE(CHAT_DUMP_WORD_ERR)						// 导出转义后的文字错误
		CL_FUNCTION_ERRORCODE_END(CHAT)

		// 喇叭
		CL_FUNCTION_ERRORCODE_BEGIN(HORN)
		CL_DEFINE_ERRORCODE(HORN_SYSTEM_ERROR)						// 系统错误
		CL_DEFINE_ERRORCODE(HORN_NOT_ENOUGH_MONEY)					// 钱不够
		CL_DEFINE_ERRORCODE(HORN_NOT_ENOUGH)						// 没有足够的喇叭
		CL_DEFINE_ERRORCODE(HORN_FORBID_TALK)						// 被禁言了
		CL_FUNCTION_ERRORCODE_END(HORN)

		CL_FUNCTION_ERRORCODE_BEGIN(PET)							//宠物
		CL_DEFINE_ERRORCODE(PET_NOT_PLAYER)							// 没有对应的玩家
		CL_DEFINE_ERRORCODE(PET_DATA_NOT_EXIST)						// 没有对应的数据项
		CL_DEFINE_ERRORCODE(PET_LEVEL_DATA_NOT_EXIST)				// 没有对应的等级
		CL_DEFINE_ERRORCODE(PET_NOT_EXIST)							// 宠物不存在
		CL_DEFINE_ERRORCODE(PET_MAX_NUM_ERROR)						// 超过宠物上限
		CL_DEFINE_ERRORCODE(PET_IS_FULL_LEVEL)						// 宠物已经满级
		CL_DEFINE_ERRORCODE(PET_PLAYER_LEVEL)						// 玩家等级不足
		CL_DEFINE_ERRORCODE(PET_EGG_DATA_NOT_EXIST)					// 宠物蛋数据不存在
		

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(PET, PET_SOLT, 1)
		CL_DEFINE_ERRORCODE(PET_SOLT_NOT_EXIST)						// 宠物槽位不存在
		CL_DEFINE_ERRORCODE(PET_SOLT_TYPE_ERROR)					// 宠物类型和槽位不匹配

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(PET, PET_DEVOUR, 2)
		CL_DEFINE_ERRORCODE(PET_DEVOUR_GOLD_ERROR)					// 吞噬宠物金币不足

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(PET, PET_SKILL, 3)
		CL_DEFINE_ERRORCODE(PET_SKILL_CHANGE_NUM_ERROR)				// 变更技能次数不足
		CL_DEFINE_ERRORCODE(PET_SKILL_CHANGE_ITEM_NUM)				// 变更技能物品不足
		CL_DEFINE_ERRORCODE(PET_SKILL_CHANGE_DUPLICATION_ERROR)		// 变更技能重复

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(PET, PET_FEED, 4)
		CL_DEFINE_ERRORCODE(PET_FEED_GOLD_NUM_ERROR)					// 宠物金币喂食次数不足
		CL_DEFINE_ERRORCODE(PET_FEED_GOLD_ERROR)						// 宠物金币喂食金币不足
		CL_DEFINE_ERRORCODE(PET_FEED_POINT_NUM_ERROR)					// 宠物点卷喂食次数不足
		CL_DEFINE_ERRORCODE(PET_FEED_POINT_ERROR)						// 宠物点卷喂食点卷不足
		CL_DEFINE_ERRORCODE(PET_FEED_ITEM_ERROR)						// 宠物点卷喂食道具不足
		CL_DEFINE_ERRORCODE(PET_FEED_TYPE_ERROR)						// 宠物喂食类型错误
		CL_DEFINE_ERRORCODE(PET_FEED_INDEX_ERROR)						// 宠物喂食索引错误
		CL_DEFINE_ERRORCODE(PET_FEED_HUNGER_FULL)						// 宠物饱食度已满
		CL_DEFINE_ERRORCODE(PET_FEED_LEVEL_FULL)						// 宠物等级已满

		CL_FUNCTION_ERRORCODE_END(PET)

		CL_FUNCTION_ERRORCODE_BEGIN(CUSTOM_SERVICE)						// 客服系统
		CL_DEFINE_ERRORCODE(CUSTOM_SERVICE_SERVER_ERROR)				// 服务器异常
		CL_DEFINE_ERRORCODE(CUSTOM_SERVICE_INVALID_PARAM)				// 错误的参数
		CL_DEFINE_ERRORCODE(CUSTOM_SERVICE_CLOSED)						// 客服系统功能关闭
		CL_FUNCTION_ERRORCODE_END(CUSTOM_SERVICE)

		CL_FUNCTION_ERRORCODE_BEGIN(RELATION)
		CL_DEFINE_ERRORCODE(SET_MASTER_NOTE)	//设置师傅公告错误
		CL_DEFINE_ERRORCODE(SYS_ERROR)			//系统错误
		CL_DEFINE_ERRORCODE(MASTER_GIVE_NUM_NOT_ENOUGH)	//师傅赠送次数不足
		CL_DEFINE_ERRORCODE(FISNISH_SCHOOL_NOTDISCIPLE)	//出师不是徒弟
		CL_DEFINE_ERRORCODE(RELATION_DISCIPLE_NOTONLINE)	//徒弟不在线
		CL_DEFINE_ERRORCODE(FISNISH_SCHOOL_TEAMERR)				//出师组队出错
		CL_DEFINE_ERRORCODE(FISNISH_SCHOOL_DISCIPLE_LEVELINSUFFIC)	//出师徒弟等级不足
		CL_DEFINE_ERRORCODE(MASTER_PUBlISHTASK_FAIL)	   //发布师门任务失败
		CL_DEFINE_ERRORCODE(MASTER_PUBlISHTASK_FAIL_PUBISHED)	 //发布师门任务失败,已经发布
		CL_DEFINE_ERRORCODE(MASTER_PUBlISHTASK_FAIL_UNREIEVE)	 //发布师门任务失败,未领取
		CL_DEFINE_ERRORCODE(GETDISCIPLE_MASTERTASKS_FAIL)   //获取徒弟师门任务数据失败
		CL_DEFINE_ERRORCODE(MASTER_DAILYTASK_REPORTFAIIL)   //汇报师门任务失败
		CL_DEFINE_ERRORCODE(REPORT_DAILYTASK_FAIL_NOTCOMPLETE) //汇报师门任务失败，师门任务未完成
		CL_DEFINE_ERRORCODE(RECEIEVE_MASTER_DAILYTASK_REWARD_STATEFIAL) //领取师门日常任务奖励失败，任务状态不对
		CL_DEFINE_ERRORCODE(MASTERSYS_NOTFIND_MASTER) //没找到师傅
		CL_DEFINE_ERRORCODE(MASTERSYS_NOTFIND_DISICIPLE) //没找到徒弟
		CL_DEFINE_ERRORCODE(MASTERSYS_NOTFIND_PLAYER) //没找到玩家
		CL_DEFINE_ERRORCODE(MASTERSYS_RECEIEVEGIFT_FAIL) //领取礼包失败
		CL_DEFINE_ERRORCODE(MASTERSYS_RECEIEVEGIFT_GROWTHFAIL) //领取礼包失败,成长值不足
		CL_DEFINE_ERRORCODE(MASTERSYS_RECEIEVEGIFT_RECVED) //领取礼包失败,已经领取过
		CL_DEFINE_ERRORCODE(MASTERSYS_AUTOFINSCHFAIL_TATGETONLINE) //自动出师失败,对方在线
		CL_DEFINE_ERRORCODE(MASTERSYS_AUTOFINSCHFAIL_TATGETOFFLINETIME) //自动出师失败,对方离线时间不够
		CL_DEFINE_ERRORCODE(RELATION_SETREMARK_UNCHANGE_ERROR) //设置备注失败，新旧备注一样
		CL_DEFINE_ERRORCODE(RELATION_SETREMARK_LEN_ERROR) //好友备注长度错误
		CL_DEFINE_ERRORCODE(MASTERSYS_SET_QUEST_DECL_LEN_ERROR) //问卷设置宣言长度错误
		CL_DEFINE_ERRORCODE(MASTERSYS_SET_QUEST_DECL_FORBID_ERROR) //问卷设置宣言有屏蔽字
		CL_DEFINE_ERRORCODE(RELATION_PRESENTGIVE_OFFLINE) //对方不在线，不能赠送礼物
		CL_DEFINE_ERRORCODE(RELATION_ERR_NOTFRIEND) //对方不是你的好友
		CL_DEFINE_ERRORCODE(RELATION_PRESENTGIVE_SELFNOTFRIEND) //你不是对方好友,不能赠送
		CL_DEFINE_ERRORCODE(RELATION_PRESENTGIVE_ALREADYSEND) //好友赠礼已发送过
		CL_DEFINE_ERRORCODE(RELATION_SETREMARK_UNVALID_NAME) //好友备注名字不合法
		CL_DEFINE_ERRORCODE(MASTERSYS_FINSCHFAIL_DISSATISFY_CONDITION) //不满足出师条件

		CL_FUNCTION_ERRORCODE_END(RELATION)

		// 赏金联赛
		CL_FUNCTION_ERRORCODE_BEGIN(PREMIUM_LEAGUE)
		// 报名
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(PREMIUM_LEAGUE, PREMIUM_LEAGUE_ENROLL, 1)
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_ENROLL_SYSTEM_ERROR)			// 系统错误
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_ENROLL_PLAYER_NOT_EXIST)		// 玩家不存在
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_ENROLL_LEVEL_LIMIT)			// 等级限制
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_ENROLL_REPEAT)				// 重复报名
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_ENROLL_MONEY_NOT_ENOUGH)		// 点劵不足
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_ENROLL_CLOSE)				// 不在报名时间内
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_ENROLL_COUNT)				// 超过报名次数
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_ENROLL_DONT_NEED)			// 已经报名成功了，不需要报名

		// 预选赛
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(PREMIUM_LEAGUE, PREMIUM_LEAGUE_PRELIMINAY, 2)
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_PRELIMINAY_NOT_START)		// 预选赛还没开始
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_PRELIMINAY_NOT_ENROLL)		// 没有报名
		CL_DEFINE_ERRORCODE(PREMIUM_LEAGUE_PRELIMINAY_ALREADY_LOSE)		// 已经输了

		CL_FUNCTION_ERRORCODE_END(PREMIUM_LEAGUE)

		// 房间
		CL_FUNCTION_ERRORCODE_BEGIN(ROOM)
		CL_SUB_FUNCTION_ERRORCODE_BEGIN(ROOM, ROOM_SYSTEM, 1)
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_NOT_PLAYER)					// 玩家不存在
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_NOT_ROOM)					// 房间不存在
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_CREATE_ROOM_MAX)			// 已经没有房间可以分配
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PLAYER_NOT_IN_ROOM)			// 玩家不再房间内
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_ROOM_EXIST)					// 房间已经存在
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_ROOM_STATUS_ERROR)			// 房间状态错误
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_ROOM_INVALID)				// 房间已经失效
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PLAYER_IN_ROOM)				// 玩家已经在房间内
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_NAME_INVALID)				// 房间名字中有屏蔽字
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PASSWORD_SIZE_ERROR)		// 房间密码字数不对
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PASSWORD_NOT_NUMBER)		// 房间密码不是数字
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PASSWORD_ERROR)				// 房间密码错误
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_JOIN_PLAYER_MAX)			// 加入房间人满
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_JOIN_BATTLE_START)			// 要加入到房间已经开始战斗
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SLOT_GROUP_ERROR)			// 玩家队伍错误
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SLOT_INDEX_ERROR)			// 玩家队伍索引错误
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SLOT_CLOSE)					// 这个位置已经被关闭
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SLOT_HAVE_PLAYER)			// 这个位置已经有玩家了
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PLAYER_OFFLINE)				// 这个玩家已经离线
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_QUIT_JOIN_ROOM_NOT_EXIST)	// 没有房间可以快速加入
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_TYPE_ERROR)					// 房间类型错误
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_KICKOUT_JOIN_ERROR)			// 被踢出短时间不能进入
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_JOIN_PLAYER_LEVEL)			// 玩家等级不够
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_JOIN_PLAYER_SEASON_LEVEL)	// 玩家段位等级不够
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PASSWORD_NOT_EMPTY)			// 房间密码不能为空
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_QUIT_JOIN_MATCH_NOT_EXIST)	// 没有匹配房间可以快速加入


		CL_SUB_FUNCTION_ERRORCODE_BEGIN(ROOM, ROOM_SYSTEM_PERMISSION, 2)
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PERMISSION_UPDATE)					// 更新房间设置没有权限
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PERMISSION_CHANGE_OWNER)			// 转让房主没有权限
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PERMISSION_KICK_OUT)				// 踢人没有权限
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PERMISSION_KICK_OUT_SELF)			// 不能把自己踢出
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PERMISSION_START_BATTLE)			// 不能开始战斗
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PERMISSION_CANCEL_BATTLE)			// 不能取消战斗
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_PERMISSION_NOT_SEND_INVITE_LINK)	// 不能发送邀请链接

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(ROOM, ROOM_SYSTEM_INVITE, 3)
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_INVITE_NOT_IN_ROOM)				// 邀请玩家不在房间里
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_BE_INVITE_NOT_NORMAL)			// 被邀请玩家不在线
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_BE_INVITE_IN_ROOM)				// 被邀请玩家已经在房间里
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_INVITE_IN_INVITE_LIST)			// 被邀请玩家已经在邀请列表
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_INVITE_INFO_TIMEOUT)			// 邀请信息超时
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_INVITE_INFO_NOT_FOUND)			// 邀请信息没有找到
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_BE_INVITE_REFUSE)				// 玩家拒绝邀请

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(ROOM, ROOM_SYSTEM_SWAP, 4)
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SWAP_REQUEST_EXIST)				// 玩家正在交换位置
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SWAP_REQUEST_BE_SWAP)			// 玩家正在被交换位置
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SWAP_RESPOND_EXIST)				// 对方正在交换位置
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SWAP_RESPOND_BE_SWAP)			// 对方正在被交换位置
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SWAP_INFO_NOT_FOUND)			// 交换信息没有找到
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SWAP_INFO_WAIT)					// 交换信息等待回应
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_SWAP_NOT_SELF)					// 不能与自己交换位置

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(ROOM, ROOM_SYSTEM_READY, 5)
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_READY_PLAYER_SIZE)				// 玩家人数不够
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_READY_STATUS_ERROR)				// 房间状态错误
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_READY_SLOT_STATUS_ERROR)		// 房间位置状态错误
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_READY_SLOT_NOT_READY)			// 还有玩家没有准备
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_READY_SLOT_REFUSE)				// 有玩家已经拒绝
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_READY_PLAYER_NOT_ONLINE)		// 有玩家不在线
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_READY_PLAYER_NOT_ROOM)			// 有玩家没有返回房间

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(ROOM, ROOM_SYSTEM_MATCH, 6)
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_MATCH_ROOM_STATUS_ERROR)		// 匹配时房间状态错误
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_MATCH_ROOM_TYPE_ERROR)			// 匹配时房间类型错误
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_MATCH_ROOM_OWNER_QUIT)			// 匹配时房主退出

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(ROOM, CROSS_ROOM, 7)
		CL_DEFINE_ERRORCODE(ROOM_SYSTEM_CROSS_ROOM_WAIT)				// 房间跨服


		CL_FUNCTION_ERRORCODE_END(ROOM)

		CL_FUNCTION_ERRORCODE_BEGIN(VERIFY)
		CL_DEFINE_ERRORCODE(VERIFY_BUSY)							// 验证服务器太忙
		CL_DEFINE_ERRORCODE(VERIFY_REPEAT)							// 重复创建
		CL_DEFINE_ERRORCODE(VERIFY_INIT_FAILED)						// 初始化失败，这里可能是因为白名单

		CL_FUNCTION_ERRORCODE_BEGIN(SCORE_WAR)
		CL_DEFINE_ERRORCODE(SCORE_WAR_REWARD_NOT_EXIST)				// 奖励不存在
		CL_DEFINE_ERRORCODE(SCORE_WAR_REWARD_GIVE)					// 奖励已经领取
		CL_DEFINE_ERRORCODE(SCORE_WAR_REWARD_BATTLE_COUNT_ERROR)	// 战斗次数不足
		CL_DEFINE_ERRORCODE(SCORE_WAR_REWARD_WIN_COUNT_ERROR)		// 战斗胜利次数不足
		CL_DEFINE_ERRORCODE(SCORE_WAR_STATUS_END)					// 活动已经结束

		CL_FUNCTION_ERRORCODE_BEGIN(DIG)
		CL_DEFINE_ERRORCODE(DIG_MAP_PLAYER_NOT_EXIST)	// 玩家不存在
		CL_DEFINE_ERRORCODE(DIG_MAP_NOT_EXIST)			// 地图不存在
		CL_DEFINE_ERRORCODE(DIG_NOT_EXIST)				// 挖宝点不存在
		CL_DEFINE_ERRORCODE(DIG_TYPE_ERROR)				// 挖宝点类型错误
		CL_DEFINE_ERRORCODE(DIG_RANDOM_ERROR)			// 随机出错
		CL_DEFINE_ERRORCODE(DIG_STATUS_ERROR)			// 挖宝点状态错误
		CL_DEFINE_ERRORCODE(DIG_OPEN_TRANSACTION)		// 挖宝事务中
		CL_DEFINE_ERRORCODE(DIG_OPEN_ITEM)				// 挖宝道具不足

		//赌马错误码
		CL_FUNCTION_ERRORCODE_BEGIN(BET_HORSE)
		CL_DEFINE_ERRORCODE(BET_HORSE_NOT_STAKE_PHASE)				// 不在押注阶段
		CL_DEFINE_ERRORCODE(BET_HORSE_STAKE_MAX)					// 押注数量达到上限
		CL_DEFINE_ERRORCODE(BET_HORSE_STAKE_FAILED)					// 押注失败
		CL_DEFINE_ERRORCODE(BET_HORSE_SHOOTER_NOT_JOIN)				// 射手未参赛
		CL_FUNCTION_ERRORCODE_END(BET_HORSE)


		//安全锁
		CL_FUNCTION_ERRORCODE_BEGIN(SECURITY_LOCK)
		CL_DEFINE_ERRORCODE(SECURITY_LOCK_FAILED)		// 安全锁操作失败
		CL_DEFINE_ERRORCODE(SECURITY_LOCK_PASSWD_ERROR)	// 安全锁解锁密码错误
		CL_DEFINE_ERRORCODE(BIND_DEVICE_MAX)			// 绑定设备数量达上限
		CL_DEFINE_ERRORCODE(SECURITY_LOCK_FORBID_OP)	// 安全锁禁止操作
		CL_DEFINE_ERRORCODE(SECURITY_LOCK_DEL_ROLE)		// 删除角色安全锁锁住
		CL_DEFINE_ERRORCODE(SECURITY_LOCK_PASSWD_ERROR_MAX_NUM)	//密码错误次数达到最大
		CL_DEFINE_ERRORCODE(SECURITY_LOCK_CHANGE_PASSWD_ERROR)	//安全锁修改密码错误
		CL_DEFINE_ERRORCODE(SECURITY_LOCK_PASSWD_LENGTH_ERROR)	//安全锁密码长度错误
		CL_DEFINE_ERRORCODE(SECURITY_LOCK_FORCE_UNLOCK)			//正在强制解锁
		CL_FUNCTION_ERRORCODE_END(SECURITY_LOCK)		

		//冒险队
		CL_FUNCTION_ERRORCODE_BEGIN(ADVENTURE_TEAM)
		CL_DEFINE_ERRORCODE(ADVENTURE_TEAM_NAME_INVALID)		//冒险队队名非法
		CL_DEFINE_ERRORCODE(ADVENTURE_TEAM_NAME_SAME)			//冒险队队名相同
		CL_DEFINE_ERRORCODE(ADVENTURE_TEAM_NAME_EXIST)			//冒险队队名已存在
		CL_DEFINE_ERRORCODE(ADVENTURE_TEAM_RENAME_FAILED)		//冒险队改名失败
		CL_DEFINE_ERRORCODE(BLESS_CRYSTAL_NOT_ENOUGH)			//赐福水晶不足
		CL_DEFINE_ERRORCODE(INHERIT_BLESS_USE_ERROR)			//传承祝福使用错误
		CL_DEFINE_ERRORCODE(EXPEDITION_MAP_ERROR)				//远征地图错误
		CL_DEFINE_ERRORCODE(EXPEDITION_ROLE_LEVEL_ERR)			//远征角色等级限制
		CL_DEFINE_ERRORCODE(ADVENTURE_TEAM_LEVEL_LIMIT)			//冒险队等级限制
		CL_DEFINE_ERRORCODE(EXPEDITION_MEMBER_NUM_ERR)			//远征队成员数错误
		CL_DEFINE_ERRORCODE(EXPEDITION_DURATION_ERROR)			//远征时间错误
		CL_DEFINE_ERRORCODE(EXPEDITION_TEAM_DISPATCH_FAILED)	//派遣远征队失败
		CL_DEFINE_ERRORCODE(EXPEDITION_TEAM_MEMBER_INEXISTENCE)	//远征队成员不存在
		CL_DEFINE_ERRORCODE(EXPEDITION_CANCEL_FAILED)			//取消远征失败
		CL_DEFINE_ERRORCODE(EXPEDITION_INEXISTENCE)				//不存在远征
		CL_DEFINE_ERRORCODE(EXPEDITION_STILL_PROCESS)			//远征还在进行中
		CL_DEFINE_ERRORCODE(EXPEDITION_TAKE_REWARD_FAILED)		//领取远征奖励失败
		CL_FUNCTION_ERRORCODE_END(ADVENTURE_TEAM)

		//黑市商人
		CL_FUNCTION_ERRORCODE_BEGIN(BLACK_MARKET)
		CL_DEFINE_ERRORCODE(BLACK_MARKET_OVERED)				//活动已经结束
		CL_DEFINE_ERRORCODE(BLACK_MARKET_TRANS_REQ_FAIL)		//申请交易失败
		CL_DEFINE_ERRORCODE(BLACK_MARKET_TRANS_CANCEL_FAIL)		//取消交易失败
		CL_DEFINE_ERRORCODE(BLACK_MARKET_TRANS_REQ_FAIL_PRICE)	//申请交易价格不在有效范围
		CL_DEFINE_ERRORCODE(BLACK_MARKET_PLAYE_LV_FAIL)			//玩家等级不够
		CL_FUNCTION_ERRORCODE_END(BLACK_MARKET)

		//吃鸡
		CL_FUNCTION_ERRORCODE_BEGIN(BATTLE)
		CL_DEFINE_ERRORCODE(BATTLE_NOT_ENROLL)				//吃鸡没有报名
		CL_DEFINE_ERRORCODE(BATTLE_TARGET_FAILED)			//操作目标失败
		CL_DEFINE_ERRORCODE(BATTLE_TARGET_INVINCIBLE)		//操作目标无敌
		CL_DEFINE_ERRORCODE(BATTLE_TARGET_PKING)			//操作目标pk中
		CL_DEFINE_ERRORCODE(BATTLE_SELF_INVINCIBLE)			//操作自己无敌
		CL_DEFINE_ERRORCODE(BATTLE_SELF_PKING)				//操作自己pk中
		CL_DEFINE_ERRORCODE(BATTLE_RETURN_TOWN)				//返回城镇
		CL_DEFINE_ERRORCODE(BATTLE_NPC_NO_FIND)				//没有该npc
		CL_DEFINE_ERRORCODE(BATTLE_NPC_TRADER_FAILED)		//npc兑换失败
		CL_DEFINE_ERRORCODE(BATTLE_BLOOD_NOT_ENOUGH)		//血量不足
		CL_DEFINE_ERRORCODE(BATTLE_EQUIP_NOT_ENOUGH)		//装备不足
		CL_DEFINE_ERRORCODE(BATTLE_NO_WAR_CD)				//免战CD
		CL_DEFINE_ERRORCODE(BATTLE_NO_WAR_CHOICE)			//免战选择中

		CL_SUB_FUNCTION_ERRORCODE_BEGIN(BATTLE, BATTE_CREATE_SCENE, 1)
		CL_DEFINE_ERRORCODE(BATTLE_CREATE_SCENE_FAILED)		//系统错误
		CL_FUNCTION_ERRORCODE_END(BATTLE)
		
		//头衔
		CL_FUNCTION_ERRORCODE_BEGIN(NEW_TITLE)
		CL_DEFINE_ERRORCODE(NEW_TITLE_TAKE_UP_FAIL)				//穿戴失败
		CL_DEFINE_ERRORCODE(NEW_TITLE_TAKE_OFF_FAIL)			//脱掉失败
		CL_DEFINE_ERRORCODE(NEW_TITLE_TAKE_SCENE_FORBID)		//当前场景无法更改头衔
		CL_FUNCTION_ERRORCODE_END(NEW_TITLE)

		// 运营活动
		CL_FUNCTION_ERRORCODE_BEGIN(OPERATE)
		CL_DEFINE_ERRORCODE(OPERATE_DATA_ERROR)				//活动数据错误
		CL_DEFINE_ERRORCODE(OPERATE_GET_REWARD_REPEATED)	//活动奖励重复领取
		CL_DEFINE_ERRORCODE(OPERATE_GET_REWARD_ERROR)		//活动奖励错误
		CL_DEFINE_ERRORCODE(OPERATE_NOT_FINISH)				//活动未完成
		CL_DEFINE_ERRORCODE(OPERATE_ACTIVITY_CLOSE)			//活动已结束
		CL_DEFINE_ERRORCODE(OPERATE_PLANT_SEED_NOTIFF)		//植树活动粽子不足
		CL_DEFINE_ERRORCODE(OPERATE_PLANT_FAIL)				//植树活动种树失败
		CL_DEFINE_ERRORCODE(OPERATE_PLANT_APPR_FAIL)		//植树活动鉴定失败
		CL_DEFINE_ERRORCODE(OPERATE_PLANT_FAIL_ALLGET)		//植树失败,都已经获得了
			CL_FUNCTION_ERRORCODE_END(OPERATE)
		
		//自然月签到
		CL_FUNCTION_ERRORCODE_BEGIN(NEW_SIGN)
		CL_DEFINE_ERRORCODE(ALREADY_SIGN)                   //已经签到了
		CL_DEFINE_ERRORCODE(REACH_LIMIT)                    //已达到当月补签上限
		CL_DEFINE_ERRORCODE(NOT_ENOUGH_STUFF)               //补签材料不足
		CL_DEFINE_ERRORCODE(ALREADY_COLLECT)                //累计签到奖励已领取
		CL_DEFINE_ERRORCODE(NOT_ENOUGH_DAYS)                //累计签到天数不够

		// 团本
		CL_FUNCTION_ERRORCODE_BEGIN(TEAM_COPY)
		CL_DEFINE_ERRORCODE(TEAM_COPY_DATA_ERROR)			//数据错误
		CL_DEFINE_ERRORCODE(TEAM_COPY_NO_EXIST_TEAM)		//找不到队伍
		CL_DEFINE_ERRORCODE(TEAM_COPY_NO_POWER)				//没有权限
		CL_DEFINE_ERRORCODE(TEAM_COPY_MEMBER_NOT_ENOUGH)	//人数不足
		CL_DEFINE_ERRORCODE(TEAM_COPY_GRADE_VALID)			//难度无效
		CL_DEFINE_ERRORCODE(TEAM_COPY_IN_BATTLE)			//战斗中
		CL_DEFINE_ERRORCODE(TEAM_COPY_BATTLE_PLAN)			//战斗配置错误
		CL_DEFINE_ERRORCODE(TEAM_COPY_NOT_APPLY)			//没有申请
		CL_DEFINE_ERRORCODE(TEAM_COPY_TEAM_FULL)			//队伍满员
		CL_DEFINE_ERRORCODE(TEAM_COPY_ONE_GOLD_FULL)		//团本一金主已满
		CL_DEFINE_ERRORCODE(TEAM_COPY_SQUAD_INVALID)		//小队无效
		CL_DEFINE_ERRORCODE(TEAM_COPY_FIELD_UNLOCK)			//据点未解锁
		CL_DEFINE_ERRORCODE(TEAM_COPY_YET_FLOP)				//已经翻牌了
		CL_DEFINE_ERRORCODE(TEAM_COPY_APPLY_LIST_FULL)		//申请列表满

		CL_DEFINE_ERRORCODE(TEAM_COPY_COUNT_NOT_ENOUGH)		//挑战次数不足
		CL_DEFINE_ERRORCODE(TEAM_COPY_TICKET_NOT_ENOUGH)	//门票不足
		CL_DEFINE_ERRORCODE(TEAM_COPY_COMMISSION_NOT_ENOUGH)//佣金不足
		CL_DEFINE_ERRORCODE(TEAM_COPY_PLAYER_UNKNOWN_ERROR) //玩家未知错误

		CL_DEFINE_ERRORCODE(TEAM_COPY_GAME_OVER)			//游戏结束
		CL_DEFINE_ERRORCODE(TEAM_COPY_NOT_FIND_TARGET)		//找不到目标
		CL_DEFINE_ERRORCODE(TEAM_COPY_BOSS_FIELD)			//boss据点，有队伍正在挑战
		CL_DEFINE_ERRORCODE(TEAM_COPY_MEMBER_LEAVE)			//有队员离开
		CL_DEFINE_ERRORCODE(TEAM_COPY_VOTE_PROCESS)			//正在投票
		CL_DEFINE_ERRORCODE(TEAM_COPY_FIELD_DEFEAT)			//据点被歼灭
		CL_DEFINE_ERRORCODE(TEAM_COPY_FIELD_REBORN)			//据点重生中
		CL_DEFINE_ERRORCODE(TEAM_COPY_NOT_GOLD_TEAM)		//不是金团
		CL_DEFINE_ERRORCODE(TEAM_COPY_GOLD_NUM_NOT_ENOUGH)	//金主数量不足

		CL_DEFINE_ERRORCODE(TEAM_COPY_SQUAD_IN_BATTLE)		//小队队员战斗中
		CL_DEFINE_ERRORCODE(TEAM_COPY_EQUIP_SCORE_NOT_ENOUGH)//装备评分不足
		CL_DEFINE_ERRORCODE(TEAM_COPY_TEAM_DISMISS)			//队伍已经解散了
		CL_DEFINE_ERRORCODE(TEAM_COPY_NO_INVITE)			//没有邀请
		CL_DEFINE_ERRORCODE(TEAM_COPY_HAS_TEAM)				//已经有队伍了
		CL_DEFINE_ERRORCODE(TEAM_COPY_COND_LIMIT_NOT_CREATE)//不符合创建条件
		CL_DEFINE_ERRORCODE(TEAM_COPY_NUM_LIMIT)	//日或周挑战次数达上限
		CL_DEFINE_ERRORCODE(TEAM_COPY_NUM_LIMIT_NOT_APPLY)	//暂时无用
		CL_DEFINE_ERRORCODE(TEAM_COPY_FLOP_LIMIT)			//该阶段的翻牌次数达上限
		CL_DEFINE_ERRORCODE(TEAM_COPY_TEAM_MATE_LOADING)	//队友还在加载
		CL_DEFINE_ERRORCODE(TEAM_COPY_TARGET_CUR_STATUS)	//目标当前状态无法加入团队
		CL_DEFINE_ERRORCODE(TEAM_COPY_JOIN_TIME_LIMIT)		//加入时间限制
		CL_DEFINE_ERRORCODE(TEAM_COPY_IN_BATTLE_NOT_INVITE)	//开战状态下，无法邀请其他成员加入团队
		CL_DEFINE_ERRORCODE(TEAM_COPY_GOLD_THAN_COMMON)		//金主大于普通玩家
		CL_DEFINE_ERRORCODE(TEAM_COPY_GOLD_NOT_JOIN)		//金主不可加入其它模式
		CL_DEFINE_ERRORCODE(TEAM_COPY_PLAYER_LEAVE)			//玩家离开
		CL_DEFINE_ERRORCODE(TEAM_COPY_RECRUIT_CD)			//招募CD
		CL_DEFINE_ERRORCODE(TEAM_COPY_FORCE_END_FAILED)		//强制结束条件不满足
		CL_DEFINE_ERRORCODE(TEAM_COPY_FORCE_END_CD)			//强制结束冷却中
		CL_DEFINE_ERRORCODE(TEAM_COPY_ENERGY_REVIVE)		//能量恢复中
		CL_DEFINE_ERRORCODE(TEAM_COPY_GRADE_LOCK)			//难度未解锁
		CL_DEFINE_ERRORCODE(TEAM_COPY_FUN_LOCK)				//团本未解锁

		CL_DEFINE_ERRORCODE(TEAM_COPY_GRID_MOVE_FAILED)		//移动失败
		CL_DEFINE_ERRORCODE(TEAM_COPY_NOT_FIND_GRID)		//找不到格子
		CL_DEFINE_ERRORCODE(TEAM_COPY_GRID_BLOCK)			//格子阻挡
		CL_DEFINE_ERRORCODE(TEAM_COPY_IN_TARGET_GRID)		//已在目标格子
		CL_DEFINE_ERRORCODE(TEAM_COPY_SQUAD_GRID_NOT_NEAR)	//小队位置不相邻
		CL_DEFINE_ERRORCODE(TEAM_COPY_PLAYER_NOT_IN_SCENE)	//玩家不在团本场景
		CL_DEFINE_ERRORCODE(TEAM_COPY_SQUAD_ALL_DISCONNECT)	//小队全部掉线
		CL_DEFINE_ERRORCODE(TEAM_COPY_TWO_GOLD_FULL)		//团本二金主已满
		CL_DEFINE_ERRORCODE(TEAM_COPY_CLOSE)		//团本关闭维护

		CL_FUNCTION_ERRORCODE_END(TEAM_COPY)

		// 招募
		CL_FUNCTION_ERRORCODE_BEGIN(HIRE)
		CL_DEFINE_ERRORCODE(HIRE_NO_INFO)					//未知错误
		CL_DEFINE_ERRORCODE(HIRE_ALREADY_BIND)				//已绑定别的账户
		CL_DEFINE_ERRORCODE(HIRE_IDENTIFY_ERR)				//身份错误
		CL_DEFINE_ERRORCODE(HIRE_TASK_ERR_UNFINISH)			//招募任务未完成
		CL_DEFINE_ERRORCODE(HIRE_CODE_ERROR)				//招募码错误
		CL_DEFINE_ERRORCODE(HIRE_BINDED_OTHER)				//已在别的服绑定
		CL_FUNCTION_ERRORCODE_END(HIRE)

			// 冠军赛
		CL_FUNCTION_ERRORCODE_BEGIN(CHAMPION)
		CL_DEFINE_ERRORCODE(CHAMPION_NO_INFO)					//未知错误
		CL_DEFINE_ERRORCODE(CHAMPION_STATUS_ERROR)				//当前赛程不支持该行为
		CL_DEFINE_ERRORCODE(CHAMPION_ALREADY_ENROLL)			//已经报名
		CL_DEFINE_ERRORCODE(CHAMPION_PERMISSION_DENIED)			//没有权限
		CL_DEFINE_ERRORCODE(CHAMPION_ALREADY_RELIVE)			//已使用过复活
		CL_DEFINE_ERRORCODE(CHAMPION_NO_BET)					//禁止下注
		CL_DEFINE_ERRORCODE(CHAMPION_RACE_ALREADY_END)			//比赛已经结束
		CL_DEFINE_ERRORCODE(CHAMPION_ENROLL_LEVEL)			//报名等级不足
		CL_DEFINE_ERRORCODE(CHAMPION_ENROLL_GOLD)			//报名金币不足
		CL_DEFINE_ERRORCODE(CHAMPION_ENROLL_PK)				//报名pk场次不足
		CL_DEFINE_ERRORCODE(CHAMPION_BET_ACCOUNT)			//本账号静止下注
		CL_DEFINE_ERRORCODE(CHAMPION_BET_LIMIT)			//单项押注超出上限
		CL_FUNCTION_ERRORCODE_END(CHAMPION)
			
			
		// 迷失地牢
		CL_FUNCTION_ERRORCODE_BEGIN(LOSTDUNGEON)
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_GENER_FLOOR_FAIL)	 //生成爬塔失败
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_PK_FAIL_CANT_ATTCK)	 //PK失败，你当前禁止攻击
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_PK_FAIL_TARGT_BATELING)	 //PK失败，目标战斗中
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_PK_FAIL_TARGT_PROTEDING)	 //PK失败，目标保护中
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_CREATE_RACE_FIAL)	 //创建比赛失败
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_SWITCH_SINGLE_MODE_FAIL)	 //队伍已满，切换单人模式失败,
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_SWITCH_MODE_FAIL) //切换单人模式失败
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_SWITCH_FAIL_NOTEAM) //切换组队模式失败
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_SELECT_BATTLE_FAIL) //分配战场失败
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_OPENBOX_FAIL_OPENED) //开宝箱失败，宝箱已经开过。
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_ADDTIME_FAIL_NOTITEM) //加次数失败，道具不足
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_OPEN_FAIL_NOTIMES) //开启地牢失败，次数不够
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_REWARD_FAIL_ST) //当前状态不能领取奖励
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_OPFAIL_ST) //状态错误，操作失败
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_OPENBOX_FAIL_LOCK) //开宝箱失败，楼层未解锁。
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_SEE_QIBAO_FAIK_NOITEM) //查看情报失败，没有神器
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_FAIL_ACT_CLOSE) //活动已经结束
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_CANT_ENTER_BAT_BEFEND) //活动快结束了，不能进入战场了
			CL_DEFINE_ERRORCODE(LOSTDUNGEON_PK_FAIL_TARGT_LEAVING) //PK失败，目标离开战场中
		CL_FUNCTION_ERRORCODE_END(LOSTDUNGEON)
			
		CL_FUNCTION_ERRORCODE_BEGIN(GOLD_CONSIGNMENT)
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_NOT_EXIST_ORDER) // 没有该订单
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_ORDER_NUM_FULL) // 订单数量多
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_ORDER_BEING_PROCESS) // 订单正在处理
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_ORDER_TIME_OUT) // 订单超时
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_ORDER_NOT_MATCH) // 订单不匹配
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_NOT_ENOUGH_GOODS) // 没有足够的货源
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_OVER_WAVE_PRICE) // 超过涨幅价
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_OVER_PROTECT_PRICE) // 超过保护价
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_OVER_ACC_PROFIT_LIMIT) // 超过账号预期收益限制
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_OVER_ACC_MONTH_GET_LIMIT) // 超过账号月获得上限
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_OVER_ACC_HOLD_LIMIT) // 超过账号拥有上限
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_TRADE_NUM_ERROR) // 交易数量错误
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_SERVER_BUSY) // 服务器忙
		CL_DEFINE_ERRORCODE(GOLD_CONSIGNMENT_CLOSE_TRADE) // 休市中

		CL_FUNCTION_ERRORCODE_END(GOLD_CONSIGNMENT)

		// 道具事务
		CL_FUNCTION_ERRORCODE_BEGIN(ITEM_THING)
		CL_DEFINE_ERRORCODE(ITEM_THING_POINT_NOT_ENOUGH) // 点券不足
		CL_DEFINE_ERRORCODE(ITEM_THING_GOLD_NOT_ENOUGH) // 金币不足
		CL_DEFINE_ERRORCODE(ITEM_THING_NOT_FIND) // 事务找不到
		CL_FUNCTION_ERRORCODE_END(ITEM_THING)

	CL_ERRORCODE_END()
}


#endif
