#ifndef _CL_MONEY_MANAGE_DEFINE_H_
#define _CL_MONEY_MANAGE_DEFINE_H_

#define MONEY_MANAGE_REWARD_SIZE 64

#define MONEY_MANAGE_OLD_CHARGE_ID 4
#define MONEY_MANAGE_NOW_CHARGE_ID 10

enum MoneyManageStatus
{
	MMS_NOT_BUY = 0,
	MMS_ACCOUNT_BUY = 1,
	MMS_PLAYER_BUY = 2,
	MMS_NEW_PLAYER_BUY = 3,
};


#endif //_CL_MONEY_MANAGE_DEFINE_H_