#ifndef _CL_SORTLIST_DEFINE_H_
#define _CL_SORTLIST_DEFINE_H_

#include "CLDefine.h"
#include "CLItemTypeDefine.h"
#include "CLJobDataEntry.h"

/**
 *@brief 排行榜类型
 *	新增类型需要修改序列化 和 排序因子获取
 */
enum SortListType
{
	SORTLIST_INVALID = 0,
	SORTLIST_POWER = 1,					//战斗力
	SORTLIST_LEVEL = 2,					//等级排行榜  等级总榜，不分职业
	SORTLIST_WEAPON = 3,				//武器排行榜  武器总榜，不分子类别
	SORTLIST_PET = 4,					//宠物评分榜
	SORTLIST_NEW_SERVER_LEVEL = 5,		//新服等级排行榜	//modified by yangwenhao
	SORTLIST_SCORE_WAR = 6,				//积分赛排行榜
	SORTLIST_CHALLENGE_DAILY = 7,		//挑战赛今日积分排行榜
	SORTLIST_NEW_YEAR_RED_PACKET = 8,	//新年红包排行榜
	//TODO
	SORTLIST_PET_LEVEL = 9,				//宠物等级排行榜
	SORTLIST_PET_GROWTH = 10,			//宠物成长排行榜
	SORTLIST_PET_APTITUDE = 11,			//宠物资质排行榜
	//TODO
	SORTLIST_PET_SKILL = 13,			//宠物技能排行榜
	//TODO
	SORTLIST_FESTIVAL = 15,				//节日活动排行榜
	//TODO
	SORTLIST_ACHIEVEMENT_SCORE = 16,	//成就点排行榜
	//TODO
	SORTLIST_ADVENTURE_TEAM_GRADE = 17, //冒险队(佣兵团)评级排行榜

	SORTLIST_GIVE_FLOWER = 21,			//送花榜
	SORTLIST_GET_FLOWER = 22,			//护花榜
	SORTLIST_EQUIP_POWER = 23,			//装备战斗力排行榜
	//TODO
	SORTLIST_ACTIVITYCONSUME = 25,		//活动消费全服
	SORTLIST_ACTIVITYCONSUME1 = 26,		//活动消费本服
	SORTLIST_DAY_CONSUME = 27,			//每日消费金贝


	// 上面都是原来的排行榜
	// 这些是我们自己的排行榜
	// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	// 死亡之塔排行榜
	SORTLIST_TOWER_1 = 30,           // 死亡之塔1
	SORTLIST_TOWER_2 = 31,           // 死亡之塔2
	SORTLIST_TOWER_3 = 32,           // 死亡之塔3
	SORTLIST_TOWER_4 = 33,           // 死亡之塔4

	// 赏金联赛
	SORTLIST_PREMIUM_LEAGUE = 35,	// 赏金联赛

	// 赛季匹配
	SORTLIST_1V1_SEASON = 40,			// 1V1赛季

	SORTLIST_GUILD_BATTLE_SCORE = 41,			// 公会战积分排行
	SORTLIST_GUILD_BATTLE_MEMBER = 42,			//公会战成员积分
	SORTLIST_GUILD_MEMBER_SCORE = 43,			//公会战成员积分

	SORTLIST_GUILD_LEVEL = 44,					//公会等级排行
	SORTLIST_GUILD_BATTLE_WEEK_SCORE = 45,		//公会战周积分排名

	//职业等级榜  职业包括：狂战士、漫游枪手(男)、枪炮师、漫游枪手(女)、召唤师
	SORTLIST_LEVEL_OCCU_GUIJIANSHI = 50,		//鬼剑士
	SORTLIST_LEVEL_OCCU_JIANHUN,
	SORTLIST_LEVEL_OCCU_KUANGZHANSHI,				//狂战士
	SORTLIST_LEVEL_OCCU_GUIQI,
	SORTLIST_LEVEL_OCCU_AXIULUO,					//阿修罗

	SORTLIST_LEVEL_OCCU_SHENQIANGSHOU = 55,	//神枪手男
	SORTLIST_LEVEL_OCCU_MANYOU,				//漫游男
	SORTLIST_LEVEL_OCCU_QIANGPAOSHI,
	SORTLIST_LEVEL_OCCU_JIXIESHI,
	SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA,

	SORTLIST_LEVEL_OCCU_MOFASHI = 60,		//魔法师
	SORTLIST_LEVEL_OCCU_YUANSUSHI,
	SORTLIST_LEVEL_OCCU_ZHANDOUFASHI,
	SORTLIST_LEVEL_OCCU_ZHAOHUANSHI,		//召唤师

	SORTLIST_LEVEL_OCCU_GEDOUJIA = 70,		//格斗家
	SORTLIST_LEVEL_OCCU_QIGONGSHI,
	SORTLIST_LEVEL_OCCU_SANDA,
	SORTLIST_LEVEL_OCCU_JIEBA,
	SORTLIST_LEVEL_OCCU_ROUDAOJIA,

	SORTLIST_LEVEL_OCCU_SHENQIANGSHOU_NV = 75,		//神枪手女
	SORTLIST_LEVEL_OCCU_MANYOU_NV,					//漫游枪手女
	SORTLIST_LEVEL_OCCU_QIANGPAOSHI_NV,
	SORTLIST_LEVEL_OCCU_JIXIESHI_NV,
	SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA_NV,

	//武器子类型排行榜  (巨剑、太刀、左轮、手炮、魔杖、法杖)
	SORTLIST_WEAPON_TT_ITEM_HUGESWORD = 80,				//武器-巨剑
	SORTLIST_WEAPON_TT_ITEM_KATANA,						//武器-太刀
	SORTLIST_WEAPON_TT_ITEM_REVOLVER,					//武器-左轮
	SORTLIST_WEAPON_TT_ITEM_HANDCANNON,					//武器-手炮
	SORTLIST_WEAPON_TT_ITEM_WAND,						//武器-魔杖
	SORTLIST_WEAPON_TT_ITEM_STAFF,						//武器-法杖
	SORTLIST_WEAPON_TT_ITEM_SHORT_SWORD,				//武器-短剑
	SORTLIST_WEAPON_TT_ITEM_GLOVE,						//武器-手套
	SORTLIST_WEAPON_TT_ITEM_BIKAI,						//武器-臂铠
	SORTLIST_WEAPON_TT_ITEM_CLAW,						//武器-爪
	SORTLIST_WEAPON_TT_ITEM_OFG,						//武器-拳套
	SORTLIST_WEAPON_TT_ITEM_EAST_STICK,					//武器-东方棍
	SORTLIST_WEAPON_TT_ITEM_CROSSBOW,					//武器-弩
	SORTLIST_WEAPON_TT_ITEM_RIFLE,						//武器-步枪
	SORTLIST_WEAPON_TT_ITEM_BEAMSWORD,					//武器-光剑
	SORTLIST_WEAPON_TT_ITEM_SICKLE,						//武器-镰刀
	SORTLIST_WEAPON_TT_ITEM_TOTEM,						//武器-图腾
	SORTLIST_WEAPON_TT_ITEM_AXE,						//武器-战斧
	SORTLIST_WEAPON_TT_ITEM_BEADS,						//武器-念珠
	SORTLIST_WEAPON_TT_ITEM_CROSS,						//武器-十字架

	// 新的武器排行榜，之前的枚举到头了
	SORTLIST_WEAPON_TT_ITEM_SPEAR = 200,				//武器-矛
	SORTLIST_WEAPON_TT_ITEM_STICK,						//武器-棍

	//勇者之塔榜  职业包括：狂战士、漫游枪手(男)、枪炮师、漫游枪手(女)、召唤师
	SORTLIST_TOWER_OCCU_GUIJIANSHI = 100,
	SORTLIST_TOWER_OCCU_JIANHUN,
	SORTLIST_TOWER_OCCU_KUANGZHANSHI,				//狂战士
	SORTLIST_TOWER_OCCU_GUIQI,
	SORTLIST_TOWER_OCCU_AXIULUO,					//阿修罗

	SORTLIST_TOWER_OCCU_SHENQIANGSHOU = 105,	//神枪手男
	SORTLIST_TOWER_OCCU_MANYOU,					//漫游男
	SORTLIST_TOWER_OCCU_QIANGPAOSHI,
	SORTLIST_TOWER_OCCU_JIXIESHI,
	SORTLIST_TOWER_OCCU_DANYAOZHUANJIA,			//武器专家

	SORTLIST_TOWER_OCCU_MOFASHI = 110,		//魔法师
	SORTLIST_TOWER_OCCU_YUANSUSHI,
	SORTLIST_TOWER_OCCU_ZHANDOUFASHI,
	SORTLIST_TOWER_OCCU_ZHAOHUANSHI,		//召唤师

	SORTLIST_TOWER_OCCU_GEDOUJIA = 120,		//格斗家
	SORTLIST_TOWER_OCCU_QIGONGSHI,
	SORTLIST_TOWER_OCCU_SANDA,
	SORTLIST_TOWER_OCCU_JIEBA,
	SORTLIST_TOWER_OCCU_ROUDAOJIA,


	SORTLIST_TOWER_OCCU_SHENQIANGSHOU_NV = 125,		//神枪手女
	SORTLIST_TOWER_OCCU_MANYOU_NV,					//漫游枪手女
	SORTLIST_TOWER_OCCU_QIANGPAOSHI_NV,
	SORTLIST_TOWER_OCCU_JIXIESHI_NV,
	SORTLIST_TOWER_OCCU_DANYAOZHUANJIA_NV,

	SORTLIST_TOWER_OCCU_SHENGZHIZHE = 135,					//圣职者
	SORTLIST_TOWER_OCCU_QUMO = 136,							//驱魔
	SORTLIST_TOWER_OCCU_SHENGQISHI = 137,							//圣骑士

	//赛季榜  职业包括：狂战士、漫游枪手(男)、枪炮师、漫游枪手(女)、召唤师
	SORTLIST_1V1_SEASON_OCCU_GUIJIANSHI = 140,
	SORTLIST_1V1_SEASON_OCCU_JIANHUN,
	SORTLIST_1V1_SEASON_OCCU_KUANGZHANSHI,				//狂战士
	SORTLIST_1V1_SEASON_OCCU_GUIQI,
	SORTLIST_1V1_SEASON_OCCU_AXIULUO,					//阿修罗

	SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU = 145,	//神枪手男
	SORTLIST_1V1_SEASON_OCCU_MANYOU,					//漫游男
	SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI,
	SORTLIST_1V1_SEASON_OCCU_JIXIESHI,
	SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA,

	SORTLIST_1V1_SEASON_OCCU_MOFASHI = 150,		//魔法师
	SORTLIST_1V1_SEASON_OCCU_YUANSUSHI,
	SORTLIST_1V1_SEASON_OCCU_ZHANDOUFASHI,
	SORTLIST_1V1_SEASON_OCCU_ZHAOHUANSHI,		//召唤师

	SORTLIST_1V1_SEASON_OCCU_GEDOUJIA = 160,		//格斗家
	SORTLIST_1V1_SEASON_OCCU_QIGONGSHI,
	SORTLIST_1V1_SEASON_OCCU_SANDA,
	SORTLIST_1V1_SEASON_OCCU_JIEBA,
	SORTLIST_1V1_SEASON_OCCU_ROUDAOJIA,

	SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU_NV = 165,		//神枪手女
	SORTLIST_1V1_SEASON_OCCU_MANYOU_NV,					//漫游枪手女
	SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI_NV,
	SORTLIST_1V1_SEASON_OCCU_JIXIESHI_NV,
	SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA_NV,

	SORTLIST_1V1_SEASON_OCCU_SHENGZHIZHE = 175,					//圣职者
	SORTLIST_1V1_SEASON_OCCU_QUMO = 176,						//驱魔
	SORTLIST_1V1_SEASON_OCCU_SHENGQISHI = 177,					//圣骑士


	SORTLIST_LEVEL_OCCU_JIANDOUSHI = 190,					//剑斗士 //等级

	SORTLIST_LEVEL_OCCU_SHENGZHIZHE = 195,					//圣职者 等级
	SORTLIST_LEVEL_OCCU_QUMO = 196,							//驱魔
	SORTLIST_LEVEL_OCCU_SHENGQISHI = 197,					//圣骑士

	SORTLIST_CHIJI_SCORE = 250,						//吃鸡积分

	// 200-210武器排行榜

	SORTLIST_2V2_SCORE_WAR = 251,				//积分赛排行榜

	SORTLIST_MAX,
};

/**
 *@brief 根据类型获取排行榜上限
		 返回0说明所有数据都需要保存
 */
inline UInt32 GetSortListSize(int type)
{
	switch (type)
	{
	case SORTLIST_NEW_YEAR_RED_PACKET:
		return 50;
	case SORTLIST_NEW_SERVER_LEVEL:
	case SORTLIST_LEVEL:
	case SORTLIST_PET:
	case SORTLIST_PET_LEVEL:
	case SORTLIST_PET_GROWTH:
	case SORTLIST_PET_APTITUDE:
	case SORTLIST_PET_SKILL:
	case SORTLIST_ADVENTURE_TEAM_GRADE:
	case SORTLIST_GET_FLOWER:
	case SORTLIST_GIVE_FLOWER:
	case SORTLIST_ACHIEVEMENT_SCORE:			//成就积分
	case SORTLIST_TOWER_1:
	case SORTLIST_TOWER_2:
	case SORTLIST_TOWER_3:
	case SORTLIST_TOWER_4:
	case SORTLIST_TOWER_OCCU_GUIJIANSHI:
	case SORTLIST_TOWER_OCCU_JIANHUN:
	case SORTLIST_TOWER_OCCU_KUANGZHANSHI:
	case SORTLIST_TOWER_OCCU_GUIQI:
	case SORTLIST_TOWER_OCCU_AXIULUO:
	case SORTLIST_TOWER_OCCU_SHENQIANGSHOU:
	case SORTLIST_TOWER_OCCU_MANYOU:
	case SORTLIST_TOWER_OCCU_QIANGPAOSHI:
	case SORTLIST_TOWER_OCCU_JIXIESHI:
	case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA:
	case SORTLIST_TOWER_OCCU_MOFASHI:
	case SORTLIST_TOWER_OCCU_YUANSUSHI:
	case SORTLIST_TOWER_OCCU_ZHANDOUFASHI:
	case SORTLIST_TOWER_OCCU_ZHAOHUANSHI:
	case SORTLIST_TOWER_OCCU_GEDOUJIA:
	case SORTLIST_TOWER_OCCU_QIGONGSHI:
	case SORTLIST_TOWER_OCCU_SANDA:
	case SORTLIST_TOWER_OCCU_JIEBA:
	case SORTLIST_TOWER_OCCU_ROUDAOJIA:
	case SORTLIST_TOWER_OCCU_SHENQIANGSHOU_NV:
	case SORTLIST_TOWER_OCCU_MANYOU_NV:
	case SORTLIST_TOWER_OCCU_QIANGPAOSHI_NV:
	case SORTLIST_TOWER_OCCU_JIXIESHI_NV:
	case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA_NV:
	case SORTLIST_TOWER_OCCU_SHENGZHIZHE:
	case SORTLIST_TOWER_OCCU_QUMO:
	case SORTLIST_TOWER_OCCU_SHENGQISHI:

	//added by aprilliu, 2017.04.21
	case SORTLIST_LEVEL_OCCU_GUIJIANSHI:			//鬼剑士
	case SORTLIST_LEVEL_OCCU_JIANHUN:
	case SORTLIST_LEVEL_OCCU_KUANGZHANSHI:				//狂战士
	case SORTLIST_LEVEL_OCCU_GUIQI:
	case SORTLIST_LEVEL_OCCU_AXIULUO:
	case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU:				//神枪手男
	case SORTLIST_LEVEL_OCCU_MANYOU: 					//漫游男
	case SORTLIST_LEVEL_OCCU_QIANGPAOSHI:
	case SORTLIST_LEVEL_OCCU_JIXIESHI:
	case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA:
	case SORTLIST_LEVEL_OCCU_MOFASHI:		//魔法师
	case SORTLIST_LEVEL_OCCU_YUANSUSHI:
	case SORTLIST_LEVEL_OCCU_ZHANDOUFASHI:
	case SORTLIST_LEVEL_OCCU_ZHAOHUANSHI:		//召唤师
	case SORTLIST_LEVEL_OCCU_GEDOUJIA: 	//格斗家
	case SORTLIST_LEVEL_OCCU_QIGONGSHI:
	case SORTLIST_LEVEL_OCCU_SANDA:
	case SORTLIST_LEVEL_OCCU_JIEBA:
	case SORTLIST_LEVEL_OCCU_ROUDAOJIA:
	case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU_NV:			//神枪手女
	case SORTLIST_LEVEL_OCCU_MANYOU_NV:					//漫游枪手女
	case SORTLIST_LEVEL_OCCU_QIANGPAOSHI_NV:
	case SORTLIST_LEVEL_OCCU_JIXIESHI_NV:
	case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA_NV:
	case SORTLIST_LEVEL_OCCU_SHENGZHIZHE:
	case SORTLIST_LEVEL_OCCU_QUMO:
	case SORTLIST_LEVEL_OCCU_SHENGQISHI:

	case SORTLIST_WEAPON_TT_ITEM_HUGESWORD:					//武器-巨剑
	case SORTLIST_WEAPON_TT_ITEM_KATANA:						//武器-太刀
	case SORTLIST_WEAPON_TT_ITEM_REVOLVER:					//武器-左轮
	case SORTLIST_WEAPON_TT_ITEM_HANDCANNON:					//武器-手炮
	case SORTLIST_WEAPON_TT_ITEM_WAND:						//武器-魔杖
	case SORTLIST_WEAPON_TT_ITEM_STAFF:						//武器-法杖
	case SORTLIST_WEAPON_TT_ITEM_SHORT_SWORD:				//武器-短剑
	case SORTLIST_WEAPON_TT_ITEM_GLOVE:						//武器-手套
	case SORTLIST_WEAPON_TT_ITEM_BIKAI:						//武器-臂铠
	case SORTLIST_WEAPON_TT_ITEM_CLAW:						//武器-爪
	case SORTLIST_WEAPON_TT_ITEM_OFG:						//武器-拳套
	case SORTLIST_WEAPON_TT_ITEM_EAST_STICK:				//武器-东方棍
	case SORTLIST_WEAPON_TT_ITEM_CROSSBOW:					//武器-弩
	case SORTLIST_WEAPON_TT_ITEM_RIFLE:						//武器-步枪
	case SORTLIST_WEAPON_TT_ITEM_BEAMSWORD:					//武器-光剑
	case SORTLIST_WEAPON_TT_ITEM_SICKLE:					//武器-镰刀
	case SORTLIST_WEAPON_TT_ITEM_TOTEM:						//武器-图腾
	case SORTLIST_WEAPON_TT_ITEM_AXE:						//武器-战斧
	case SORTLIST_WEAPON_TT_ITEM_BEADS:						//武器-念珠
	case SORTLIST_WEAPON_TT_ITEM_CROSS:						//武器-十字架
	case SORTLIST_WEAPON_TT_ITEM_SPEAR:						//武器-矛
	case SORTLIST_WEAPON_TT_ITEM_STICK:						//武器-棍
	//end of aprilliu

	case SORTLIST_1V1_SEASON:
	case SORTLIST_1V1_SEASON_OCCU_GUIJIANSHI:
	case SORTLIST_1V1_SEASON_OCCU_JIANHUN:
	case SORTLIST_1V1_SEASON_OCCU_KUANGZHANSHI:
	case SORTLIST_1V1_SEASON_OCCU_GUIQI:
	case SORTLIST_1V1_SEASON_OCCU_AXIULUO:
	case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU:
	case SORTLIST_1V1_SEASON_OCCU_MANYOU:
	case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI:
	case SORTLIST_1V1_SEASON_OCCU_JIXIESHI:
	case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA:
	case SORTLIST_1V1_SEASON_OCCU_MOFASHI:
	case SORTLIST_1V1_SEASON_OCCU_YUANSUSHI:
	case SORTLIST_1V1_SEASON_OCCU_ZHANDOUFASHI:
	case SORTLIST_1V1_SEASON_OCCU_ZHAOHUANSHI:
	case SORTLIST_1V1_SEASON_OCCU_GEDOUJIA:
	case SORTLIST_1V1_SEASON_OCCU_QIGONGSHI:
	case SORTLIST_1V1_SEASON_OCCU_SANDA:
	case SORTLIST_1V1_SEASON_OCCU_JIEBA:
	case SORTLIST_1V1_SEASON_OCCU_ROUDAOJIA:
	case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU_NV:
	case SORTLIST_1V1_SEASON_OCCU_MANYOU_NV:
	case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI_NV:
	case SORTLIST_1V1_SEASON_OCCU_JIXIESHI_NV:
	case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA_NV:
	case SORTLIST_1V1_SEASON_OCCU_SHENGZHIZHE:
	case SORTLIST_1V1_SEASON_OCCU_QUMO:
	case SORTLIST_1V1_SEASON_OCCU_SHENGQISHI:
	case SORTLIST_GUILD_LEVEL:
		return 150;
	case SORTLIST_SCORE_WAR:
		return 300;
	case SORTLIST_POWER:
	case SORTLIST_CHALLENGE_DAILY:
	case SORTLIST_EQUIP_POWER:
	case SORTLIST_DAY_CONSUME:
		return 500;
	case SORTLIST_ACTIVITYCONSUME:
		return 500;
	case SORTLIST_ACTIVITYCONSUME1:
		return 1000;
	case SORTLIST_GUILD_BATTLE_MEMBER:
	case SORTLIST_GUILD_BATTLE_SCORE:
	case SORTLIST_GUILD_MEMBER_SCORE:
		return 0;
	case SORTLIST_GUILD_BATTLE_WEEK_SCORE:
		return 20;
	}
	return 100;
}

/**
 *@brief 判断是否日清空的排行榜
 */
inline bool IsDailySortList(int type)
{
	switch(type)
	{
	case SORTLIST_CHALLENGE_DAILY:
	case SORTLIST_GET_FLOWER:
	case SORTLIST_GIVE_FLOWER:
	case SORTLIST_DAY_CONSUME:
	//case SORTLIST_TOWER_1:
	//case SORTLIST_TOWER_2:
	//case SORTLIST_TOWER_3:
	//case SORTLIST_TOWER_4:
		return true;
	}
	return false;
}

/**
 *@brief 判断是否周清空排行榜
 */
inline bool IsWeeklySortList(int type)
{
	switch (type)
	{
	case SORTLIST_GUILD_BATTLE_WEEK_SCORE:
		return true;
	}
	return false;
}

/**
*@brief 判断是否为公会战排行
*/
inline bool IsGuildBattleSortList(int type)
{
	switch (type)
	{
	case SORTLIST_GUILD_BATTLE_SCORE:
	case SORTLIST_GUILD_BATTLE_MEMBER:
	case SORTLIST_GUILD_MEMBER_SCORE:
		return true;
	}
	return false;
}

/**
*@brief 判断是否为公会排行
*/
inline bool IsGuildSortList(int type)
{
	switch (type)
	{
	case SORTLIST_GUILD_BATTLE_SCORE:
	case SORTLIST_GUILD_LEVEL:
	case SORTLIST_GUILD_BATTLE_WEEK_SCORE:
		return true;
	}
	return false;
}

/**
*@brief 判断是否为公会成员排行,根据公会
*/
inline bool IsGuildMemberSortList(int type)
{
	return type == SORTLIST_GUILD_MEMBER_SCORE;
}

/**
*@brief 判断是否为积分赛排行榜
*/
inline bool IsScoreWarSortList(int type)
{
	return type == SORTLIST_SCORE_WAR;
}


/**
*@brief 判断是否为2V2积分赛排行榜
*/
inline bool Is2V2ScoreWarSortList(int type)
{
	return type == SORTLIST_2V2_SCORE_WAR;
}


/**
*@brief 判断是否为吃鸡排行榜
*/
inline bool IsChijiSortList(int type)
{
	return type == SORTLIST_CHIJI_SCORE;
}

/**
 *@brief 判断是否为玩家自身排行
 */
inline bool IsPlayerSortList(int type)
{
	switch(type)
	{
	case SORTLIST_POWER:
	case SORTLIST_LEVEL:
	case SORTLIST_NEW_SERVER_LEVEL:
	case SORTLIST_NEW_YEAR_RED_PACKET:
	//case SORTLIST_SIXIANG:
	case SORTLIST_SCORE_WAR:
	case SORTLIST_CHALLENGE_DAILY:
	case SORTLIST_FESTIVAL:
	case SORTLIST_GET_FLOWER:
	case SORTLIST_GIVE_FLOWER:
	case SORTLIST_EQUIP_POWER:
	case SORTLIST_ACTIVITYCONSUME:
	case SORTLIST_ACTIVITYCONSUME1:
	case SORTLIST_DAY_CONSUME:
	case SORTLIST_ACHIEVEMENT_SCORE:
	case SORTLIST_TOWER_1:
	case SORTLIST_TOWER_2:
	case SORTLIST_TOWER_3:
	case SORTLIST_TOWER_4:
	case SORTLIST_TOWER_OCCU_GUIJIANSHI:
	case SORTLIST_TOWER_OCCU_JIANHUN:
	case SORTLIST_TOWER_OCCU_KUANGZHANSHI:
	case SORTLIST_TOWER_OCCU_GUIQI:
	case SORTLIST_TOWER_OCCU_AXIULUO:
	case SORTLIST_TOWER_OCCU_SHENQIANGSHOU:
	case SORTLIST_TOWER_OCCU_MANYOU:
	case SORTLIST_TOWER_OCCU_QIANGPAOSHI:
	case SORTLIST_TOWER_OCCU_JIXIESHI:
	case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA:
	case SORTLIST_TOWER_OCCU_MOFASHI:
	case SORTLIST_TOWER_OCCU_YUANSUSHI:
	case SORTLIST_TOWER_OCCU_ZHANDOUFASHI:
	case SORTLIST_TOWER_OCCU_ZHAOHUANSHI:
	case SORTLIST_TOWER_OCCU_GEDOUJIA:
	case SORTLIST_TOWER_OCCU_QIGONGSHI:
	case SORTLIST_TOWER_OCCU_SANDA:
	case SORTLIST_TOWER_OCCU_JIEBA:
	case SORTLIST_TOWER_OCCU_ROUDAOJIA:
	case SORTLIST_TOWER_OCCU_SHENQIANGSHOU_NV:
	case SORTLIST_TOWER_OCCU_MANYOU_NV:
	case SORTLIST_TOWER_OCCU_QIANGPAOSHI_NV:
	case SORTLIST_TOWER_OCCU_JIXIESHI_NV:
	case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA_NV:
	case SORTLIST_TOWER_OCCU_SHENGZHIZHE:
	case SORTLIST_TOWER_OCCU_QUMO:
	case SORTLIST_TOWER_OCCU_SHENGQISHI:

	case SORTLIST_1V1_SEASON:
	case SORTLIST_1V1_SEASON_OCCU_GUIJIANSHI:
	case SORTLIST_1V1_SEASON_OCCU_JIANHUN:
	case SORTLIST_1V1_SEASON_OCCU_KUANGZHANSHI:
	case SORTLIST_1V1_SEASON_OCCU_GUIQI:
	case SORTLIST_1V1_SEASON_OCCU_AXIULUO:
	case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU:
	case SORTLIST_1V1_SEASON_OCCU_MANYOU:
	case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI:
	case SORTLIST_1V1_SEASON_OCCU_JIXIESHI:
	case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA:
	case SORTLIST_1V1_SEASON_OCCU_MOFASHI:
	case SORTLIST_1V1_SEASON_OCCU_YUANSUSHI:
	case SORTLIST_1V1_SEASON_OCCU_ZHANDOUFASHI:
	case SORTLIST_1V1_SEASON_OCCU_ZHAOHUANSHI:
	case SORTLIST_1V1_SEASON_OCCU_GEDOUJIA:
	case SORTLIST_1V1_SEASON_OCCU_QIGONGSHI:
	case SORTLIST_1V1_SEASON_OCCU_SANDA:
	case SORTLIST_1V1_SEASON_OCCU_JIEBA:
	case SORTLIST_1V1_SEASON_OCCU_ROUDAOJIA:
	case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU_NV:
	case SORTLIST_1V1_SEASON_OCCU_MANYOU_NV:
	case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI_NV:
	case SORTLIST_1V1_SEASON_OCCU_JIXIESHI_NV:
	case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA_NV:
	case SORTLIST_1V1_SEASON_OCCU_SHENGZHIZHE:
	case SORTLIST_1V1_SEASON_OCCU_QUMO:
	case SORTLIST_1V1_SEASON_OCCU_SHENGQISHI:
	case SORTLIST_GUILD_BATTLE_MEMBER:

	//added by aprilliu 2017.04.21
	case SORTLIST_LEVEL_OCCU_GUIJIANSHI:			//鬼剑士
	case SORTLIST_LEVEL_OCCU_JIANHUN:
	case SORTLIST_LEVEL_OCCU_KUANGZHANSHI:				//狂战士
	case SORTLIST_LEVEL_OCCU_GUIQI:
	case SORTLIST_LEVEL_OCCU_AXIULUO:
	case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU:				//神枪手男
	case SORTLIST_LEVEL_OCCU_MANYOU: 					//漫游男
	case SORTLIST_LEVEL_OCCU_QIANGPAOSHI:
	case SORTLIST_LEVEL_OCCU_JIXIESHI:
	case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA:
	case SORTLIST_LEVEL_OCCU_MOFASHI:		//魔法师
	case SORTLIST_LEVEL_OCCU_YUANSUSHI:
	case SORTLIST_LEVEL_OCCU_ZHANDOUFASHI:
	case SORTLIST_LEVEL_OCCU_ZHAOHUANSHI:		//召唤师
	case SORTLIST_LEVEL_OCCU_GEDOUJIA: 	//格斗家
	case SORTLIST_LEVEL_OCCU_QIGONGSHI:
	case SORTLIST_LEVEL_OCCU_SANDA:
	case SORTLIST_LEVEL_OCCU_JIEBA:
	case SORTLIST_LEVEL_OCCU_ROUDAOJIA:
	case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU_NV:			//神枪手女
	case SORTLIST_LEVEL_OCCU_MANYOU_NV:					//漫游枪手女
	case SORTLIST_LEVEL_OCCU_QIANGPAOSHI_NV:
	case SORTLIST_LEVEL_OCCU_JIXIESHI_NV:
	case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA_NV:
	case SORTLIST_LEVEL_OCCU_SHENGZHIZHE:
	case SORTLIST_LEVEL_OCCU_QUMO:
	case SORTLIST_LEVEL_OCCU_SHENGQISHI:
	case SORTLIST_PREMIUM_LEAGUE:
		return true;
	}
	return false;
}

/**
*@brief 判断是否为账号类型排行
*/
inline bool IsAccountSortList(int type)
{
	switch (type)
	{
	case SORTLIST_ADVENTURE_TEAM_GRADE:
		return true;

	default:
		return false;
	}
}

/**
 *@brief 判断是否为宠物排行榜
 */
inline bool IsPetSortList(int type)
{
	switch(type)
	{
	case SORTLIST_PET:
	case SORTLIST_PET_LEVEL:
	case SORTLIST_PET_GROWTH:
	case SORTLIST_PET_APTITUDE:
	case SORTLIST_PET_SKILL:
		return true;
	}
	return false;
}

/**
 *@brief 判断是否为装备排行榜
 */
inline bool IsEquipSortList(int type)
{
	switch(type)
	{
	case SORTLIST_WEAPON:
	//added by aprilliu, 2017.04.21
	case SORTLIST_WEAPON_TT_ITEM_HUGESWORD:					//武器-巨剑
	case SORTLIST_WEAPON_TT_ITEM_KATANA:						//武器-太刀
	case SORTLIST_WEAPON_TT_ITEM_REVOLVER:					//武器-左轮
	case SORTLIST_WEAPON_TT_ITEM_HANDCANNON:					//武器-手炮
	case SORTLIST_WEAPON_TT_ITEM_WAND:						//武器-魔杖
	case SORTLIST_WEAPON_TT_ITEM_STAFF:						//武器-法杖
	case SORTLIST_WEAPON_TT_ITEM_SHORT_SWORD:				//武器-短剑
	case SORTLIST_WEAPON_TT_ITEM_GLOVE:						//武器-手套
	case SORTLIST_WEAPON_TT_ITEM_BIKAI:						//武器-臂铠
	case SORTLIST_WEAPON_TT_ITEM_CLAW:						//武器-爪
	case SORTLIST_WEAPON_TT_ITEM_OFG:						//武器-拳套
	case SORTLIST_WEAPON_TT_ITEM_EAST_STICK:				//武器-东方棍
	case SORTLIST_WEAPON_TT_ITEM_CROSSBOW:					//武器-弩
	case SORTLIST_WEAPON_TT_ITEM_RIFLE:						//武器-步枪
	case SORTLIST_WEAPON_TT_ITEM_BEAMSWORD:					//武器-光剑
	case SORTLIST_WEAPON_TT_ITEM_SICKLE:					//武器-镰刀
	case SORTLIST_WEAPON_TT_ITEM_TOTEM:						//武器-图腾
	case SORTLIST_WEAPON_TT_ITEM_AXE:						//武器-战斧
	case SORTLIST_WEAPON_TT_ITEM_BEADS:						//武器-念珠
	case SORTLIST_WEAPON_TT_ITEM_CROSS:						//武器-十字架
	case SORTLIST_WEAPON_TT_ITEM_SPEAR:						//武器-矛
	case SORTLIST_WEAPON_TT_ITEM_STICK:						//武器-棍
		return true;
	}
	return false;
}

/**
 *@brief 是否全服排行榜                                                                     
 */
inline bool IsWorldSortList(int type)
{
	switch(type)
	{
	case SORTLIST_ACTIVITYCONSUME:
		return true;
	}
	return false;
}

/**
 *@brief 是否取最大值排行（只保存最佳纪录）
 */
inline bool IsMaxValueSortList(int type)
{
	switch(type)
	{
	case SORTLIST_POWER:
	//case SORTLIST_SIXIANG:
	case SORTLIST_EQUIP_POWER:
    case SORTLIST_TOWER_1:
    case SORTLIST_TOWER_2:
    case SORTLIST_TOWER_3:
    case SORTLIST_TOWER_4:
	case SORTLIST_TOWER_OCCU_GUIJIANSHI:
	case SORTLIST_TOWER_OCCU_JIANHUN:
	case SORTLIST_TOWER_OCCU_KUANGZHANSHI:
	case SORTLIST_TOWER_OCCU_GUIQI:
	case SORTLIST_TOWER_OCCU_AXIULUO:
	case SORTLIST_TOWER_OCCU_SHENQIANGSHOU:
	case SORTLIST_TOWER_OCCU_MANYOU:
	case SORTLIST_TOWER_OCCU_QIANGPAOSHI:
	case SORTLIST_TOWER_OCCU_JIXIESHI:
	case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA:
	case SORTLIST_TOWER_OCCU_MOFASHI:
	case SORTLIST_TOWER_OCCU_YUANSUSHI:
	case SORTLIST_TOWER_OCCU_ZHANDOUFASHI:
	case SORTLIST_TOWER_OCCU_ZHAOHUANSHI:
	case SORTLIST_TOWER_OCCU_GEDOUJIA:
	case SORTLIST_TOWER_OCCU_QIGONGSHI:
	case SORTLIST_TOWER_OCCU_SANDA:
	case SORTLIST_TOWER_OCCU_JIEBA:
	case SORTLIST_TOWER_OCCU_ROUDAOJIA:
	case SORTLIST_TOWER_OCCU_SHENQIANGSHOU_NV:
	case SORTLIST_TOWER_OCCU_MANYOU_NV:
	case SORTLIST_TOWER_OCCU_QIANGPAOSHI_NV:
	case SORTLIST_TOWER_OCCU_JIXIESHI_NV:
	case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA_NV:
	case SORTLIST_TOWER_OCCU_SHENGZHIZHE:
	case SORTLIST_TOWER_OCCU_QUMO:
	case SORTLIST_TOWER_OCCU_SHENGQISHI:
		return true;
	}
	return false;
}

/**
 *@brief 是否需要存储
 */
inline bool IsSortDataNeedSave(int type)
{
	switch(type)
	{
	case SORTLIST_CHALLENGE_DAILY:
	case SORTLIST_GUILD_LEVEL:
		return false;
	}
	return true;
}

//added by aprilliu, 2017.04.21 
//根据武器的子类型得到排行榜类型
inline SortListType GetWeaponSortListTypeByItemThirdType(UInt32 ItemThirdType)
{
	SortListType type = SORTLIST_INVALID;
	switch (ItemThirdType)
	{
		case TT_ITEM_HUGESWORD:
			type = SORTLIST_WEAPON_TT_ITEM_HUGESWORD;
			break;
		case TT_ITEM_KATANA:
			type = SORTLIST_WEAPON_TT_ITEM_KATANA;
			break;
		case TT_ITEM_REVOLVER:
			type = SORTLIST_WEAPON_TT_ITEM_REVOLVER;
			break;
		case TT_ITEM_HANDCANNON:
			type = SORTLIST_WEAPON_TT_ITEM_HANDCANNON;
			break;
		case TT_ITEM_WAND:
			type = SORTLIST_WEAPON_TT_ITEM_WAND;
			break;
		case TT_ITEM_STAFF:
			type = SORTLIST_WEAPON_TT_ITEM_STAFF;
			break;
		case TT_ITEM_SHORTSWORD:
			type = SORTLIST_WEAPON_TT_ITEM_SHORT_SWORD;
			break;
		case TT_ITEM_GLOVE:
			type = SORTLIST_WEAPON_TT_ITEM_GLOVE;
			break;
		case TT_ITEM_BIKAI:
			type = SORTLIST_WEAPON_TT_ITEM_BIKAI;
			break;
		case TT_ITEM_CLAW:
			type = SORTLIST_WEAPON_TT_ITEM_CLAW;
			break;
		case TT_ITEM_OFG:
			type = SORTLIST_WEAPON_TT_ITEM_OFG;
			break;
		case TT_ITEM_EAST_STICK:
			type = SORTLIST_WEAPON_TT_ITEM_EAST_STICK;
			break;
		case TT_ITEM_CROSSBOW:
			type = SORTLIST_WEAPON_TT_ITEM_CROSSBOW;
			break;
		case TT_ITEM_RIFLE:
			type = SORTLIST_WEAPON_TT_ITEM_RIFLE;
			break;
		case TT_ITEM_BEAMSWORD:
			type = SORTLIST_WEAPON_TT_ITEM_BEAMSWORD;
			break;
		case TT_ITEM_SICKLE:
			type = SORTLIST_WEAPON_TT_ITEM_SICKLE;
			break;
		case TT_ITEM_TOTEM:
			type = SORTLIST_WEAPON_TT_ITEM_TOTEM;
			break;
		case TT_ITEM_AXE:
			type = SORTLIST_WEAPON_TT_ITEM_AXE;
			break;
		case TT_ITEM_BEADS:
			type = SORTLIST_WEAPON_TT_ITEM_BEADS;
			break;
		case TT_ITEM_CROSS:
			type = SORTLIST_WEAPON_TT_ITEM_CROSS;
			break;
		case TT_ITEM_SPEAR:
			type = SORTLIST_WEAPON_TT_ITEM_SPEAR;
			break;
		case TT_ITEM_STICK:
			type = SORTLIST_WEAPON_TT_ITEM_STICK;
			break;
		default:
			break;

	}
	return type;
}

inline SortListType GetLevelSortListTypeByOccu(UInt8 occupation)
{
	SortListType type = SORTLIST_INVALID;
	switch (occupation)
	{
		//鬼剑士
		case OCCU_JIANHUN:
			type = SORTLIST_LEVEL_OCCU_JIANHUN;
			break;
		case OCCU_KUANGZHANSHI:
			type = SORTLIST_LEVEL_OCCU_KUANGZHANSHI;
			break;
		case OCCU_GUIQI:
			type = SORTLIST_LEVEL_OCCU_GUIQI;
			break;
		case OCCU_AXIULUO:
			type = SORTLIST_LEVEL_OCCU_AXIULUO;
			break;

		//神枪手男
		case OCCU_MANYOU:
			type = SORTLIST_LEVEL_OCCU_MANYOU;
			break;
		case OCCU_QIANGPAOSHI:
			type = SORTLIST_LEVEL_OCCU_QIANGPAOSHI;
			break;
		case OCCU_JIXIESHI:
			type = SORTLIST_LEVEL_OCCU_JIXIESHI;
			break;

		case OCCU_DANYAOZHUANJIA:
			type = SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA;
			break;

		//魔法师
		case OCCU_YUANSUSHI:
			type = SORTLIST_LEVEL_OCCU_YUANSUSHI;
			break;

		case OCCU_ZHANDOUFASHI:
			type = SORTLIST_LEVEL_OCCU_ZHANDOUFASHI;
			break;

		case OCCU_ZHAOHUANSHI:
			type = SORTLIST_LEVEL_OCCU_ZHAOHUANSHI;
			break;

		//格斗家
		case OCCU_QIGONGSHI:
			type = SORTLIST_LEVEL_OCCU_QIGONGSHI;
			break;

		case OCCU_SANDA:
			type = SORTLIST_LEVEL_OCCU_SANDA;
			break;

		case OCCU_JIEBA:
			type = SORTLIST_LEVEL_OCCU_JIEBA;
			break;
		case OCCU_ROUDAOJIA:
			type = SORTLIST_LEVEL_OCCU_ROUDAOJIA;
			break;

		//神枪手女
		case OCCU_MANYOU_NV:
			type = SORTLIST_LEVEL_OCCU_MANYOU_NV;
			break;
		case OCCU_QIANGPAOSHI_NV:
			type = SORTLIST_LEVEL_OCCU_QIANGPAOSHI_NV;
			break;
		case OCCU_JIXIESHI_NV:
			type = SORTLIST_LEVEL_OCCU_JIXIESHI_NV;
			break;
		case OCCU_DANYAOZHUANJIA_NV:
			type = SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA_NV;
			break;

		//圣职者
		case OCCU_QUMO:
			type = SORTLIST_LEVEL_OCCU_QUMO;
			break;
		case OCCU_SHENGQISHI:
			type = SORTLIST_LEVEL_OCCU_SHENGQISHI;
			break;
	default:
		break;
	}

	return type;
}

inline SortListType GetTowerSortListTypeByOccu(UInt8 occupation)
{
	SortListType type = SORTLIST_INVALID;
	switch (occupation)
	{
		//鬼剑士
	case OCCU_JIANHUN:
		type = SORTLIST_TOWER_OCCU_JIANHUN;
		break;
	case OCCU_KUANGZHANSHI:
		type = SORTLIST_TOWER_OCCU_KUANGZHANSHI;
		break;
	case OCCU_GUIQI:
		type = SORTLIST_TOWER_OCCU_GUIQI;
		break;
	case OCCU_AXIULUO:
		type = SORTLIST_TOWER_OCCU_AXIULUO;
		break;

		//神枪手男
	case OCCU_MANYOU:
		type = SORTLIST_TOWER_OCCU_MANYOU;
		break;
	case OCCU_QIANGPAOSHI:
		type = SORTLIST_TOWER_OCCU_QIANGPAOSHI;
		break;
	case OCCU_JIXIESHI:
		type = SORTLIST_TOWER_OCCU_JIXIESHI;
		break;
	case OCCU_DANYAOZHUANJIA:
		type = SORTLIST_TOWER_OCCU_DANYAOZHUANJIA;
		break;

		//魔法师
	case OCCU_YUANSUSHI:
		type = SORTLIST_TOWER_OCCU_YUANSUSHI;
		break;
	case OCCU_ZHANDOUFASHI:
		type = SORTLIST_TOWER_OCCU_ZHANDOUFASHI;
		break;
	case OCCU_ZHAOHUANSHI:
		type = SORTLIST_TOWER_OCCU_ZHAOHUANSHI;
		break;

		//格斗家
	case OCCU_QIGONGSHI:
		type = SORTLIST_TOWER_OCCU_QIGONGSHI;
		break;
	case OCCU_SANDA:
		type = SORTLIST_TOWER_OCCU_SANDA;
		break;
	case OCCU_JIEBA:
		type = SORTLIST_TOWER_OCCU_JIEBA;
		break;
	case OCCU_ROUDAOJIA:
		type = SORTLIST_TOWER_OCCU_ROUDAOJIA;
		break;

		//神枪手女
	case OCCU_MANYOU_NV:
		type = SORTLIST_TOWER_OCCU_MANYOU_NV;
		break;
	case OCCU_QIANGPAOSHI_NV:
		type = SORTLIST_TOWER_OCCU_QIANGPAOSHI_NV;
		break;
	case OCCU_JIXIESHI_NV:
		type = SORTLIST_TOWER_OCCU_JIXIESHI_NV;
		break;
	case OCCU_DANYAOZHUANJIA_NV:
		type = SORTLIST_TOWER_OCCU_DANYAOZHUANJIA_NV;
		break;

	//圣职者
	case OCCU_QUMO:
		type = SORTLIST_TOWER_OCCU_QUMO;
		break;
	case OCCU_SHENGQISHI:
		type = SORTLIST_TOWER_OCCU_SHENGQISHI;
		break;
	default:
		break;
	}

	return type;
}


inline SortListType Get1v1SeasonSortListTypeByOccu(UInt8 occupation)
{
	SortListType type = SORTLIST_INVALID;
	switch (occupation)
	{
		//鬼剑士
	case OCCU_JIANHUN:
		type = SORTLIST_1V1_SEASON_OCCU_JIANHUN;
		break;
	case OCCU_KUANGZHANSHI:
		type = SORTLIST_1V1_SEASON_OCCU_KUANGZHANSHI;
		break;
	case OCCU_GUIQI:
		type = SORTLIST_1V1_SEASON_OCCU_GUIQI;
		break;
	case OCCU_AXIULUO:
		type = SORTLIST_1V1_SEASON_OCCU_AXIULUO;
		break;

		//神枪手男
	case OCCU_MANYOU:
		type = SORTLIST_1V1_SEASON_OCCU_MANYOU;
		break;
	case OCCU_QIANGPAOSHI:
		type = SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI;
		break;
	case OCCU_JIXIESHI:
		type = SORTLIST_1V1_SEASON_OCCU_JIXIESHI;
		break;
	case OCCU_DANYAOZHUANJIA:
		type = SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA;
		break;

		//魔法师
	case OCCU_YUANSUSHI:
		type = SORTLIST_1V1_SEASON_OCCU_YUANSUSHI;
		break;
	case OCCU_ZHANDOUFASHI:
		type = SORTLIST_1V1_SEASON_OCCU_ZHANDOUFASHI;
		break;
	case OCCU_ZHAOHUANSHI:
		type = SORTLIST_1V1_SEASON_OCCU_ZHAOHUANSHI;
		break;

		//格斗家
	case OCCU_QIGONGSHI:
		type = SORTLIST_1V1_SEASON_OCCU_QIGONGSHI;
		break;
	case OCCU_SANDA:
		type = SORTLIST_1V1_SEASON_OCCU_SANDA;
		break;
	case OCCU_JIEBA:
		type = SORTLIST_1V1_SEASON_OCCU_JIEBA;
		break;
	case OCCU_ROUDAOJIA:
		type = SORTLIST_1V1_SEASON_OCCU_ROUDAOJIA;
		break;

		//神枪手女
	case OCCU_MANYOU_NV:
		type = SORTLIST_1V1_SEASON_OCCU_MANYOU_NV;
		break;
	case OCCU_QIANGPAOSHI_NV:
		type = SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI_NV;
		break;
	case OCCU_JIXIESHI_NV:
		type = SORTLIST_1V1_SEASON_OCCU_JIXIESHI_NV;
		break;
	case OCCU_DANYAOZHUANJIA_NV:
		type = SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA_NV;
		break;

	//圣职者
	case OCCU_QUMO:
		type = SORTLIST_1V1_SEASON_OCCU_QUMO;
		break;
	case OCCU_SHENGQISHI:
		type = SORTLIST_1V1_SEASON_OCCU_SHENGQISHI;
		break;

	default:
		break;
	}

	return type;
}

/**
 *@brief 排行项
 */
struct SortListEntry
{
	SortListEntry():key(0), id(0), sortType(0), zoneId(0), quality(0), level(0), vip(0), occu(0), sex(0), ownerId(0), ownerAccid(0)
		, value1(0), value2(0), value3(0), updateTime(0), bDirty(false){}

	/**
	 *@brief 序列化到客户端
	 */
	void SerializeForClient(Avalon::NetOutputStream& stream)
	{
		switch(sortType)
		{
		case SORTLIST_POWER:
			stream & id & name & vip & occu & tribeName & value1 & value2;		//value1表示等级 value2表示战力值
			break;
		case SORTLIST_NEW_YEAR_RED_PACKET:
			stream & id & name & occu & value1;
			break;
		case SORTLIST_LEVEL:
		case SORTLIST_NEW_SERVER_LEVEL:
			//stream & id & name & vip & occu & tribeName & value1;					//value1表示等级
		//added by aprilliu ,2017.04.21 
		case SORTLIST_LEVEL_OCCU_GUIJIANSHI:			//鬼剑士
		case SORTLIST_LEVEL_OCCU_JIANHUN:
		case SORTLIST_LEVEL_OCCU_KUANGZHANSHI:				//狂战士
		case SORTLIST_LEVEL_OCCU_GUIQI:
		case SORTLIST_LEVEL_OCCU_AXIULUO:					//阿修罗

		case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU:				//神枪手男
		case SORTLIST_LEVEL_OCCU_MANYOU: 					//漫游男
		case SORTLIST_LEVEL_OCCU_QIANGPAOSHI:
		case SORTLIST_LEVEL_OCCU_JIXIESHI:
		case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA:


		case SORTLIST_LEVEL_OCCU_MOFASHI:		//魔法师
		case SORTLIST_LEVEL_OCCU_YUANSUSHI:
		case SORTLIST_LEVEL_OCCU_ZHANDOUFASHI:
		case SORTLIST_LEVEL_OCCU_ZHAOHUANSHI:		//召唤师


		case SORTLIST_LEVEL_OCCU_GEDOUJIA: 	//格斗家
		case SORTLIST_LEVEL_OCCU_QIGONGSHI:
		case SORTLIST_LEVEL_OCCU_SANDA:
		case SORTLIST_LEVEL_OCCU_JIEBA:
		case SORTLIST_LEVEL_OCCU_ROUDAOJIA:
		case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU_NV:			//神枪手女
		case SORTLIST_LEVEL_OCCU_MANYOU_NV:					//漫游枪手女
		case SORTLIST_LEVEL_OCCU_QIANGPAOSHI_NV:
		case SORTLIST_LEVEL_OCCU_JIXIESHI_NV:
		case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA_NV:
		case SORTLIST_LEVEL_OCCU_SHENGZHIZHE:
		case SORTLIST_LEVEL_OCCU_QUMO:
		case SORTLIST_LEVEL_OCCU_SHENGQISHI:
			stream & id & name & occu & (UInt16)value1;			//value1表示等级
			break;
		case SORTLIST_ACHIEVEMENT_SCORE:
			stream & id & name & occu & value1;					//value1 表示成就积分
			break;
		case SORTLIST_WEAPON:
		//added by aprilliu 2017.04.21 
		case SORTLIST_WEAPON_TT_ITEM_HUGESWORD:					//武器-巨剑
		case SORTLIST_WEAPON_TT_ITEM_KATANA:						//武器-太刀
		case SORTLIST_WEAPON_TT_ITEM_REVOLVER:					//武器-左轮
		case SORTLIST_WEAPON_TT_ITEM_HANDCANNON:					//武器-手炮
		case SORTLIST_WEAPON_TT_ITEM_WAND:						//武器-魔杖
		case SORTLIST_WEAPON_TT_ITEM_STAFF:						//武器-法杖
		case SORTLIST_WEAPON_TT_ITEM_SHORT_SWORD:				//武器-短剑
		case SORTLIST_WEAPON_TT_ITEM_GLOVE:						//武器-手套
		case SORTLIST_WEAPON_TT_ITEM_BIKAI:						//武器-臂铠
		case SORTLIST_WEAPON_TT_ITEM_CLAW:						//武器-爪
		case SORTLIST_WEAPON_TT_ITEM_OFG:						//武器-拳套
		case SORTLIST_WEAPON_TT_ITEM_EAST_STICK:				//武器-东方棍
		case SORTLIST_WEAPON_TT_ITEM_CROSSBOW:					//武器-弩
		case SORTLIST_WEAPON_TT_ITEM_RIFLE:						//武器-步枪
		case SORTLIST_WEAPON_TT_ITEM_BEAMSWORD:					//武器-光剑
		case SORTLIST_WEAPON_TT_ITEM_SICKLE:					//武器-镰刀
		case SORTLIST_WEAPON_TT_ITEM_TOTEM:						//武器-图腾
		case SORTLIST_WEAPON_TT_ITEM_AXE:						//武器-战斧
		case SORTLIST_WEAPON_TT_ITEM_BEADS:						//武器-念珠
		case SORTLIST_WEAPON_TT_ITEM_CROSS:						//武器-十字架
		case SORTLIST_WEAPON_TT_ITEM_SPEAR:						//武器-矛
		case SORTLIST_WEAPON_TT_ITEM_STICK:						//武器-棍
			stream & id & name & ownerId & ownerName & level  & value1 & value2 & value3 & sex & occu;	//modified by aprilliu: level：表示武器等级  value1表示武器强化等级 value2表示武器战斗力（评分）,value3表示道具资源Id,sex表示装备类型,occu表示增幅路线,道具的品质，名字信息可以根据value3查表得到,所以装备名字并没有同步给client
			break;
		case SORTLIST_PET:
		case SORTLIST_PET_LEVEL:
		case SORTLIST_PET_GROWTH:
		case SORTLIST_PET_APTITUDE:
		case SORTLIST_PET_SKILL:
			stream & id & name & quality & ownerId & ownerName & value1;		//value1表示评分
			break;
		//case SORTLIST_SIXIANG:
		//	stream & id & name & vip & occu & value1 & value2;					//value1 为通关层数,value2为通关时间
		//	break;
		case SORTLIST_CHALLENGE_DAILY:
			stream & id & name & level & vip & occu & value1 & value2;			//value1 为积分 value2为百分比胜率
			break;
		case SORTLIST_FESTIVAL:
			stream & id & name & vip & occu & tribeName & value1 & value2;			//value1表示节日活动计数,value2表示等级
			break;
		case SORTLIST_GET_FLOWER:
		case SORTLIST_GIVE_FLOWER:
			stream & id & name & vip & occu & tribeName & value1 & value2;			//value1表示鲜花数量
			break;
		case SORTLIST_EQUIP_POWER:
			stream & id & name & vip & occu & tribeName & value1 & value2;			//value1表示等级 value2表示装备战力值
			break;
		case SORTLIST_ACTIVITYCONSUME:
			stream & id & name & zoneId & vip & value1;								//value1表示消费总额
			break;
		case SORTLIST_ACTIVITYCONSUME1:
		case SORTLIST_DAY_CONSUME:
			stream & id & name & vip & occu  & value1;								//value1表示每日消费金贝
			break;
        case SORTLIST_TOWER_1:
        case SORTLIST_TOWER_2:
        case SORTLIST_TOWER_3:
        case SORTLIST_TOWER_4:
		case SORTLIST_TOWER_OCCU_GUIJIANSHI:
		case SORTLIST_TOWER_OCCU_JIANHUN:
		case SORTLIST_TOWER_OCCU_KUANGZHANSHI:
		case SORTLIST_TOWER_OCCU_GUIQI:
		case SORTLIST_TOWER_OCCU_AXIULUO:
		case SORTLIST_TOWER_OCCU_SHENQIANGSHOU:
		case SORTLIST_TOWER_OCCU_MANYOU:
		case SORTLIST_TOWER_OCCU_QIANGPAOSHI:
		case SORTLIST_TOWER_OCCU_JIXIESHI:
		case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA:
		case SORTLIST_TOWER_OCCU_MOFASHI:
		case SORTLIST_TOWER_OCCU_YUANSUSHI:
		case SORTLIST_TOWER_OCCU_ZHANDOUFASHI:
		case SORTLIST_TOWER_OCCU_ZHAOHUANSHI:
		case SORTLIST_TOWER_OCCU_GEDOUJIA:
		case SORTLIST_TOWER_OCCU_QIGONGSHI:
		case SORTLIST_TOWER_OCCU_SANDA:
		case SORTLIST_TOWER_OCCU_JIEBA:
		case SORTLIST_TOWER_OCCU_ROUDAOJIA:
		case SORTLIST_TOWER_OCCU_SHENQIANGSHOU_NV:
		case SORTLIST_TOWER_OCCU_MANYOU_NV:
		case SORTLIST_TOWER_OCCU_QIANGPAOSHI_NV:
		case SORTLIST_TOWER_OCCU_JIXIESHI_NV:
		case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA_NV:
		case SORTLIST_TOWER_OCCU_SHENGZHIZHE:
		case SORTLIST_TOWER_OCCU_QUMO:
		case SORTLIST_TOWER_OCCU_SHENGQISHI:
            stream & id & name & occu & level & value1 & value2;							//value1表示最高层，value2表示用时
            break;
		case SORTLIST_1V1_SEASON:
		case SORTLIST_1V1_SEASON_OCCU_GUIJIANSHI:
		case SORTLIST_1V1_SEASON_OCCU_JIANHUN:
		case SORTLIST_1V1_SEASON_OCCU_KUANGZHANSHI:
		case SORTLIST_1V1_SEASON_OCCU_GUIQI:
		case SORTLIST_1V1_SEASON_OCCU_AXIULUO:
		case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU:
		case SORTLIST_1V1_SEASON_OCCU_MANYOU:
		case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI:
		case SORTLIST_1V1_SEASON_OCCU_JIXIESHI:
		case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA:
		case SORTLIST_1V1_SEASON_OCCU_MOFASHI:
		case SORTLIST_1V1_SEASON_OCCU_YUANSUSHI:
		case SORTLIST_1V1_SEASON_OCCU_ZHANDOUFASHI:
		case SORTLIST_1V1_SEASON_OCCU_ZHAOHUANSHI:
		case SORTLIST_1V1_SEASON_OCCU_GEDOUJIA:
		case SORTLIST_1V1_SEASON_OCCU_QIGONGSHI:
		case SORTLIST_1V1_SEASON_OCCU_SANDA:
		case SORTLIST_1V1_SEASON_OCCU_JIEBA:
		case SORTLIST_1V1_SEASON_OCCU_ROUDAOJIA:
		case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU_NV:
		case SORTLIST_1V1_SEASON_OCCU_MANYOU_NV:
		case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI_NV:
		case SORTLIST_1V1_SEASON_OCCU_JIXIESHI_NV:
		case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA_NV:
		case SORTLIST_1V1_SEASON_OCCU_SHENGZHIZHE:
		case SORTLIST_1V1_SEASON_OCCU_QUMO:
		case SORTLIST_1V1_SEASON_OCCU_SHENGQISHI:
			stream & id & name & occu & level & value1 & value2;				//value1 表示段位  value2 表示星
			break;
		case SORTLIST_GUILD_BATTLE_SCORE:
		case SORTLIST_GUILD_BATTLE_WEEK_SCORE:
			stream & id & name & value1;											//value1 表示公会积分
			break;
		case SORTLIST_GUILD_BATTLE_MEMBER:
			stream & id & name & value1;									//value1 表示公会战成员积分
			break;
		case SORTLIST_GUILD_LEVEL:
			stream & id & name & ownerName & guildMemberNum & value1;		//value1 表示等级, value2表示公会成员数量
			break;
		case SORTLIST_PREMIUM_LEAGUE:
			stream & id & name & occu & level & value1 & value2 & value3;		//value1 表示积分, value2表示时间
			break;
		case SORTLIST_ADVENTURE_TEAM_GRADE:
			stream & id & name & level & ownerName & value1 & value2; // value1 表示冒险团总评分, value2表示冒险团评级, value3 头衔
			break;
		}
	}

	AVALON_DEFINE_NETSERIALIZATION()
	{
		stream & sortType & id;

		switch(sortType)
		{
		case SORTLIST_POWER:
		case SORTLIST_LEVEL:
		case SORTLIST_NEW_SERVER_LEVEL:
		//added by aprilliu, 2017.04.21
		case SORTLIST_LEVEL_OCCU_GUIJIANSHI:			//鬼剑士
		case SORTLIST_LEVEL_OCCU_JIANHUN:
		case SORTLIST_LEVEL_OCCU_KUANGZHANSHI:				//狂战士
		case SORTLIST_LEVEL_OCCU_GUIQI:
		case SORTLIST_LEVEL_OCCU_AXIULUO:
		case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU:				//神枪手男
		case SORTLIST_LEVEL_OCCU_MANYOU: 					//漫游男
		case SORTLIST_LEVEL_OCCU_QIANGPAOSHI:
		case SORTLIST_LEVEL_OCCU_JIXIESHI:
		case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA:
		case SORTLIST_LEVEL_OCCU_MOFASHI:		//魔法师
		case SORTLIST_LEVEL_OCCU_YUANSUSHI:
		case SORTLIST_LEVEL_OCCU_ZHANDOUFASHI:
		case SORTLIST_LEVEL_OCCU_ZHAOHUANSHI:		//召唤师
		case SORTLIST_LEVEL_OCCU_GEDOUJIA: 	//格斗家
		case SORTLIST_LEVEL_OCCU_QIGONGSHI:
		case SORTLIST_LEVEL_OCCU_SANDA:
		case SORTLIST_LEVEL_OCCU_JIEBA:
		case SORTLIST_LEVEL_OCCU_ROUDAOJIA:
		case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU_NV:			//神枪手女
		case SORTLIST_LEVEL_OCCU_MANYOU_NV:					//漫游枪手女
		case SORTLIST_LEVEL_OCCU_QIANGPAOSHI_NV:
		case SORTLIST_LEVEL_OCCU_JIXIESHI_NV:
		case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA_NV:
		case SORTLIST_LEVEL_OCCU_SHENGZHIZHE:
		case SORTLIST_LEVEL_OCCU_QUMO:
		case SORTLIST_LEVEL_OCCU_SHENGQISHI:
		//end of aprilliu
			stream & name & quality & occu & ownerId & level & value1 & value2 & value3; //modified by aprilliu: 为了兼容 level: 玩家等级, value1表示玩家等级
			break;
		case SORTLIST_ACHIEVEMENT_SCORE:
			stream & name & quality & occu & ownerId & level & value1 & value2 & value3;
			break;
		case SORTLIST_EQUIP_POWER:
		case SORTLIST_WEAPON:
		//added by aprilliu,2017.04.21
		case SORTLIST_WEAPON_TT_ITEM_HUGESWORD:					//武器-巨剑
		case SORTLIST_WEAPON_TT_ITEM_KATANA:						//武器-太刀
		case SORTLIST_WEAPON_TT_ITEM_REVOLVER:					//武器-左轮
		case SORTLIST_WEAPON_TT_ITEM_HANDCANNON:					//武器-手炮
		case SORTLIST_WEAPON_TT_ITEM_WAND:						//武器-魔杖
		case SORTLIST_WEAPON_TT_ITEM_STAFF:						//武器-法杖
		case SORTLIST_WEAPON_TT_ITEM_SHORT_SWORD:				//武器-短剑
		case SORTLIST_WEAPON_TT_ITEM_GLOVE:						//武器-手套
		case SORTLIST_WEAPON_TT_ITEM_BIKAI:						//武器-臂铠
		case SORTLIST_WEAPON_TT_ITEM_CLAW:						//武器-爪
		case SORTLIST_WEAPON_TT_ITEM_OFG:						//武器-拳套
		case SORTLIST_WEAPON_TT_ITEM_EAST_STICK:				//武器-东方棍
		case SORTLIST_WEAPON_TT_ITEM_CROSSBOW:					//武器-弩
		case SORTLIST_WEAPON_TT_ITEM_RIFLE:						//武器-步枪
		case SORTLIST_WEAPON_TT_ITEM_BEAMSWORD:					//武器-光剑
		case SORTLIST_WEAPON_TT_ITEM_SICKLE:					//武器-镰刀
		case SORTLIST_WEAPON_TT_ITEM_TOTEM:						//武器-图腾
		case SORTLIST_WEAPON_TT_ITEM_AXE:						//武器-战斧
		case SORTLIST_WEAPON_TT_ITEM_BEADS:						//武器-念珠
		case SORTLIST_WEAPON_TT_ITEM_CROSS:						//武器-十字架
		case SORTLIST_WEAPON_TT_ITEM_SPEAR:						//武器-矛
		case SORTLIST_WEAPON_TT_ITEM_STICK:						//武器-棍
		//end of aprilliu
			stream & name & quality & occu & ownerId & level & value1 & value2 & value3 & sex; //modified by aprilliu: level: 装备等级, value1：强化等级, value2: 装备评分 value3 表示资源id
			break;
		case SORTLIST_PET:
		case SORTLIST_PET_LEVEL:
		case SORTLIST_PET_GROWTH:
		case SORTLIST_PET_APTITUDE:
		case SORTLIST_PET_SKILL:
			stream & name & quality & ownerId & value1;
			break;
		case SORTLIST_FESTIVAL:
			stream & value1 & value2;
			break;
		case SORTLIST_GIVE_FLOWER:
		case SORTLIST_GET_FLOWER:
			stream & value1;
			break;
		case SORTLIST_ACTIVITYCONSUME:
			stream & name & zoneId & vip & value1;
			break;
		case SORTLIST_ACTIVITYCONSUME1:
			stream & value1;
			break;
		case SORTLIST_DAY_CONSUME:
			stream & value1;
			break;
		case SORTLIST_TOWER_1:
		case SORTLIST_TOWER_2:
		case SORTLIST_TOWER_3:
		case SORTLIST_TOWER_4:
		case SORTLIST_TOWER_OCCU_GUIJIANSHI:
		case SORTLIST_TOWER_OCCU_JIANHUN:
		case SORTLIST_TOWER_OCCU_KUANGZHANSHI:
		case SORTLIST_TOWER_OCCU_GUIQI:
		case SORTLIST_TOWER_OCCU_AXIULUO:
		case SORTLIST_TOWER_OCCU_SHENQIANGSHOU:
		case SORTLIST_TOWER_OCCU_MANYOU:
		case SORTLIST_TOWER_OCCU_QIANGPAOSHI:
		case SORTLIST_TOWER_OCCU_JIXIESHI:
		case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA:
		case SORTLIST_TOWER_OCCU_MOFASHI:
		case SORTLIST_TOWER_OCCU_YUANSUSHI:
		case SORTLIST_TOWER_OCCU_ZHANDOUFASHI:
		case SORTLIST_TOWER_OCCU_ZHAOHUANSHI:
		case SORTLIST_TOWER_OCCU_GEDOUJIA:
		case SORTLIST_TOWER_OCCU_QIGONGSHI:
		case SORTLIST_TOWER_OCCU_SANDA:
		case SORTLIST_TOWER_OCCU_JIEBA:
		case SORTLIST_TOWER_OCCU_ROUDAOJIA:
		case SORTLIST_TOWER_OCCU_SHENQIANGSHOU_NV:
		case SORTLIST_TOWER_OCCU_MANYOU_NV:
		case SORTLIST_TOWER_OCCU_QIANGPAOSHI_NV:
		case SORTLIST_TOWER_OCCU_JIXIESHI_NV:
		case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA_NV:
		case SORTLIST_TOWER_OCCU_SHENGZHIZHE:
		case SORTLIST_TOWER_OCCU_QUMO:
		case SORTLIST_TOWER_OCCU_SHENGQISHI:
			stream & name & occu & level & value1 & value2;							//value1表示最高层，value2表示用时
			break;
		case SORTLIST_1V1_SEASON:
		case SORTLIST_1V1_SEASON_OCCU_GUIJIANSHI:
		case SORTLIST_1V1_SEASON_OCCU_JIANHUN:
		case SORTLIST_1V1_SEASON_OCCU_KUANGZHANSHI:
		case SORTLIST_1V1_SEASON_OCCU_GUIQI:
		case SORTLIST_1V1_SEASON_OCCU_AXIULUO:
		case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU:
		case SORTLIST_1V1_SEASON_OCCU_MANYOU:
		case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI:
		case SORTLIST_1V1_SEASON_OCCU_JIXIESHI:
		case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA:
		case SORTLIST_1V1_SEASON_OCCU_MOFASHI:
		case SORTLIST_1V1_SEASON_OCCU_YUANSUSHI:
		case SORTLIST_1V1_SEASON_OCCU_ZHANDOUFASHI:
		case SORTLIST_1V1_SEASON_OCCU_ZHAOHUANSHI:
		case SORTLIST_1V1_SEASON_OCCU_GEDOUJIA:
		case SORTLIST_1V1_SEASON_OCCU_QIGONGSHI:
		case SORTLIST_1V1_SEASON_OCCU_SANDA:
		case SORTLIST_1V1_SEASON_OCCU_JIEBA:
		case SORTLIST_1V1_SEASON_OCCU_ROUDAOJIA:
		case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU_NV:
		case SORTLIST_1V1_SEASON_OCCU_MANYOU_NV:
		case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI_NV:
		case SORTLIST_1V1_SEASON_OCCU_JIXIESHI_NV:
		case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA_NV:
		case SORTLIST_1V1_SEASON_OCCU_SHENGZHIZHE:
		case SORTLIST_1V1_SEASON_OCCU_QUMO:
		case SORTLIST_1V1_SEASON_OCCU_SHENGQISHI:
			stream & name & occu & level & value1 & value2;
			break;
		case SORTLIST_GUILD_BATTLE_SCORE:
		case SORTLIST_GUILD_BATTLE_WEEK_SCORE:
			stream & name & value1;
			break;
		case SORTLIST_GUILD_BATTLE_MEMBER:
			stream & name & value1;
			break;
		case SORTLIST_PREMIUM_LEAGUE:
			stream & name & occu & level & value1 & value2 & value3;		//value1 表示积分, value2表示时间
			break;
		case SORTLIST_NEW_YEAR_RED_PACKET:
			stream & name & occu & value1;
			break;
		case SORTLIST_ADVENTURE_TEAM_GRADE:
			stream & id & name & level & ownerName & value1 & value2; // value1 表示冒险团总评分, value2表示冒险团评级
			break;
		}
	}

	static UInt64 GetSortFactor(UInt8 sortType, ObjID_t id, UInt32 value1, UInt32 value2, UInt32 value3)
	{
		switch(sortType)
		{
		case SORTLIST_NEW_YEAR_RED_PACKET: return value1;
		case SORTLIST_POWER:		return value2;
		case SORTLIST_NEW_SERVER_LEVEL:
		case SORTLIST_LEVEL:		return (UInt64(value1) << 32) + value2;  //value2表示经验
		case SORTLIST_PET:			return value1;
		case SORTLIST_PET_LEVEL:	return value1;
		case SORTLIST_PET_GROWTH:	return value1;
		case SORTLIST_PET_APTITUDE:	return value1;
		case SORTLIST_PET_SKILL:	return value1;
		case SORTLIST_ACHIEVEMENT_SCORE:	return value1;
		case SORTLIST_ADVENTURE_TEAM_GRADE: return value1;
		case SORTLIST_1V1_SEASON:
		case SORTLIST_1V1_SEASON_OCCU_GUIJIANSHI:
		case SORTLIST_1V1_SEASON_OCCU_JIANHUN:
		case SORTLIST_1V1_SEASON_OCCU_KUANGZHANSHI:
		case SORTLIST_1V1_SEASON_OCCU_GUIQI:
		case SORTLIST_1V1_SEASON_OCCU_AXIULUO:
		case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU:
		case SORTLIST_1V1_SEASON_OCCU_MANYOU:
		case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI:
		case SORTLIST_1V1_SEASON_OCCU_JIXIESHI:
		case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA:
		case SORTLIST_1V1_SEASON_OCCU_MOFASHI:
		case SORTLIST_1V1_SEASON_OCCU_YUANSUSHI:
		case SORTLIST_1V1_SEASON_OCCU_ZHANDOUFASHI:
		case SORTLIST_1V1_SEASON_OCCU_ZHAOHUANSHI:
		case SORTLIST_1V1_SEASON_OCCU_GEDOUJIA:
		case SORTLIST_1V1_SEASON_OCCU_QIGONGSHI:
		case SORTLIST_1V1_SEASON_OCCU_SANDA:
		case SORTLIST_1V1_SEASON_OCCU_JIEBA:
		case SORTLIST_1V1_SEASON_OCCU_ROUDAOJIA:
		case SORTLIST_1V1_SEASON_OCCU_SHENQIANGSHOU_NV:
		case SORTLIST_1V1_SEASON_OCCU_MANYOU_NV:
		case SORTLIST_1V1_SEASON_OCCU_QIANGPAOSHI_NV:
		case SORTLIST_1V1_SEASON_OCCU_JIXIESHI_NV:
		case SORTLIST_1V1_SEASON_OCCU_DANYAOZHUANJIA_NV:
		case SORTLIST_1V1_SEASON_OCCU_SHENGZHIZHE:
		case SORTLIST_1V1_SEASON_OCCU_QUMO:
		case SORTLIST_1V1_SEASON_OCCU_SHENGQISHI:
			return (UInt64(value1) << 32) + value2;
		//case SORTLIST_SIXIANG:		return (UInt64(value1) << 32) + UInt64(0xFFFFFFFF) - value2;
		case SORTLIST_CHALLENGE_DAILY:	return (UInt64(value1) << 32) + value2;
		case SORTLIST_FESTIVAL:		return 0xFFFFFFFF - value1;
		case SORTLIST_GET_FLOWER:   return value1;
		case SORTLIST_GIVE_FLOWER:  return value1;
		case SORTLIST_EQUIP_POWER:  return value2;
		case SORTLIST_ACTIVITYCONSUME:	return value1;
		case SORTLIST_ACTIVITYCONSUME1: return value1;
		case SORTLIST_DAY_CONSUME: return value1;
        case SORTLIST_TOWER_1:
        case SORTLIST_TOWER_2:
        case SORTLIST_TOWER_3:
        case SORTLIST_TOWER_4:
		case SORTLIST_TOWER_OCCU_GUIJIANSHI:
		case SORTLIST_TOWER_OCCU_JIANHUN:
		case SORTLIST_TOWER_OCCU_KUANGZHANSHI:
		case SORTLIST_TOWER_OCCU_GUIQI:
		case SORTLIST_TOWER_OCCU_AXIULUO:
		case SORTLIST_TOWER_OCCU_SHENQIANGSHOU:
		case SORTLIST_TOWER_OCCU_MANYOU:
		case SORTLIST_TOWER_OCCU_QIANGPAOSHI:
		case SORTLIST_TOWER_OCCU_JIXIESHI:
		case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA:
		case SORTLIST_TOWER_OCCU_MOFASHI:
		case SORTLIST_TOWER_OCCU_YUANSUSHI:
		case SORTLIST_TOWER_OCCU_ZHANDOUFASHI:
		case SORTLIST_TOWER_OCCU_ZHAOHUANSHI:
		case SORTLIST_TOWER_OCCU_GEDOUJIA:
		case SORTLIST_TOWER_OCCU_QIGONGSHI:
		case SORTLIST_TOWER_OCCU_SANDA:
		case SORTLIST_TOWER_OCCU_JIEBA:
		case SORTLIST_TOWER_OCCU_ROUDAOJIA:
		case SORTLIST_TOWER_OCCU_SHENQIANGSHOU_NV:
		case SORTLIST_TOWER_OCCU_MANYOU_NV:
		case SORTLIST_TOWER_OCCU_QIANGPAOSHI_NV:
		case SORTLIST_TOWER_OCCU_JIXIESHI_NV:
		case SORTLIST_TOWER_OCCU_DANYAOZHUANJIA_NV:
		case SORTLIST_TOWER_OCCU_SHENGZHIZHE:
		case SORTLIST_TOWER_OCCU_QUMO:
		case SORTLIST_TOWER_OCCU_SHENGQISHI:
			return (UInt64(value1) << 32) + UInt64(0xFFFFFFFF) - value2;
		case SORTLIST_GUILD_BATTLE_SCORE: return value1;
		case SORTLIST_GUILD_BATTLE_MEMBER: return value1;

		// value1 表示积分, value2表示时间 积分大的排前面，时间小的排前面,最后按公会id排
		case SORTLIST_GUILD_BATTLE_WEEK_SCORE: 
			return (UInt64(value1) << 32) + UInt64(0xFFFFFFFF) - value2 + id % 100;

		//公会等级排行榜，value1表示公会等级，value2表示公会成立时间，value3表示建筑分，排序规则是等级->公会分->公会成立时间(越早越好)
		case SORTLIST_GUILD_LEVEL: return (UInt64(value1 * 100000 + value3) << 32) + UInt64(0xFFFFFFFF) - value2;
		//added by aprilliu, 2017.04.21
		case SORTLIST_LEVEL_OCCU_GUIJIANSHI:			//鬼剑士
		case SORTLIST_LEVEL_OCCU_JIANHUN:
		case SORTLIST_LEVEL_OCCU_KUANGZHANSHI:				//狂战士
		case SORTLIST_LEVEL_OCCU_GUIQI:
		case SORTLIST_LEVEL_OCCU_AXIULUO:
		case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU:				//神枪手男
		case SORTLIST_LEVEL_OCCU_MANYOU: 					//漫游男
		case SORTLIST_LEVEL_OCCU_QIANGPAOSHI:			
		case SORTLIST_LEVEL_OCCU_JIXIESHI:
		case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA:
		case SORTLIST_LEVEL_OCCU_MOFASHI:		//魔法师
		case SORTLIST_LEVEL_OCCU_YUANSUSHI:
		case SORTLIST_LEVEL_OCCU_ZHANDOUFASHI:
		case SORTLIST_LEVEL_OCCU_ZHAOHUANSHI:		//召唤师
		case SORTLIST_LEVEL_OCCU_GEDOUJIA: 	//格斗家
		case SORTLIST_LEVEL_OCCU_QIGONGSHI:
		case SORTLIST_LEVEL_OCCU_SANDA:
		case SORTLIST_LEVEL_OCCU_JIEBA:
		case SORTLIST_LEVEL_OCCU_ROUDAOJIA:
		case SORTLIST_LEVEL_OCCU_SHENQIANGSHOU_NV:			//神枪手女
		case SORTLIST_LEVEL_OCCU_MANYOU_NV:					//漫游枪手女
		case SORTLIST_LEVEL_OCCU_QIANGPAOSHI_NV:
		case SORTLIST_LEVEL_OCCU_JIXIESHI_NV:
		case SORTLIST_LEVEL_OCCU_DANYAOZHUANJIA_NV:
		case SORTLIST_LEVEL_OCCU_SHENGZHIZHE:
		case SORTLIST_LEVEL_OCCU_QUMO:
		case SORTLIST_LEVEL_OCCU_SHENGQISHI:
			return (UInt64(value1) << 32) + value2;  //value1 表示等级， value2表示经验

		//武器
		case SORTLIST_WEAPON:									//武器总榜
		case SORTLIST_WEAPON_TT_ITEM_HUGESWORD:					//武器-巨剑
		case SORTLIST_WEAPON_TT_ITEM_KATANA:						//武器-太刀
		case SORTLIST_WEAPON_TT_ITEM_REVOLVER:					//武器-左轮
		case SORTLIST_WEAPON_TT_ITEM_HANDCANNON:					//武器-手炮
		case SORTLIST_WEAPON_TT_ITEM_WAND:						//武器-魔杖
		case SORTLIST_WEAPON_TT_ITEM_STAFF:						//武器-法杖
		case SORTLIST_WEAPON_TT_ITEM_SHORT_SWORD:				//武器-短剑
		case SORTLIST_WEAPON_TT_ITEM_GLOVE:						//武器-手套
		case SORTLIST_WEAPON_TT_ITEM_BIKAI:						//武器-臂铠
		case SORTLIST_WEAPON_TT_ITEM_CLAW:						//武器-爪
		case SORTLIST_WEAPON_TT_ITEM_OFG:						//武器-拳套
		case SORTLIST_WEAPON_TT_ITEM_EAST_STICK:				//武器-东方棍
		case SORTLIST_WEAPON_TT_ITEM_CROSSBOW:					//武器-弩
		case SORTLIST_WEAPON_TT_ITEM_RIFLE:						//武器-步枪
		case SORTLIST_WEAPON_TT_ITEM_BEAMSWORD:					//武器-光剑
		case SORTLIST_WEAPON_TT_ITEM_SICKLE:					//武器-镰刀
		case SORTLIST_WEAPON_TT_ITEM_TOTEM:						//武器-图腾
		case SORTLIST_WEAPON_TT_ITEM_AXE:						//武器-战斧
		case SORTLIST_WEAPON_TT_ITEM_BEADS:						//武器-念珠
		case SORTLIST_WEAPON_TT_ITEM_CROSS:						//武器-十字架
		case SORTLIST_WEAPON_TT_ITEM_SPEAR:						//武器-矛
		case SORTLIST_WEAPON_TT_ITEM_STICK:						//武器-棍
			return value2;										//level: 表示装备等级 value1 表示强化等级，value2表示评分 ,value3表示资源id
		case SORTLIST_PREMIUM_LEAGUE:							//赏金联赛
			return (UInt64(value1) << 32) + UInt64(0xFFFFFFFF) - value2;	// //value1 表示积分, value2表示时间 积分大的排前面，时间小的排前面
		//end of  aprilliu
		
		}
		return 0;
	}

	UInt64 GetSortFactor() const
	{
		return GetSortFactor(sortType, id, value1, value2, value3);
	}

	ObjID_t		key;		//主键   数据表内的主键
	ObjID_t		id;			//id     该表项(排行榜项)表示的对象的 object id.比如：如果是武器榜，就表示该装备对象的object id,相应的ownerId 就表示该武器所属的玩家对象id
	UInt8		sortType;	//排行榜类型

	std::string	name;		//名字
	UInt32		zoneId;		//区号
	UInt8		quality;	//品质
	UInt16		level;		//等级
	UInt8		vip;		//vip等级
	UInt8		occu;		//职业
	UInt8		sex;		//性别
	ObjID_t		ownerId;	//拥有者id
	UInt32		ownerAccid;	//拥有者账号id
	std::string	ownerName;	//拥有者名字
	std::string	tribeName;	//部落名
	UInt32		value1;		//通用数据1
	UInt32		value2;		//通用数据2
	UInt32		value3;		//通用数据3

	UInt32		updateTime; //数据更新时间

	bool		bDirty;		//脏标志

	UInt32		guildMemberNum;	// 公会成员数量,这个不存到数据库
};

/**
*@brief 排行榜条件限制
*/
inline UInt32 GetSortFactorLimit(int type)
{
	switch(type)
	{
	case SORTLIST_PET:					return 3000;
	case SORTLIST_EQUIP_POWER:			return 10000;
	default:	return 0;
	}

	return 0;
}

struct GiveRewardIndex
{
	GiveRewardIndex() : sum(0), start(0), count(0), isOver(true) {}

	UInt32 sum;

	UInt32 start;
	UInt32 count;

	bool isOver;

};

//佣兵团排行榜下次结算时间
#define PARAM_SORTLIST_ADVENTURE_SETTLE_TIME "sortlist_advent_settle_time"

#endif
